### ISSUE TITLE
Missing javadocs at http://junit-team.github.io/junit/javadoc/

### ISSUE THREAD

**Issue by alb-i986** [junit-team/junit4#1023]
Looks like that [recent commits to gh-pages](https://github.com/junit-team/junit/commits/gh-pages) deleted many many files under /javadoc, e.g.:
https://github.com/junit-team/junit/commit/0f570aa347b56116276f7110e879717ab561f2f4

In particular, one URL that I had in my history (i.e. I'm sure it was reachable)
http://junit-team.github.io/junit/javadoc/4.10/org/junit/rules/TestRule.html
Also same URL, 4.11, is missing
http://junit-team.github.io/junit/javadoc/4.11/org/junit/rules/TestRule.html

Also, maybe not related to this bug report, I see that in the [homepage](http://junit-team.github.io/junit/), there is a bullet point for "javadocs". but it's not a link as I'd expect.

**Comment by marcphilipp** [comment]
The Javadocs are now available again at http://junit.org/junit4/javadoc/4.10/ and so on.
