### ISSUE TITLE
assertTrue()/assertFalse() should include an error message by default

### ISSUE THREAD

**Issue by kluever** [junit-team/junit4#1030]
assertTrue(falseMethod()) gives:
    junit.framework.AssertionFailedError
assertEquals(true, falseMethod()) gives:
    junit.framework.AssertionFailedError: expected:<true> but was:<false>

Can we add default error messages for assertTrue(boolean)/assertFalse(boolean)?

The easiest thing to do is probably just to call assertEquals(true, condition), etc.

**Comment by mlgiter** [comment]
I do vote up this issue. Other frameworks support showing actual value capability and it's essential.

**Comment by ChaminW** [comment]
I do vote up this issue since it's important to have a more informative error message for assertTrue and assertFalse. My colleagues and I are reluctant to use assertTrue/assertFalse because of this.

**Comment by stefanbirkner** [comment]
@ChaminW You can use `assertTrue("Some more specific message.", value);` for more informative error message.

**Comment by BMomani** [comment]
I know its closed but let's vote in emoji 
leave 👍 if you are in favor of the change (doing the requested ch)
leave 👎 if you are in favor of the decision
