### ISSUE TITLE
Add @Rule(around="otherRule") to specify order

### ISSUE THREAD

**Issue by shicks** [junit-team/junit4#1045]
By naming another @Rule field/method in an annotation, this would allow topologically sorting the rules to provide a deterministic order. Should probably apply to @ClassRule, too.

**Comment by FeuRenard** [comment]
PR #1418 was rejected because you don't like the feature. As a consequence this issue should be closed.

**Comment by stefanbirkner** [comment]
You're right. Thanks.

**Comment by kcooney** [comment]
Note for other people that may be following along: we are considering other ways to specify the order of rules via the `@Rule` annotation. See #1417
