### ISSUE TITLE
JUnit 5.0 API backwards compatibility

### ISSUE THREAD

**Issue by Tibor17** [junit-team/junit4#1079]
We should list all APIs of JUnit 5.0 which neccessarily breaks backwards compatibility against JUni 4.x.
This should list removed API marked `@Deprecated` in JUnit 4.x as well.

This information should appear in JUnit wiki page.
It is very important info for the Maven in order to adapt our internal junit providers accordingly.

**Comment by kcooney** [comment]
So far, the only comparability issues is from removing APIs that have been deprecated since 4.11 or earlier. See the release notes for details. When we get closer to release, we should certainly call out compatibility issues in a separate section of the release notes.

Thanks for the reminder

**Comment by Tibor17** [comment]
Put label 5.0. This would mean that every PR should find broken API. This would be a bit difficult with a lot of changes.

**Comment by kcooney** [comment]
Having a lot of changes on the 5.0 branch would be a good problem to have ::-)

**Comment by kcooney** [comment]
We no longer are planning a 5.0 release from this codebase
