### ISSUE TITLE
enhancement: assertRelativeError

### ISSUE THREAD

**Issue by jason-sachs** [junit-team/junit4#1081]
[`assertEquals()`](https://github.com/junit-team/junit/blob/master/src/main/java/org/junit/Assert.java#L550) uses absolute error calculated by subtraction. Could you add another method e.g. `assertRelativeError` that calculates error using division? A lot of applications use relative error for asserting equality in mathematical situations.

```
Math.abs(d1 - d2)      // absolute error

Math.abs(d1/d2 - 1.0)  // ratiometric a.k.a. relative error
```

**Comment by kcooney** [comment]
It was never JUnit's goal to provide every possible assertion method, and it should be quite easy to write this yourself, so I'm tempted to close this bug

**Comment by jason-sachs** [comment]
yeah, I'd kind of feel the same way, it's just that you have to choose *something* when comparing floating point numbers (exact equality is a recipe for disaster), and these two are the main methods. I would almost go so far as to say that junit's method is the less preferable of the two.

If someone else with a strong numerical analysis background looks at this and says "nah, absolute error is the more important one", then I'll slink away, + feel free to close.

**Comment by ggupta2005** [comment]
Hi jason-sachs, I am new to junit. I agree with kcooney that your requirement can be met using the current set of junit APIs. All you need to do is to call assertEquals() in the following manner:-

double d1 = 95.5;
double d2 = 100.0;
double delta = 0.10;
assertEquals(d1/d2, 1.0, delta);

**Comment by ggupta2005** [comment]
Hi jason-sachs,

I am new to juint and I am a big fan of this way of documenting the unit tests for future validation. I am looking for some code contribution to junit. I looked into the implementation of assertEquals() for doubles and float. Following is the definition:-

132     /**
133      * Asserts that two floats are equal concerning a positive delta. If they
134      * are not an AssertionFailedError is thrown with the given message. If the
135      * expected value is infinity then the delta value is ignored.
136      */
137     static public void assertEquals(String message, float expected, float actual, float delta) {
138         if (Float.compare(expected, actual) == 0) {
139             return;
140         }
141         if (!(Math.abs(expected - actual) <= delta)) {
142             failNotEquals(message, new Float(expected), new Float(actual));
143         }
144     }

From the definition is seems like delta needs to be positive in order for this assertEquals to work in a proper manner. However, in some cases users may pass negative value of delta inadvertently and may get unexpected failures while using this API. In such scenarios, in line 141 we will compare a positive quantity with a negative number. My suggestion is that we check for negative value of delta and either throw an value error exception or call fail() and return from this function without getting to line 141. 

Please let me know what are your thoughts.

Thanks,
gaurav

**Comment by adrianosimoes** [comment]
This issue seems to be staled. Should we accept @ggupta2005 suggestion?
Other solution would just be to use abs(delta)?

**Comment by kcooney** [comment]
What we should do if you pass a negative delta is an interesting question but unrelated to this issue. I don't think we should use abs(delta) since that wouldn't be a behavior one would expect.

I am going to close this issue. If you want the allowed error to be relative you can make the delta relative to your expeted value.

**Comment by jason-s** [comment]
>All you need to do is to call assertEquals() in the following manner:-
>
>    double d1 = 95.5;
>    double d2 = 100.0;
>    double delta = 0.10;
>    assertEquals(d1/d2, 1.0, delta);

No, that won't work, because it trips a divide-by-zero error if d2=0. There's some real subtleties here and if users have to provide their own functionality they may get it wrong.

**Comment by jason-s** [comment]
@kcooney I have no major problem with this issue being closed, but I'm disappointed, mainly because of the following:

- Users that naively try to use `assertEquals(double, double)` will see that [this method is deprecated](http://junit.sourceforge.net/javadoc/org/junit/Assert.html#assertEquals(double, double)) (and rightly so):

        Deprecated. Use assertEquals(double expected, double actual, double epsilon) instead

- Users that then look for the [3-argument `assertEquals()` for `double`s](http://junit.sourceforge.net/javadoc/org/junit/Assert.html#assertEquals(double, double, double)) will read:

        Asserts that two doubles or floats are equal to within a positive delta

    There is no mention of what actually is calculated, or why this is important; you have to look at the source code if you want to know what it does. Does "within a positive delta" mean an absolute or a relative error? It should say something like "Equivalent to `assertTrue(Math.abs(expected-actual)<delta)`" and explain that floating-point numbers cannot reliably be compared exactly because of rounding issues. IMHO it should also state that a relative error is more appropriate in many cases.

But that's just my opinion.

**Comment by kcooney** [comment]
@jason-s We would happily accept pull requests to improve the documentation.

**Comment by jason-s** [comment]
Fair enough.
