### ISSUE TITLE
@Ignore status changes to incomplete, if there is an exception in @BeforeClass method

### ISSUE THREAD

**Issue by OpenHelios** [junit-team/junit4#1090]
The following test class helps to show an issue for the @Ignore status on the first test method.

After running the given test class only with the ignored test method:
- testIgnoreAnnotation has status ignored (this is the expected status)

After running the given test class with the ignored and the other method (uncomment second test method):
- testIgnoreAnnotation has status incomplete (status ingnored is expected)
- testSuccess has status incomplete (this is the expected status)

``` java
package test;

import static org.junit.Assert.*;

import org.junit.BeforeClass;
import org.junit.Ignore;
import org.junit.Test;

public class IgnoreAnnotationTest {

    @BeforeClass
    public static void beforeClass() {
        throw new IllegalStateException("test for @Ignore annotation exception in beforeClass() method");
    }

    @Ignore("This method should have ignored status in every case.")
    @Test
    public void testIgnoreAnnotation() {
        fail("This method is ignored.");
    }

    /**
     * Uncomment this method and the ignored status of {@link #testIgnoreAnnotation()}
     * changes to incomplete.
     */
//  @Test
//  public void testSuccess() {
//  }

}
```

**Comment by kcooney** [comment]
Thanks for the report

I suspect the `@BeforeClass` is not run if all test methods are annotated with `@Ignore`. If so, I feel this behavior isn't unreasonable (if the `@BeforeClass` method consistently throws, you need to fix your test).

If you can find a simple change to JUnit that will get the behavior you want, I would be happy to review it.

**Comment by OpenHelios** [comment]
There is a pull request #1091 with a change including a JUnit test to verify my expected behavior.

**Comment by adrianosimoes** [comment]
The pull request that originated from this story ( #1091 ) ended up being close. Should we close this story also?

**Comment by kcooney** [comment]
@adrianosimoes thanks for pointing that out. Closed.
