### ISSUE TITLE
Show contents actual array when array lengths differ.

### ISSUE THREAD

**Issue by sf105** [junit-team/junit4#1127]
assertArrayEquals() will short-circuit and only report lengths if they differ. I find this insufficient for easy diagnosis. Can the assertion show the actual result? Happy to provide a pull request if this is accepted.

**Comment by marcphilipp** [comment]
I was about to ask whether you have considered using Hamcrest… ;-)

Having said that, I would support such an enhancement.

**Comment by sf105** [comment]
I did :), but I was doing some training and didn't want to pull in the extra library.

**Comment by PostalBear** [comment]
Hi folks, if you don't mind I would propose these pull requests. 
I used feature of Hamcrest matcher to print content of array if length is different, as it was proposed by @marcphilipp.

PS sorry for duplicated pull request, I had problem with my Git :(

**Comment by kcooney** [comment]
@PostalBear I see the commits but no pull request.

I don't think Marc was suggesting that the fix in JUnit would use Hamcrest; I think he was wondering if Hamcrest  ave the error message that the original poster expected.

FYI, we will most likely be removing dependencies from JUnit to Hamcrest, so if we change JUnit to resolve this issue, we should find a fix that doesn't use Hamcrest APIs.

**Comment by PostalBear** [comment]
@kcooney I got your point, indeed it is possible to achieve what original poster wanted by using Hamcrest matcher (since I did it same way). 
In such a case I will take a look to other low priority issues, instead of dealing with this one. 

PS What do you think about closing this issue ? I'm asking cause it could be easily solved without any modifications of JUnit code at all.

**Comment by kcooney** [comment]
I don't have a strong feeling for whether or not we should change the current behavior. If we do, I think we should do it in the junit5 branch.

We did do some optimizations on this code in 4.12, so it's possible the JUnit version is faster than the Hamcrest one.

**Comment by atulagrawal** [comment]
PR for this issue has been merged. Can you please close this issue. Thanks.
Ref - https://github.com/junit-team/junit4/pull/1300

**Comment by marcphilipp** [comment]
Thanks, @atulagrawal!
