### ISSUE TITLE
Allow Rules to modify After/Before Actions

### ISSUE THREAD

**Issue by RainerW** [junit-team/junit4#115]
I need a way to intercept a failing Test method BEFORE any After Method was called.

The rule i'm working on should create a screenshot of the app in case a Test failed. This is not possible, because my rule get's a RunAfters Instance passed in, on which I call base.evaluate(). But the RunAfters instance allready handles the @After part. So when my rule gets control again, all after methodes are allready executed. And therefore the applications is allready down, making now a screenshot is useless.

So I need a Way to modify the After Statements passed in.

a) Im my case it would be enough to create my own RunAfters. Therefore RunAfters should have a getter for it's private fields. So I can delegate the afters after i created the screenshot.

b) But, the nicer solution would be, to allow to modify the after & before list. I can imagine a Rule which does execute some of the @Before or @Afters only if some conditions are met. Or Injects it's own Before/Afters on the fly.

**Comment by kcooney** [comment]
Closing. We won't be adding way to intercept things between the test and the `@After`. The general solution is to move the code from `@After` to another rule and use `RuleChain`
