### ISSUE TITLE
JUnit needs a better story for extensibility

### ISSUE THREAD

**Issue by rschmitt** [junit-team/junit4#1161]
This issue is a continuation of the discussion in #1158. This is the essential issue, and it prevents me from using JUnit for anything other than toys:

> It's starting to sound like the abstractions that JUnit provides are inadequate.
> 
> On the one hand, we've got Runner, which is potentially very powerful, but that power can only be accessed through subclassing. I can't compose two different Runners to combine their effects.
> 
> On the other hand, we have TestRule, which is interface-based and composes well, but which isn't powerful enough to safely extend or modify the way test methods are executed, therefore making them largely useless for anything other than simple callbacks (e.g. TemporaryFolder, ErrorCollector, Stopwatch) and filters (Verifier). The main exception is Timeout.

There are tons of interesting and useful custom test runners for JUnit, all of which are utterly non-interoperable with each other. They just don't compose, and there are really fundamental reasons why they can't compose under the current architecture. JUnit 5 would be a fantastic opportunity to tackle this problem. Is this something that people have been thinking about for a while? Is there a wiki or something that discusses potential design directions? The only things I'm aware of targeting JUnit 5 are (1) removal of Hamcrest matchers (yay), (2) removal of a really old runner (yay), (3) targeting of JDK6 (what's the point? Do you need `ArrayDeque` or something?).

**Comment by rschmitt** [comment]
Appears related, if somewhat indirectly, to #1160.

**Comment by kcooney** [comment]
Also related to #958

**Comment by Fuud** [comment]
Let me try to summarize what is wrong (IMHO) in current JUnit design:
1. It implicitly assumes scheme of class. For example, if we want to parallelize test, we should extend ParentRunner (it is the only way to obtain RunnerScheduler) and pass class in constructor. ParentRunner will parse class as regular JUnit test. When I added support for parallel test execution in Spock I forced to pass Object.class into super constructor because Spock allow @BeforeClass to be instance method and ParentRunner forbid this (see spockframework/spock#67)
2. Same for Description - It attached to classes/methods.
3. Filter API is a little bit tricky to use.

What I suggest:
1. Decouple description from java objects, add `location` field to `Description` (it should support various types of locations: class/method, file, line-number, etc) so IDE will be able to navigate.
2. Add to Description fields for reference to setup/test/cleanup functions. This approach make IDE integration more clear. On user request IDE can filter out unnecessary nodes and leave only requested leaves.
3. Runner will be able to add new nodes (at preparation time and at execution time), manipulate them, add setup, cleanup methods, change test method, etc.

**Comment by rschmitt** [comment]
This isn't really what I'm getting at. The problem I want to see addressed is not "how do we make our monolithic test runner more powerful," but rather "how do we break up our monolithic test runner in a way that facilitates the creation of composable extensions?" The very idea of a "test runner," in its current form, is probably a non-starter. It's responsible for a lot of unrelated functionality:

1. Discovering/generating test cases
2. Instantiating test classes
3. Calling test methods
4. Calling various before/after methods
5. Calling into TestRules and legacy MethodRules
6. Sending messages to listeners, and figuring out which messages to send, and when to send them

It's interesting to consider two things:

1. What standalone interfaces for these tasks would look like
2. Which of these interfaces could be composed

For example, some people insist on using Spring to inject fields into test classes, or to just create the instances from whole cloth. Why not just configure an instantiator and leave the rest of the test runner alone? This would also make it possible to use a different instantiation policy: for instance, instead of the default JUnit behavior (one instance per test case), substitute the TestNG behavior (one instance per class).

Calling test methods is an interesting one, especially if instantiation is done lazily. For instance, consider a `RetryInvoker` that applies a retry policy to a test in order to tolerate transient failures. If the test fails and you decide to rerun it, you can construct a new instance and call into it; this is not currently possible using a `Rule`. Another interesting case is a hypothetical `RepeatInvoker`, which runs a test multiple times (possibly in parallel). Such an invoker could create one instance per invocation, or one instance for all invocations, or one instance per thread.

People could also substitute a custom instantiator for "performance" reasons. (I'm skeptical of this one, but it's a valid hypothetical.) JUnit targets JDK5 of course, and uses vanilla reflection to construct objects, but someone using JDK7 or later could replace a reflective invoker with one that uses a `MethodHandle`. There may be other reflection use cases elsewhere that could be similarly sped up by using `invokedynamic`. This is an example where it really _would_ make sense to vend an extension library for people running newer versions of Java.

The before/after methods might be generalizable into some sort of Interceptor concept that would also subsume the `TestRule` interface. We've already seen that interception is composable; the trick is getting the order right. You could imagine doing things like combining Spring and PowerMock functionality (an interceptor for the former that handles injection of non-mocked fields, an instantiator for the latter that does bytecode manipulation in a separate classloader) that are _almost_--but not quite--possible with `TestRule`s today. (There's actually a `MethodRule` for PowerMock that _can_ be composed with the Spring runner, but like most useful Rules, it's a hack.)

Messaging is another interesting one. I've seen it go wrong with TestNG: a test with a retry policy could succeed on the second attempt, but the messaging from the first attempt would result in a test suite failure (the transient failure gets reported to the class responsible for emitting a status code upon `System.exit`). That's an example of ordering being important; it's also worth thinking about how static vs. dynamic typing plays in to this (in other words, does there need to be a prenegotiated contract for all notification messages, or can they be extended by library authors?). I'm not sure what use cases people have for test listeners (they seem to be a popular feature), or how frequently they're being used as a substitute for some other, more ideal feature.

It's also worth thinking about whether JUnit could be made more useful as a library, rather than a framework. (My working definition of a framework is "a library that calls you.") I see two basic types of use:

1. Invoking JUnit programmatically (keep in mind that Java is probably getting a [first party REPL](http://openjdk.java.net/projects/kulla/) sooner or later)
2. Reusing pieces of JUnit in other test contexts (e.g. the `Assert` class is dead simple and can be used anywhere)

It's obviously possible to invoke JUnit programmatically, but there may be ways to improve that functionality (e.g. a first-class data model for test suites, as an alternative to classes that contain nothing but annotations which, as @stuarthalloway pointed out, is pretty backwards).

**Comment by rschmitt** [comment]
Oh, here's another feature: test case ordering (e.g. in dependency order). This could be considered a form of test case discovery: you can have not only multiple discovery strategies (discover from the classpath, discover from the command line, discover from a data file, discover from a prior test run), but multiple _types_ of discovery strategies (some add tests, some reorder them, some remove them), and the overall test suite is determined by the collection of discoverers and which order they run in.

I think it's also important for discovery to be dynamic/incremental. This is a severe weakness of the current Theories runner: all test cases are generated and buffered up-front, which discourages exhaustive generative testing.

One additional detail of dependency-order execution is how to deal with failure. If B depends on a failed test A, it should be skipped. Where does that logic live? Where is the decision made? How does it interact with other extensions?

**Comment by rschmitt** [comment]
Oh, that reminds me: the assumption that all test cases are known up front is deeply, _deeply_ woven into the very architecture of JUnit. The `Runner` class itself has `testCount` as one of its three methods, and if you go even _further_ up the class hierarchy you find this Javadoc on `Description`:

```
Descriptions are implemented as a single class rather than a Composite because they are entirely informational. They contain no logic aside from counting their tests.
```

This was pretty clearly done to facilitate the creation of IDE plugins and the like, which means that incremental test discovery won't merely break everyone who's subclassing `BlockJUnit4ClassRunner`. I don't know what to do with this information, but at a glance the situation looks pretty bleak.

**Comment by Fuud** [comment]
Ok. Lets try to write down something specific.
I prefer to separate test execution in two stages: initial discovery and execution (execution can also discover something at run time).

Initial discovery subsystem builds some sort of ExecutionPlan (from IDE side it is equal to Description). 

```
public interface ExecutionPlan {
  TestResult run(RunListener listener);

  TestResult run();
  
  List<ExecutionPlan> getKnownChildren();
  
  String getId();
  
  String getDisplayName();
}
```

All object creations, setups and cleanups, iteration over children etc are hidden into run method.
IDE can use getKnownChildren to render test execution before test run.
`run` returns TestResult thus it can be used programmatically like this:
```
  TestResult testResult = ClassicJUnit.parseClass(MyTest.class).run();
  if (testResult.hasFailures()) ...
```

`ExecutionPlan` can have some well-known (by IDE developers and extension developers) implementations to support filtering, sorting, multithreading.

**Comment by rschmitt** [comment]
@kcooney @marcphilipp any thoughts in general? What's on or off the table for JUnit 5?

**Comment by kcooney** [comment]
There are a lot of good ideas here. Many of the problems raised here are ones that have bothered me in the past.

I personally think that the next step is for a few passionate people to do some prototyping of these ideas, figure out what design patterns work, take a few use cases (dependency injection, parameterized tests, etc).If it looks promising, and if we can provide some kind of compatability layer, we can discuss getting the changes into JUnit.

I think we all get too caught up on whether feature X will be in JUnit 5. We should focus on what problems users have, which ones we understand enough to solve well, and let the features land where they land. Features that can break things go in major releases, non-breaking changes go in the next release (be it major or minor).

**Comment by rschmitt** [comment]
@kcooney I think that's an excellent philosophy. I've noticed however that the JUnit team is very conservative and it occurred to me that dynamic test discovery (and the implications for tooling) might be considered too radical a change, even for a major release.

**Comment by rschmitt** [comment]
Your "compatibility layer" proviso is interesting, and it makes things much more difficult considering the limitations of the current execution model.

**Comment by kcooney** [comment]
@rschmitt the beauty of prototyping is that you don't have to be conservative at all. You're just experimenting to try out some ideas, with the knowledge that most likely you will throw much of it away.

It would be challenging to add a new way to run tests without some kind of compatibility layer, because we would need to update all the IDE and build tool plugins to support running the new style of tests. If the improvements were large, and if we had many people willing and able to update the plug-ins, then *possibly* we only need a way to run JUnit4-style tests with the new APIs, but I suspect we wouldn't have the impact we want if we couldn't run new-style tests with the JUnit4 `Request` API.

**Comment by rschmitt** [comment]
Prototyping is a good way to discover the limitations of an approach, but it's not a good way to identify requirements or basic misconceptions. The requirement of forwards _and_ backwards compatibility could be a significant impediment, depending on your definition of "new-style tests." Insisting on _too_ much compatibility could result in JUnit getting stuck in a local maximum.

It's probably worth noting that TestNG has had this kind of dynamic execution model for a long time. In general, there is precedent for build tools, IDE plugins, etc having to support incremental discovery.

One other approach that might work is to support execution of new-style tests on JUnit 4, but with severely diminished reporting capabilities, such that a single dummy test stands in for all dynamically discovered tests.

**Comment by kcooney** [comment]
@rschmitt all that I was trying to say is that if someome creates a new model for running tests, and tests using that model cannot be run from the existing APIs in `JUnitCore` and `Request`, then someone will either need to work with the plugin owners to use the new APIs, or they will be limiting their user base.

Assuming we want to support incremental discovery of tests, perhaps a dynamically created test would need to be associated with a parent test case (not test suite). When you run new-style tests using the JUnit 4 APIs, failures in the dynamically created test would me associated with the parent.

But I think we are getting ahead ourselves. We need a few people passionate about this idea to create a new project (probably on github) that depends on JUnit, and start experimenting with ideas. If things look promising, then we can look into compatibility with "legacy" JUnit tests. I personally agree with you that requiring forward and backward compatibility is too big of a constraint *during the early prototyping phase*, but when to worry about which challenges is entirely up to this new team.

Do you think you have time to work on this? Unfortunately, I won't have time for the foreseeable future.

**Comment by jlink** [comment]
Those topics (extensibility and runtime model) are also part of the "JUnit
5/Lambda crowdfunding campaign" which will start later this month or early
in August. We're in the final stages of setting up the campaign, and
development (if the funding goal is reached) will probably start in October.

Of course, any additional prototyping and concrete experimentation is
welcomed. What I don't think makes a lot of sense is just collecting
requirements and wishes since we already have many more than could be
reasonably covered in a few months of work.

cheers,
Johannes

2015-07-13 7:00 GMT+02:00 Kevin Cooney <notifications@github.com>:

**Comment by kcooney** [comment]
These should be addressed in JUnit 5
