### ISSUE TITLE
Allow custom behaviour for Description.testCount()

### ISSUE THREAD

**Issue by stikkanen** [junit-team/junit4#1166]
We have a test suite with custom runners using JUnit 4.11. The test suite is run using Eclipse. The total number of tests displayed in Eclipse is not correct (because of our customizations), and as the constructors in org.junit.runner.Description are private, there is no (sane) way to override the method Description.testCount(). Is it possible to make the Description class extendable or to provide some other mechanism allowing for customization of the testCount method?

**Comment by kcooney** [comment]
I suspect that many third-party extensions would break if the test count differed from the number of description objects. Could you go into some details as to why your customizations cauae the test count to not match the number of description objects?

**Comment by stikkanen** [comment]
We run the tests parameterized so that the parameters are read from external configuration files. Each test method is run from 1 to n times (where n changes based on the content of the external parameter file). For example, one test might have the input value a = 1 and expected output value of b == 2 and another test the input value a = 2 and expected output value of b == 1.

When a test method is e.g. configured to run twice (with different parameters), Eclipse displays "Runs: 2/1". Displaying the correct total number of tests would not only be more aesthetically pleasing, but would give the user some expected information about how long the tests are going to run.

**Comment by kcooney** [comment]
JUnit doesn't have good support for the same test being run multiple times. The test listener is passed the test's `Description` when the test runs (and if it fails) so if a test runs multiple times the listener cannot tell the two runs apart.

Can you create unique `Description ` instances for each set of input values?

**Comment by Buzz2Buzz** [comment]
What's the answer finally for this behaviour ?

**Comment by marcphilipp** [comment]
Repeating @kcooney's question:

> Can you create unique `Description` instances for each set of input values?

**Comment by Buzz2Buzz** [comment]
I'm sorry I'm not sure to use it properly ... 
In my case it's not a custom Runner but a Rule. This rule takes the statement to execute and repeats it n time.

```
public class ParallelStatementRule extends ExternalResource{
..
    @Override
    public Statement apply(Statement test, Description description) {
        return new ParallelStatement(test,nbIterations,threadPool, description);
    }
..
}
```

```
public class ParallelStatement{
..
protected Description description;

 @Override
    public void evaluate() throws Throwable {
        List<Callable<Void>> callables = new ArrayList<>();
        for (int i=0 ; i < nbIterations ; i++) {
            Description child =
                    Description.createTestDescription(description.getTestClass(), description.getDisplayName() + " with driver " + i, (Annotation[])description.getAnnotations().toArray());
            description.addChild(child);
            callables.add(new CallableStatement(test, errorCollector));
        }
 .....
    }
..
}
```

That's why I need a new `Description` for each loop. Is this the right way to do it ? Because JUnit console log isn't accurate.

**Comment by kcooney** [comment]
@Buzz2Buzz Rules should execute the statement chain more than once. I'd you want to run a test method n times you need a custom runner.

**Comment by kcooney** [comment]
I am going to close this. Too many things would break if the test count differed from the number of description objects.
