### ISSUE TITLE
Make org.junit.runner.Description's constructor protected so that it can be subclassed

### ISSUE THREAD

**Issue by pniederw** [junit-team/junit4#117]
My org.junit.runner.Runner dynamically generates new tests at runtime. In order to make them behave nicely in IDEs, I'd like to override org.junit.runner.Description.getMethodName(). However, I can't subclass Description because its only constructor is private.

**Comment by scottresnik** [comment]
I have a use for this.  This would be handy in my use case where I'd like to set the category of a test class contained in a suite to the suite's category via a customized runner.

**Comment by kcooney** [comment]
@scottresnik interesting. How would subclassing `Description` help?

Note we were planning on making `Description` to be immutable in the future, which we wouldn't be able to do if the constructor was protected.

**Comment by scottresnik** [comment]
I'm injecting the category attribute from the suite into the child test class description as the child runners are built.  I'm using the `public static Description createSuiteDescription(String name, Annotation... annotations)` builder method, and it doesn't set the TestClass on the description.

**Comment by kcooney** [comment]
@scottresnik could you create a separate issue for the desire to be able to create a `Description` with the attributes you want? When we create the builders for the immutable descriptions, we'll make sure you can create a `Description` with the attributes that you need.

**Comment by adrianosimoes** [comment]
Since there is already an issue for the proposed solution ( #1135  ), should this issue be closed?

**Comment by kcooney** [comment]
I don't think we want to give `Description` a protected constructor. Every time we've discussed issues related to this, we've pushed towards either more static methods in `Description` for creating instances or a builder.
