### ISSUE TITLE
Discerning test failures which are not genuine

### ISSUE THREAD

**Issue by alb-i986** [junit-team/junit4#1177]
Sometimes, the test infrastructure supporting your tests happens to fail causing your tests to fail.

For example, Selenium tests, which typically run against a [Grid](https://github.com/SeleniumHQ/selenium/wiki/Grid2), may fail due to a [GridException](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/common/exception/GridException.java). Or [UnreachableBrowserException](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/remote/UnreachableBrowserException.html).

In these cases, the failure is not genuine, and I think it would be nice if JUnit helped discerning at a first glance, just like an `@Ignored` test or a failed assumption is reported differently than normal failures.

BTW, discerning may involve checking the class of the Throwable; other unlucky times its message, if any.

I don't think it's currently possible to achieve this behaviour, is it?

Thanks

**Comment by rschmitt** [comment]
A fairly generic way of dealing with transient failures is a bounded number of retries. You could try adding a RetryRule like [this](https://gist.github.com/abyx/897229) to your tests.

**Comment by alb-i986** [comment]
Hi @rschmitt
A retryer certainly helps when dealing with browser tests. But you know.. even a retried test may.. fail :)

**Comment by kcooney** [comment]
There's no way to do this currently. I'm not sure how JUnit could know that a test failure shouldn't be reported as a failure. You could use a `Rule` to cause the test to not fail.

I wouldn't recommend using a rule to retry tests. JUnit creates a unique instance of the class for each test method, but if you use a rule to retry you would get the same instance run multiple times, which means that your tests's fields would have the values from the previous run.
