### ISSUE TITLE
Rename leftover fields with f-prefix

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit4#1182]
Due to serialization issues (see #976) we have decided not to rename certain fields in classes that implement `Serializable`. We should increment the `serialVersionUID` of those classes and rename the fields in 5.0.

Here's a list of classes:
- ArrayComparisonFailure.java - junit/src/main/java/org/junit/internal
- AssumptionViolatedException.java - junit/src/main/java/org/junit/internal
- ComparisonFailure.java - junit/src/main/java/org/junit
- Description.java - junit/src/main/java/org/junit/runner
- Failure.java - junit/src/main/java/org/junit/runner/notification
- InitializationError.java - junit/src/main/java/org/junit/internal/runners
- InitializationError.java - junit/src/main/java/org/junit/runners/model
- MaxHistory.java - junit/src/main/java/org/junit/experimental/max
- MultipleFailureException.java - junit/src/main/java/org/junit/runners/model

**Comment by kcooney** [comment]
This would likely break people
