### ISSUE TITLE
Implementations of RunnerBuilder#runnerForClass/safeRunnerForClass(...) return null

### ISSUE THREAD

**Issue by mkeller** [junit-team/junit4#1193]
Most default implementations of `RunnerBuilder#runnerForClass/safeRunnerForClass(...)` return null, although the API Javadocs sound as if they would always return a runner.

**Comment by kcooney** [comment]
The javadocs should state that implementations may return. That being said, unless you depend on internal code, `safeRumnerForClass` will not return null.

**Comment by mkeller** [comment]
safeRunnerForClass will return null whenever runnerForClass returns null. It just delegates to the latter and only catches Throwable.

**Comment by kcooney** [comment]
In practice it shouldn't return null because usually nom-internal code is passed in a https://github.com/junit-team/junit/blob/master/src/main/java/org/junit/internal/builders/AllDefaultPossibilitiesBuilder.java

**Comment by mkeller** [comment]
I see. Only the internal builders used by AllDefaultPossibilitiesBuilder break the rules, but the AllDefaultPossibilitiesBuilder itself doesn't, because the last builder is the JUnit4Builder, which never returns null.
So it's not an API issue but rather a sloppy implementation of the internal builders that only works as long as all builders are kept internal.
