### ISSUE TITLE
timeout annotation nor global rule not working as expected

### ISSUE THREAD

**Issue by sshakil** [junit-team/junit4#1207]
I encountered a situation where the timeout annotation param set on a test nor the defined global timeout rule were kicking in.  This was due to an outstanding commit on an update on a row that the code in test was trying to update.  Upon committing and rerunning the test, the test completed within a couple of seconds (the timeout was set to 20 seconds).

I don't have the liberty to give the code or more details at the moment, but I'll try to recreate it once I'm home.

**Comment by kcooney** [comment]
Without a way to reproduce this, we can't work on a fix. I'll close it for now, but feel free to reopen if you can reproduce the problem.
