### ISSUE TITLE
TemporaryFolder doesn't work for parallel test execution in several JVMs

### ISSUE THREAD

**Issue by tryge** [junit-team/junit4#1223]
Our observation is that the TemporaryFolder is deleted during tests when we run our gradle build with the `--parallel` flag.

We have several thousand unit tests that in part run in parallel in several JVMs (spawned by gradle). What I think happens is that when `junit` retrieves a temporary file and deletes it in order to create a directory instead using the same name, between the point where the file is deleted and the directory is created another test in another JVM chooses the same name for the temporary folder. The first test to finish execution deletes the whole directory and the second throws an exception because the directory (or a file in it) doesn't exist anymore.

One option for us is to switch to `Files.createTempDirectory`, but I like how `TemporaryFolder` works so I'm in favour of keeping it (and not changing all of our tests...)

**Comment by marcphilipp** [comment]
This issue has been addressed in #1304.

**Comment by jzgithub1** [comment]
Was this issue every fixed for certain?
