### ISSUE TITLE
Test case failures are hidden by temporary folder rule's assured deletion failures

### ISSUE THREAD

**Issue by reinholdfuereder** [junit-team/junit4#1224]
See https://github.com/reinholdfuereder/junit/tree/test-case-failure-is-hidden-by-temporary-folder-rule-assured-deletion-failure for a little test case that demonstrates the problem.

It happened that a test case failure (on Windows) actually had the side effect of a leftover open file handle to a temporary file/folder and so the assured deletion of the temporary folder rule failed. And the latter failure hided the first or actual one.

In theory two approaches would be possible:
(1) Multiple failures
(2) Just keep the first one (the actual one) and solely log out the second one or so

**Comment by panchenko** [comment]
This is fixed by #1334

**Comment by marcphilipp** [comment]
Fixed by 85d7d3327a10435291f948121e1a8402b131fbd4.

Thanks, @panchenko!
