### ISSUE TITLE
Allow for String Categories

### ISSUE THREAD

**Issue by Juan-Bustamante** [junit-team/junit4#1226]
Currently JUnit test categories can only be classes. In the maven configs you put the class name, and on the JUnit tests you put the actual class. 

This forces you to put the Category class on a jar that's accessible by all the maven modules that share the maven surefire plugin configuration. This seems like an unnecessary constraint. 

It's nice having the type-safe Category, but we not always have a jar common to all the modules that share the parent pom where the surefire config is specified.

**Comment by seh** [comment]
I just ran into this problem yesterday—having to add a dependency on the Maven module that defines this interface supplied to the `Category` annotation in *all* modules subjected to this Surefire plugin configuration, even if no classes in those modules happen to use this interface at the moment.

**Comment by Tibor17** [comment]
In Surefire we can employ customized JUnit Filter.
You know that RunListener can be configured in system properties
configuration.
I can imaging the same with Filter and Sorter.
This way you can implement Categories Filter by your own.

On Tue, Dec 8, 2015 at 4:21 PM, Steven E. Harris <notifications@github.com>
wrote:

> I just ran into this problem yesterday—having to add a dependency on the
> Maven module that defines this interface supplied to the Category
> annotation in *all* modules subjected to this Surefire plugin
> configuration, even if no classes in those modules happen to use this
> interface at the moment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/junit-team/junit/issues/1226#issuecomment-162912812>.
>



-- 
Cheers
Tibor

**Comment by Juan-Bustamante** [comment]
@Tibor17 - agreed, but we would like to be able to use this feature without having to craft our own solutions to make it work, and without having to put a common jar dependency on all our modules. 

Allowing for the "category" to be a String, and not restricting it to be Class, would achieve this goal.

**Comment by marcphilipp** [comment]
FYI our current JUnit 5 prototype does not have categories but tags that are strings. In addition, since we support meta-annotations, you can easily create your own annotation (e. g. `@Fast`) to tag your tests. 

For more informative please see: https://github.com/junit-team/junit-lambda/wiki/Prototype-Writing-Test-Cases

**Comment by Tibor17** [comment]
`@Fast` is what they don't want. They do not want to have String :
annotation = 1:1.
My solution above needs just only one annotation in the framework which
covers all strings, N:1.

On Wed, Dec 9, 2015 at 7:13 PM, Marc Philipp <notifications@github.com>
wrote:

> FYI our current JUnit 5 prototype does not have categories but tags that
> are strings. In addition, since we support meta-annotations, you can easily
> create your own annotation (e. g. @Fast) to tag your tests.
>
> For more informative please see:
> https://github.com/junit-team/junit-lambda/wiki/Prototype-Writing-Test-Cases
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/junit-team/junit/issues/1226#issuecomment-163345408>.
>



-- 
Cheers
Tibor

**Comment by Juan-Bustamante** [comment]
@marcphilipp  - will there be support for these @Tags from the surefire maven plugin? Using something simple like <includedTags> <excludedTags>?

If so, that would be exactly what we are asking for. 

@Tibor17 - What would we have to put on surefire to run only "groupXyz" tests if we mark them with this annotation?

`@Category({ @Named("groupXyz") })`

**Comment by Tibor17** [comment]
>>will there be support for these @Tags <https://github.com/Tags> from the
surefire maven plugin
ugf, to support junit 5 completely is difficult. We manage to introduce new
API in surefire that the user would implement it but the ambition is not
junit5. We want to satisfy all users with "current features" and this is
not possible because they have requirements which we do not want to have
new config parameters all the time. Therefore we came with an idea they
will implement SPI as they like to have.

>>What would we have to put on surefire to run only "groupXyz" tests if we
mark them with this annotation?
In surefire just use <group>groupXyz</group> and update class
GroupMatcherCategoryFilter.
The Surefire would need to adapt to JUnit first of all.
If a contributor wants to open PR, everything is possible then.


On Wed, Dec 9, 2015 at 10:20 PM, Juan-Bustamante <notifications@github.com>
wrote:

> @marcphilipp <https://github.com/marcphilipp> - will there be support for
> these @Tags <https://github.com/Tags> from the surefire maven plugin?
> Using something simple like ?
>
> If so, that would be exactly what we are asking for.
>
> @Tibor17 <https://github.com/Tibor17> - What would we have to put on
> surefire to run only "groupXyz" tests if we mark them with this annotation?
>
> @Category({ @Named("groupXyz") })
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/junit-team/junit/issues/1226#issuecomment-163394987>.
>



-- 
Cheers
Tibor

**Comment by marcphilipp** [comment]
@Tibor17 I've opened [an issue in the Maven Surefire JIRA](https://issues.apache.org/jira/browse/SUREFIRE-1206) regarding future support for JUnit 5 in Maven Surefire.

**Comment by Tibor17** [comment]
@marcphilipp See JIRA with my questions to junit5.

**Comment by Tibor17** [comment]
@Juan-Bustamante We agreed in ASF to wait for standard JUnit API.

**Comment by Tibor17** [comment]
@marcphilipp Please find the time to answer my questions in JIRA, Thx.

**Comment by marcphilipp** [comment]
@Tibor17 I've just responded. Let's please not use this GitHub issue but the JIRA ticket or junit-team/junit-lambda#31.

**Comment by kcooney** [comment]
I don't think we will be changing this in JUnit 4.x, so I vote to close it

**Comment by marcphilipp** [comment]
Agreed.
