### ISSUE TITLE
Jdk9 Early Access Build 99 issue

### ISSUE THREAD

**Issue by nhojpatrick** [junit-team/junit4#1233]
Installed Java 9 Early Access Build 99, trying to build JUnit and identified issue with maven-jar-plugin 2.6. Will raise with maven-jar-plugin and then submit pull request with updates so JUnit builds with Java 9.

**Comment by marcphilipp** [comment]
Please do, thanks for checking!

**Comment by nhojpatrick** [comment]
Fixes awaiting release;
https://issues.apache.org/jira/browse/MJAR-206
https://issues.apache.org/jira/browse/MJAVADOC-443

Pull request into maven-plugin;
https://github.com/apache/maven-plugins/pull/76

**Comment by nhojpatrick** [comment]
See pull request https://github.com/junit-team/junit/pull/1234

**Comment by stefanbirkner** [comment]
The plugins are now working fine with JDK 9. The only problem currently is that `StackTracesTest` is failing. I have a look at it. For more details see the [builds for my jdk9 branch](https://travis-ci.org/stefanbirkner/junit/branches).

**Comment by stefanbirkner** [comment]
JUnit can now be build with JDK 9. See 9b061ea8c96fa6cba0ac9d7cfd5e8ffbd030b34a.
