### ISSUE TITLE
MultipleFailureException should override printStackTrace()

### ISSUE THREAD

**Issue by drewhannay** [junit-team/junit4#1238]
Currently `MultipleFailureException` overrides the `getMessage()` method, but not this `printStackTrace()` method. This means that anyone calling `printStackTrace()` will only see the last exception in the `MultipleFailureException`, which is often the least useful.

Ideally `MultipleFailureException#printStackTrace()` should include the stack traces of all the wrapped exceptions.

**Comment by jlink** [comment]
Since JUnit 5 is based on the exception hierarchy in opentest4j you might also want to bring up your point there: https://github.com/ota4j-team/opentest4j
It's called `MultipleFailuresError` there.

**Comment by kcooney** [comment]
This was fixed via 35c8fd37
