### ISSUE TITLE
Timeout Test and Rule Annotation bug

### ISSUE THREAD

**Issue by rob0229** [junit-team/junit4#1250]
I created a simple test that has a 'for loop' where a public int getPrice() function is called 2.1 billion times as a test of the timeout. When I set the timeout for 10ms, it will correctly fail the test because the test takes 6200 milliseconds to run on my older machine. The problem is when I I increase the timeout to 100 ms. The test passes. I played with other values and I could recreate the issue each time. I also set the timeout as a @Rule and had the same behavior. I plan to look into the code this evening. What better way to spend a Friday night?

**Comment by kcooney** [comment]
The timeout values are approximate. Also, for slow machines and older JVMs, a thread that spends a long time doing work without making a blocking call or a sleep.call can result in other threads not getting scheduled (including the JUnit thread that is implementing the timeout).
