### ISSUE TITLE
Fix broken links on FAQ page

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit4#1257]
As a follow-up on #1248 the remaining broken links on the website's FAQ should be fixed or the corresponding FAQ entries should be removed.

![6qmhafrci6aaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/214207/13395110/d5c26554-deec-11e5-9d50-d61d8d2382ad.png)

**Comment by abinabrahamanchery** [comment]
![404 in junit](https://cloud.githubusercontent.com/assets/5570791/14009996/1a393f5a-f1b7-11e5-8e3a-8ae573c14a83.PNG)

when i tried to access http://junit.org/faq.html , Its returning 404 error ...!!  is it removed ???

**Comment by marcphilipp** [comment]
We're in the process of working on a new website for the upcoming JUnit 5. Thus, the URL changed to http://junit.org/junit4/faq.html. However, thanks to your issue report, I've now created redirects for all pages, including http://junit.org/faq.html.
