### ISSUE TITLE
Missing test case for junit.textui.TestRunner

### ISSUE THREAD

**Issue by avargas-nearsoft** [junit-team/junit4#1266]
@fcalderonnearsoft and me noticed that there is no test case for TestRunner. Should we create it or is it also unused?

**Comment by kcooney** [comment]
This class was part of JUnit 3, and isn't used in JUnit 4. The JUnit3 part of the code base is effectively in maintenance mode, so it is not worth anyone's time to write tests for this class.

**Comment by avargas-nearsoft** [comment]
Ok, thanks!
