### ISSUE TITLE
Used only first* from methods marked @Parameters

### ISSUE THREAD

**Issue by sirikid** [junit-team/junit4#1270]
I think it might be useful to have more than one method marked @ Parameters.
\* lexicographically first

**Comment by marcphilipp** [comment]
Can you please provide a compelling example? ;-)

**Comment by sirikid** [comment]
In the first method I create test data using a PRNG, and in the second I read from a file previously detected edge cases.

**Comment by kcooney** [comment]
@sirikid why do you need two methods annotated with `@Parameters` to do that? You could have one method that does both things (then it's 100% clear what JUnit would do).
