### ISSUE TITLE
Method copyArray of JUnitCommandLineParseResult class could replace using of ArrayList for primitive array

### ISSUE THREAD

**Issue by fcalderonnearsoft** [junit-team/junit4#1271]
In the copyArray metod we receive an array to copy of, from a starting point to an ending point. The values are added in a for loop to an arraylist. We think it could be more efficiente if we use a primitve array, as we know the size the new array should have and that way improve the performance.

**Comment by marcphilipp** [comment]
You're probably right about that. Since the array of command line arguments is probably not very long it won't make a big difference. If you want to give it a shot, please keep in mind that JUnit 4 can only use JDK methods present in JDK 5, e.g. no `Arrays.copyOfRange`.

**Comment by marcphilipp** [comment]
Resolved in #1272.
