### ISSUE TITLE
@RunWith not running with maven

### ISSUE THREAD

**Issue by pratikkumar19** [junit-team/junit4#1288]
Hi, I am using Junit for testing.
I have created a custom junit runner and have been using it with @RunWith annotation on a test class .
The problem is when using maven as a build manager for my java project, the test class annotated with @RunWith is completely getting ignored.
Going through maven documentation , I saw that there is no way to specify a custom junit runner.
How can I run the junit  test class with my custom junit runner in my maven build lifecycle?(My class is named *Test and is inside directory src/test/java)

**Comment by marcphilipp** [comment]
Normally, you don't have to configure anything to use a custom runner using Maven. Please open an issue in [Maven Surefire's issue tracker](https://issues.apache.org/jira/browse/SUREFIRE).
