### ISSUE TITLE
Tests annotated with `@Test(expected = AssumptionViolatedException.class)` will be marked as skipped instead of passing

### ISSUE THREAD

**Issue by alb-i986** [junit-team/junit4#1290]
When using `@Test(expected = AssumptionViolatedException.class)` the test will actually be marked as skipped instead of passing, as if the AssumptionViolatedException were thrown up in the stack.
In fact that's what seems to happen: https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/internal/runners/statements/ExpectException.java#L22

I've found this bug while doing #1289, while inspecting our skipped unit tests.
See e.g. https://github.com/junit-team/junit4/blob/master/src/test/java/org/junit/tests/experimental/AssumptionTest.java#L80

But maybe this is actually working as expected. I mean, no one should ever expect AssumptionViolatedException. It can happen only to us, in our unit tests. Wherever we need to, we have to use a try/catch block instead.

@stefanbirkner You seem to have worked on assumptions quite a lot, can you please advise?

**Comment by alb-i986** [comment]
I think I got it. See #1291

**Comment by adrianosimoes** [comment]
What's the status of this issue? Is it fixed?

**Comment by kcooney** [comment]
@adrianosimoes there is a fix in #1291 by @alb-i986 but there were some issues with the tests and the pull languished. Alberto, any chance you can make the requested changes?

**Comment by alb-i986** [comment]
Sure, I'll try to finish it asap.

**Comment by alb-i986** [comment]
@kcooney I hope I haven't missed anything. Please check it out.
Thanks
--alb
