### ISSUE TITLE
Javadoc for RuleChain contains errors

### ISSUE THREAD

**Issue by rillig-nm** [junit-team/junit4#1295]
* The class modifier `static` is not necessary.
* The method calls are missing closing parentheses.

In addition, the documentation should make clear that the `RuleChain` cannot be used to define the order of existing rules, e.g. the following does not work as expected:

```
@Rule
public LoggingRule middle = new LoggingRule("middle rule");
@Rule
public RuleChain chain = RuleChain
    .outerRule(new LoggingRule("outer rule"))
    .around(middle)
    .around(new LoggingRule("inner rule"));
```

In this code, `middle` is executed twice.

**Comment by marcphilipp** [comment]
You're right -- thanks for reporting this issue!

Do you have time to submit a fix?

**Comment by rillig-nm** [comment]
No, I don’t. Setting up the necessary IDE that exactly follows your coding conventions doesn’t seem time-efficient to me.

**Comment by marcphilipp** [comment]
If you use Eclipse you just have to clone the repo and open the project in Eclipse.

**Comment by Harrisnick** [comment]
I have come across this issue and thought it would be a great way to start contributing to JUnit. I'd like to modify the Javadoc as suggested by rillig-nm and also add something to clarify how RuleChaining works with existing rules.

I will submit a fix now.
