### ISSUE TITLE
JUnit should guarantee execution order of @Rules in test class hierarchies

### ISSUE THREAD

**Issue by rillig-nm** [junit-team/junit4#1296]
In the following code, there is currently no guarantee that the rules are executed in a specific order:

```java
public class SuperTest {
  @Rule
  public final LoggingRule superRule = new LoggingRule("super");
}

public class SubTest extends SuperTest {
  @Rule
  public final LoggingRule subRule = new LoggingRule("sub");

  @Test
  public void test() {
  }
}
```

It should be defined that rules from a super class are wrapped around rules from a subclass, analogous to how `@Before` and `@After` already work.

The order of rules within a single class should be left unspecified, since that can be worked around using the `RuleChain`.

**Comment by marcphilipp** [comment]
@junit-team/junit-committers Do you think we should guarantee such an order?

**Comment by kcooney** [comment]
I thought we already defined an order. The code is here:

https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/runners/model/TestClass.java#L90

Is that not called  for rules?

**Comment by rillig-nm** [comment]
I’m sorry, this already works exactly as expected. Some time ago I was sure that it didn’t, but right now I cannot reproduce this.
