### ISSUE TITLE
RunListener implementation questions

### ISSUE THREAD

**Issue by Macarse** [junit-team/junit4#1316]
I am creating a custom `RunListener` to update a test run on TestRail with the results from an android automation run. I have two questions:

1) How important is to be able to declare the `RunListener` as thread safe?

I see if it's not marked with `@RunListener.ThreadSafe` the listener will be wrapped in the `SynchronizedRunListener`. AFAIK, `AndroidJUnitRunner` will run one test at the time, so I think it doesn't matter.

2) Which is the best way to know if a test passed?
The `RunListener` API doesn't have a `testPassed()` (why?) so what I did is the following:
 - Create a set of `Description`s on `testRunStarted()`
 - If `testFailure()` or `testAssumptionFailure()` are called, add the `Description` instance to the set
 - When `testFinished()` is called, if the `Description` instance is not in the set, I mark the test as passed

Thanks for your time!

**Comment by kcooney** [comment]
If you are not sure if your listener implementation is thread-safe then I would not recommend annotating it as thread-safe. The cost of acquiring a noncontested lock.is low so if there is only one thread then there will be no noticeable impact on the running time by leaving the listener unannotated.

**Comment by kcooney** [comment]
As for.knowimg if a test has passed, `testStarted()` is called right before the test started and `testFinished()` is called right after it ends.

Note: for general "how do I use JUnit's <something> API" questions, I recommend StackOverflow.com

**Comment by Macarse** [comment]
@kcooney but I can't know if the test passed or not just using the `Description`, right? Or I am missing something very obvious?

**Comment by marcphilipp** [comment]
You know that a test passed when `testFinished()` is called without a prior call to `testFailure()` with the same `Description`.

**Comment by sebastianvintila** [comment]
@Macarse regarding the issue of missing testSuccess method here is the solution i have implemented

private static final Description FAILED = Description.createTestDescription("failed", "failed");

public void testFinished(Description description) throws Exception {
        System.out.println("Finished test: " + description.getMethodName());
        if (description.getChildren().contains(FAILED)) {
            // action for test failed
        } else {
            // action for test success 
        }
    }

    public void testFailure(Failure failure) throws Exception {
        System.out.println("Failed test: " + failure.getDescription().getMethodName());

// mark the test as being failed 
        failure.getDescription().addChild(FAILED);
    }
