### ISSUE TITLE
Request.filterWith(final Description desiredDescription)

### ISSUE THREAD

**Issue by Reissner** [junit-team/junit4#1318]
Documentation is syntactically wrong. 
 "Returns a Request that only runs contains tests whose Description equals desiredDescription. "

What it does is returns a request which is empty if desiredDescription is not a single test 
and which filters all but the single test if desiredDescription is a single test. 

What is most probably wanted is 
a filter which runs those tests in this Request which are also contained in desiredDescription.

**Comment by kcooney** [comment]
@Reissner would you be willing to send us a pull request that improves the Javadoc?

**Comment by stefanbirkner** [comment]
Fixed by a73dc0d5ab3bf12db50c5a4c62a933f2d08d4936.
