### ISSUE TITLE
ParentRunner<T>: T is Runner for Suite

### ISSUE THREAD

**Issue by Reissner** [junit-team/junit4#1321]
documentation of ParentRunner says: 
(For {@link BlockJUnit4ClassRunner}, {@code T} is
 * {@link Method} . For {@link Suite}, {@code T} is {@link Class}.)

The latter is wrong: should be {@link Runner}.

**Comment by kcooney** [comment]
@Reissner Good catch! Would you be willing to send us a pull fixing the docs?

**Comment by Reissner** [comment]
done.
