### ISSUE TITLE
Result shall take failed assumptions also into account

### ISSUE THREAD

**Issue by Reissner** [junit-team/junit4#1325]
In some version assumptions came into the game 
but tests with failed assumtions do not go into Results: in fact they cannot be distinghished from passed tests which i think is inadequate. 
Suggestion: add a category besides ignored: invalidated holding tests with failed assumptions. 
The number of those is the number of invocations of testAssumtionFailure..

**Comment by marcphilipp** [comment]
There's already a pull request for that: #1294.
