### ISSUE TITLE
why dropped junit.framework.AssertionFailedError?

### ISSUE THREAD

**Issue by Reissner** [junit-team/junit4#1326]
This is more a question but an issue. 
In very old junit, AssertionFailedError extends AssertionError was available. 
But now Assert throws just AssertionError. 
With assertions enabled, failed assertions cannot be distinguished from failed tests. 
Isnt this a bug??

**Comment by kcooney** [comment]
Believe it or not, JUnit actually predated the `assert` keyword being added to Java.

I wasn't involved in the initial creation of JUnit 4.0 but I suspect they decided that creating a new exception wasn't necessary.

In the end, distinguishing the two doesn't matter. When tests throw exceptions they fail. The message should make it easy to see why the failure happened.

**Comment by Reissner** [comment]
Well, I remember the times where one distinguished, 
whether a test could not be executed and was thus invalid and did neither pass nor fail 
or whether it could be executed but discovered a failure. 

With AssertionFailedError being thrown by class Assert, 
one cannot distinguish clearly.

**Comment by kcooney** [comment]
With JUnit4-style tests, if a test can determine that it cannot be executed, then it can use `Assume` so it isn't reported as a pass or a fail.

If JUnit cannot run the test for some reason, that shows up as a failure.

To the best of my knowledge, JUnit3-style tests never threw a `AssertionFailure` that wasn't an instance of `AssertionFailureError`, so if you saw those, your tests or code was throwing them.

**Comment by Reissner** [comment]
Well, AssertionFailedError extended AssertionError, so the fathers of JUnit surely had a notion of assertion. By the way, in the very first draft of the jls assert was forseen, but later dropped. 

You write: If JUnit cannot run the test for some reason, that shows up as a failure.
Hm, if a tests fails to execute (originally called 'test in error'), this does not show a failure in the software tested, right? 
It just shows that not all tests forseen for assuring a predefined quality level could be evaluated. 
If in contrast a test executes but returns with a failure (originally called 'test in failure'), 
a bug in the application is found. 


Thus it is vital to distinguish test in failure and test in error. 

you write: 
'To the best of my knowledge, JUnit3-style tests never threw a AssertionFailure that wasn't an instance of AssertionFailureError, so if you saw those, your tests or code was throwing them.' 
Right. it threw AssertionFailureError which is a subclass of AssertionError (there is no AssertionFailure)

you write: 
'With JUnit4-style tests, if a test can determine that it cannot be executed, then it can use Assume so it isn't reported as a pass or a fail.' 
Hm, it is not feasable to catch all kinds of exceptions that could be thrown by a test irregularly, 
i.e. outside Assert in terms of an assumption. 
Thus it is important to provide a mechanism to fail via some throwable 
which can be distinguished from the one thrown by Assert. 
This was originally done by throwing AssertionFailedError by Assert 
and nowhere else. 
AssertionFailedError indicated test in failure. 
All other Throwables indicated tests in error.

**Comment by kcooney** [comment]
> Thus it is vital to distinguish test in failure and test in error.

Again, I wasn't there for the original design of JUnit4. From what I understand, David and Kent decided  that the distinction between failure and error wasn't necessary (and possibly confusing) when they designed JUnit4 ten years ago.

This has been the far too late to change this behavior now in the JUnit4 code base. Perhaps you can file a feature request at https://github.com/junit-team/junit5

**Comment by kcooney** [comment]
Also remember that there are many third-party assertion frameworks and thise frameworks may not want to depend on JUnit classes. These libraries tend to throw `AssertionError`
