### ISSUE TITLE
For Spock and parameterized tests, Description.getMethodName() returns values that are not method names

### ISSUE THREAD

**Issue by juherr** [junit-team/junit4#1328]
The javadoc is saying:

``` java
    /**
     * @return If this describes a method invocation,
     *         the name of the method (or null if not)
     */
```

As I understand it, 

``` java
Description desc = ...
desc.getTestClass().getMethod(desc.getMethodName());
```

should work if `desc.getMethodName() != null`.

Maybe parameterized tests (#892) are a specific use cases but what about the other test cases?

For example, with the following simple Spock specification:

``` groovy
class SpockSample extends Specification {

    def "adding an element leads to size increase"() {
        setup: "a new stack instance is created"
        def stack = new Stack()

        when:
        stack.push 42

        then:
        stack.size() == 1
    }
}
```

`desc.getMethodName()` will return `"a new stack instance is created"`. 
Is it the expected value?

Source ref: https://github.com/spockframework/spock/blob/master/spock-core/src/main/java/org/spockframework/runtime/JUnitDescriptionGenerator.java#L75-L76

**Comment by marcphilipp** [comment]
Unfortunately, `Description` was not designed with use cases outside of JUnit in mind. Therefore, methods like `getMethodName()` have to be used carefully. In this case, Spock is passing "a new stack instance is created" to the `Description` factory method as a method name.

The JUnit platform that JUnit 5 will be built upon has an abstraction that is designed to be support use cases outside of Java classes/methods: [`TestSource`](https://junit.ci.cloudbees.com/job/JUnit5/1162/javadoc/org/junit/gen5/engine/TestSource.html).

**Comment by juherr** [comment]
> Spock is passing "a new stack instance is created" to the `Description` factory method as a method name.

In fact, they are more passing it as a method `displayName` which seems correct for me.

What surprises me is not having `null` when the method doesn't exist.

BTW, I found a workaround and it is not a problem anymore: https://github.com/cbeust/testng/pull/1063

**Comment by kcooney** [comment]
If are passing it as the display name, we *might* be able to.fix this

**Comment by juherr** [comment]
@kcooney It is always `displayName` computed from the class name and the "name" (not clear for me what name is supposed to be).
And for the moment `getMethodName()` is computed from the `toString()` aka `displayName` and returns, in fact,  `name`.

I see many "problems":
- It is not possible to override anything from `Description`
- It is not possible to configure its `displayName` logic (+/- same than previous)
- No `String getName()` method (which returns the passed name)
- No `Method getMethod()` (which returns the method if exists or null)
- No clear definition on what `getMethodName()` is supposed to be

Fixes could be:
- Let the possibility to implement `MyDescription`
- Having `getName()` which returns `name` and `getMethodName()` which returns the method name or null if it doesn't exist (breaks backward compability)
- Having `getName()` which returns `name`, `getMethodName()` like before to keep backward compability and `Method getMethod()`

What do you think?

**Comment by kcooney** [comment]
@juherr at one point we were considering solving these problems with a builder that built immutable `Description` objects. It was challenging to do this without breaking existing users. Getting filters to work was also challenging.

The work was tabled when the JUnit Lambda effort started.

**Comment by kcooney** [comment]
One thing to consider: it might be simpler and better to reimplement the JUnit Spock integration on top of JUnit Lambda.

**Comment by juherr** [comment]
@kcooney I'm not sure to understand you: what is the expected behavior for `getMethodName`? 
As I mentioned before, I think some fixes are possible and backward compatible. I can propose a PR but I need to understand what I should do before ;) 

> it might be simpler and better to reimplement the JUnit Spock integration on top of JUnit Lambda.

I'm sure it is, but not really my business :)

**Comment by kcooney** [comment]
@juherr if the need for these changes are for Spock then I think we should close this bug. JUnit Lambda has a more flexible description mechanism that solves these issues.

**Comment by juherr** [comment]
Yep, not a problem for me.

The root problem was the support of Spock into TestNG where I was surprised about their usage of `getMethodName` and I wanted to know if they are rigth and/or they can improve it.
But as I said, I found a workaround ;)
