### ISSUE TITLE
assumeTrue doesn't work in @Parameters methods

### ISSUE THREAD

**Issue by garfieldnate** [junit-team/junit4#1329]
My test class loads some expensive resources in the parameters function, so I want to skip that step if the entire class of tests is going to be skipped anyway. However, when I use `assumeTrue` in the parameters function the tests fail with the following:

```
org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
    at org.junit.Assume.assumeThat(Assume.java:95)
    at org.junit.Assume.assumeTrue(Assume.java:41)
    at ExampleTest.getParams(ExampleTest.java:17)
```

I am running JUnit 4.12 within Eclipse. MWE below:

```
import static org.junit.Assume.assumeTrue;

import java.util.Collection;
import java.util.Collections;

import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

@RunWith(Parameterized.class)
public class ExampleTest {

    @Parameters(name = "{index}: {1}")
    public static Collection<Object[]> getParams() {
//      assumeTrue(false);//bad
        return Collections.emptyList();
    }

    public ExampleTest(){
        assumeTrue(false);//okay
    }
}
```

**Comment by PeterWippermann** [comment]
What do you mean by:
>  if the entire class of tests is going to be skipped anyway

Why should all tests be skipped?

**Comment by garfieldnate** [comment]
My code base is being retrofitted to work with multiple locales, and many of the tests apply to one locale or another. In some cases it is specific tests within a file, in other cases it is the entire file of tests that should not be run for the locale. By "all tests should be skipped," I mean the entire file, not the entire test suite, which does not sound useful to me. 

Of course, it would also be possible for me to create an entire custom test suite depending on the variables. However, the simplest test suite to run is the suite of all of them, and in this case it is much simpler for me to specify within a file, "skip this file if we're testing a different locale."

**Comment by PeterWippermann** [comment]
Ok, got it :-)

From the documentation of [assumptions](https://github.com/junit-team/junit4/wiki/assumptions-with-assume):

> A failing assumption in a @Before or @BeforeClass method will have the same effect as a failing assumption in each @Test method of the class.

So I propose you put your assumption in `@BeforeClass` as it seems to be a good practice.
However, to avoid the expensive processing of resources in your `@Parameters` method, why don't you convert your assumption there to a simple check with an `if`-statement?

`

    @Parameters
    public static Iterable<Object> parameters() {
        if(isAssumptionFulfilled()) {
            return listFromExpensiveResourceProcessing();
        } else {
            return Collections.emptyList(); // or maybe a List with at least one element?
        }
        
    }
    
    @BeforeClass
    public static void before() {
        assumeTrue(isAssumptionFulfilled());
    }
    
`

**Comment by kcooney** [comment]
If you filter out all of the test methods (for example, via `Categories`) then I believe JUnit won't call the `@Parameters` method

**Comment by garfieldnate** [comment]
I've refactored my code so that this just isn't a problem any more (moving expensive operations to other places, etc.). However, I still think handling the assumption in the parameters method would be the most convenient from a user's standpoint. I've never had to consider the running order of `beforeClass` and `parameters`, and but it seems that many people have issues with this (from a quick Googling, and #527). Not allowing the `assume` method in the parameters method is kind of a "gotcha" since that method is run very first.

**Comment by garfieldnate** [comment]
I've only just run into this, but it seems that the same problem exists for `@AfterClass` methods. I ran into this problem when timing tests using apache.commons.lang3.StopWatch:

    private static StopWatch stopWatch = new StopWatch();
    @BeforeClass
    public static void setup() {
        assumeTrue(somethingFalse);
        stopWatch.start();
    }
    @Test
    public static void someLongTest(){...}
    @AfterClass
    public static void reportTime(){
        stopWatch.stop();
        System.out.println("Time was " + stopWatch.toString());
    }

Unexpectedly, calling `assumeTrue` in the `@BeforeClass` method did not skip the `@AfterClass` method. Because of this I attempted to stop the stopwatch even though it was never started, which throws an exception. I figured the obvious solution would be to put the same `assumeTrue` statement in the `@AfterClass` method, but that resulted in an uncaught `AssumptionViolatedException`. So now I have to write the assumption twice, once using `assumeTrue` and once using an if statement.

**Comment by kcooney** [comment]
@garfieldnate in general if any `@Before` methods are called then all the  `@After` methods are called, even if the `@Before` methods threw exceptiona. The thinking is that the `@Before` method could have done something before the exception was thrown that requires a tear down.

`@BeforeClass` and `@AfterClass` are similar. Having the behavior be different for assumption failures would be confusing.

**Comment by garfieldnate** [comment]
I understand how that could lead to some bad accidents. jUnit has no way of telling whether a method did setup before throwing an assumption exception. However, I think AssumptionViolationException should be dealt with in the after methods.

**Comment by Tibor17** [comment]
AFAIK the user wants to alter the phase when injection of @Parameters
is done and call the Assumption right before @Before and skip
before-test-after if the assumption in parameters fails.
My hint is to introduce new descriptive method in the annotation @Parameters.
```
public static @interface Parameters {
   String name() default "{index}";
   boolean aroundTest() default true;
}
```

In code this might be
```
@Parameters(aroundTest = false)
public static Iterable<Object> parameters() {
    assumeTrue(isAssumptionFulfilled());
    ...
}
```

And the lifecycle would be:
+ parameters
+ before
+ test
+ after

On 8/26/16, Nathan Glenn <notifications@github.com> wrote:
> I understand how that could lead to some bad accidents. jUnit has no way of
> telling whether a method did setup before throwing an assumption exception.
> However, I think AssumptionViolationException should be dealt with in the
> after methods.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/junit-team/junit4/issues/1329#issuecomment-242656045


-- 
Cheers
Tibor

**Comment by kcooney** [comment]
Looking back at the original motivation (avoiding an expensive operation that produces the parameters) it sounds like something JUnit 5 already supports. @marcphilipp can you comment?

As for JUnit 4 the simple workaround would be to just return an array of size one containing all nulls, and have a `@Before` method use `Assume` to skip the tests in this case.

**Comment by Tibor17** [comment]
@kcooney The problem is that the organizations won't change the framework and entire testset due to this feature. If it's a simple change then why not to make it in JUnit 4.

**Comment by kcooney** [comment]
@Tibor17 I am not sure we can make a simple change that wouldn't break people. We would likely break people if we changed the way assumption failures were handled in `@Before` and/or `@BeforeClass` methods. Do you have a specific proposal?

**Comment by Tibor17** [comment]
if `aroundTest =true` nothing changed. If false then it is up to JUnit when parameters methods are called. It's clear that JUnit would not call the methods before @Test. Obviously before calling @Before or Rules.

**Comment by kcooney** [comment]
@Tibor17 I'm guessing when you said `@Before` you meant `@BeforeClass`. In any case, making the method order conditional on an annotation parameter wouldn't be very discoverable.

Again, if someone can find a clean way to handle assumption failures in `@Parameters` methods please send a pull.

**Comment by Tibor17** [comment]
>>I'm guessing when you said @Before you meant @BeforeClass.
No, i mean this order:
BeforeClass
Parameters
Before
Test
After
AfterClass

AFAIK currently the order is (which would mean aroundTest = true by default):
BeforeClass
Before
Parameters
Test
After
AfterClass

>>please send a pull.
exactly! This might not be visible solution in case of multiple @Parameters.

On 8/28/16, Kevin Cooney <notifications@github.com> wrote:
> @Tibor17 I'm guessing when you said `@Before` you meant `@BeforeClass`. In
> any case, making the method order conditional on an annotation parameter
> wouldn't be very discoverable.
>
> Again, if someone can find a clean way to handle assumption failures in
> `@Parameters` methods please send a pull.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/junit-team/junit4/issues/1329#issuecomment-242995519


-- 
Cheers
Tibor

**Comment by kcooney** [comment]
@Tibor17 `@Before` methods are instance methods so they cannot be called until after the test class has been constructed. Constructing the test class requires that JUnit know the parameters.

**Comment by Tibor17** [comment]
@kcooney So what is the order of the method by in Parameterized?
If params are called before `@Before` then no issue. The only thing is to skip the before-test-after if @Parameters fail with the assumption.

**Comment by kcooney** [comment]
@Tibor17 The `@Parameters` method is called before any `@BeforeClass` methods and before any class Rules. It is called while the Runner tree is being built (from the `Parameters` constructor) so it may be tricky to handle assumption failures there.

**Comment by Tibor17** [comment]
Then it does not have the solution I wanted. Nice way would be to have
`assumeTrue` in the constructor of `FibonacciTest(int input, int
expected)`, see this example and imaging the constructor with
assumption
https://github.com/junit-team/junit4/wiki/parameterized-tests

On 8/29/16, Kevin Cooney <notifications@github.com> wrote:
> @Tibor17 The `@Parameters` method is called before any `@BeforeClass`
> methods and before any class Rules. It is called while the Runner tree is
> being built (from the `Parameters` constructor) so it may be tricky to
> handle assumption failures there.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/junit-team/junit4/issues/1329#issuecomment-243144166


-- 
Cheers
Tibor

**Comment by marcphilipp** [comment]
> Looking back at the original motivation (avoiding an expensive operation that produces the parameters) it sounds like something JUnit 5 already supports. @marcphilipp can you comment?

JUnit Jupiter indeed provides an extension point to skip an entire test class: [`ContainerExecutionCondition`](http://junit.org/junit5/docs/current/user-guide/#extensions-conditions).
