### ISSUE TITLE
testSuiteStarted and testSuiteFinished executed twice

### ISSUE THREAD

**Issue by helaili** [junit-team/junit4#1332]
@baev, I've created a simple implementation of RunListener using `4.13-SNAPSHOT` and noticed my implementations for `testSuiteStarted` and `testSuiteFinished` are actually called twice. Looking at the stack traces, it seems to originate in ParentRunner : 

```
@Override
    public void run(final RunNotifier notifier) {
        EachTestNotifier testNotifier = new EachTestNotifier(notifier,
                getDescription());
        testNotifier.fireTestSuiteStarted();
        try {
            Statement statement = classBlock(notifier);
            statement.evaluate();
        } catch (AssumptionViolatedException e) {
            testNotifier.addFailedAssumption(e);
        } catch (StoppedByUserException e) {
            throw e;
        } catch (Throwable e) {
            testNotifier.addFailure(e);
        } finally {
            testNotifier.fireTestSuiteFinished();
        }
    }
```

Both `testNotifier.fireTestSuiteStarted()` and `statement.evaluate()` are triggering the call to `junit.runner.notification.RunNotifier.fireTestSuiteStarted`.

**Comment by helaili** [comment]
Looking deeper, it seems `fireTestSuiteXXX` is called both for test suite classes and test case classes. Therefore : 
- if I have N test classes in a test suite, I will receive N+1 calls to `testSuiteStarted` while I am expecting one only,
- you receive a `testSuiteStarted` call even when you're not using test suites.

**Comment by helaili** [comment]
According to [`Description.isTest()` and `Description.isSuite()`](https://github.com/junit-team/junit4/blob/dc43a04fcac86f1d412b428cce1ad9737d2287d3/src/main/java/org/junit/runner/Description.java#L203), whatever is not a test case is a test suite, hence a test class is a test suite. 

Is it working as expected?

**Comment by marcphilipp** [comment]
Yes, that's the JUnit 4 definition of a suite. Thus, the events fired are correct, too.
