### ISSUE TITLE
ExternalResource: the behavior is different than using multiple After methods

### ISSUE THREAD

**Issue by alb-i986** [junit-team/junit4#1334]
Multiple issues here:
1. When the test fails _and_ closing the resource fails, the test failure is lost: only the exception coming from the after() method is propagated.
2. In case there are multiple (ExternalResource) rules in place, and (closing) one fails, then all of the subsequent resources will _not_ be closed (without even trying to!).

This was not the case when encapsulating the tear down logic in multiple `@After` methods: RunAfters runs all of the After methods regardless of the result of each, and throws a MultipleFailureException in case more than one thing (test method and/or after logic) goes wrong.

I'm working on a fix for 1 for now, which is an easy one.

**Comment by alb-i986** [comment]
Sorry, I should have opened one issue for each point.
I used "fixes 1334" in my commit, so this will be closed as soon as the PR for point 1 is merged.

**Comment by marcphilipp** [comment]
Can you please open a separate issue for point 2?

**Comment by kcooney** [comment]
As an asside, the test fixture prototype I sent out last week has neither of these problems :-)

**Comment by marcphilipp** [comment]
I think #1335 and therefore 85d7d33 only addressed @alb-i986's first point. So I'm reopening this issue.

@alb-i986 Please provide an example for the second issue.

**Comment by panchenko** [comment]
That change fixes this fully and this issue can be resolved, as demonstrated in my PR, which just flattens MultipleFailureException in this case.

**Comment by panchenko** [comment]
@kcooney This issue can be closed.
