### ISSUE TITLE
Issues with AssumptionViolatedException constructor parameter name

### ISSUE THREAD

**Issue by mjustin** [junit-team/junit4#1337]
There are some inconsistencies with the constructor parameter names in the Javadocs for [AssumptionViolatedException](http://junit.org/junit4/javadoc/4.12/org/junit/AssumptionViolatedException.html), as well as mismatches between the documented behavior and the parameter names:

```
 AssumptionViolatedException(String message)
          An assumption exception with the given message only.
AssumptionViolatedException(String assumption, Throwable t)
          An assumption exception with the given message and a cause.
AssumptionViolatedException(String message, T expected, Matcher<T> matcher)
          An assumption exception with a message with the given actual value and a matcher describing the expectation that failed.
AssumptionViolatedException(T actual, Matcher<T> matcher)
          An assumption exception with the given actual value and a matcher describing the expectation that failed.
```

The (String, T, Matcher) constructor is inconsistent with its own description, as well as with the (T, Matcher) constructor ("expected" vs. "actual").

The (String, Throwable) constructor is inconsistent with the (String) and (String, T, Matcher) constructor ("assumption" vs. "message").

**Comment by marcphilipp** [comment]
You're right! Do you have time to submit a pull request?
