### ISSUE TITLE
Is there a way to pass a variable into JUnitCore when testing a Class in a Jar?

### ISSUE THREAD

**Issue by aaronmagi** [junit-team/junit4#1339]
I wanted to know if there is a way to pass in a `variable` to a `Class` when running it from `JUnitCore`?

I am currently testing `Classes` within a `Jar` and would like to pass in a variable to a @`Test`.  

Is there any way to do this?  I saw @Parameters but I believe this only works with a static set.  I want to pass a port number into the test.

**Code**

```
        File pathToJar = new File(jarPath);

        JarFile jarFile;
        jarFile = new JarFile(pathToJar);
        Enumeration<JarEntry> e = jarFile.entries();

        URL[] classLoaderUrls = new URL[]{pathToJar.toURI().toURL()};

        URLClassLoader cl = new URLClassLoader(classLoaderUrls, getClass().getClassLoader());
        while (e.hasMoreElements()) {
            JarEntry je = e.nextElement();
            if(je.isDirectory() || !je.getName().endsWith(".class")){
                continue;
            }
            // -6 because of .class
            String className = je.getName().substring(0,je.getName().length()-6);
            className = className.replace('/', '.');
            Class c = cl.loadClass(className);


            JUnitCore junit = new JUnitCore();
            Result result = junit.runClasses(c);  // I would like to pass the port # to the test if possible

  ......
```

**Comment by marcphilipp** [comment]
There's no built-in way to do this. How about setting a system property and reading that in your test?

**Comment by aaronmagi** [comment]
@marcphilipp   The problem is that we are trying to run junit tests in parrallel and inside the test execute a test based on a URL.  That URL needs to have a different port for each test.  This will not work with System Properties because there is no mapping for different ports to each test unless we can somehow pass in a way to read a different property 

Port1, Port2....

Do you know any other way to try to do this?

**Comment by marcphilipp** [comment]
How do you run them in parallel? Would a parameterized test help?
