### ISSUE TITLE
Execution of custom code when @BeforeClass fails?

### ISSUE THREAD

**Issue by morsmodre** [junit-team/junit4#1341]
I'm not sure if this is the right place to place this question, but this is specific and nitpicking enough for me to try.

I'm using junit to run some integrations tests with docker. I have a custom TestRule to copy the logs from the containers when a certain test fails:

```
public static class CopyLogsOnTestFailure implements TestRule {
    @Override
    public Statement apply(Statement base, Description description) {
        return statement(base, description);
    }

    private Statement statement(final Statement base, Description description) {
        return new Statement() {

            final String pathToFolder = "/tmp/logs";

            @Override
            public void evaluate() throws Throwable {
                try {
                    base.evaluate();
                } catch (Throwable caughtThrowable) {
                    logger.error("Copyings logs on failure!");
                    copyLogs(pathToFolder);
                    throw caughtThrowable;
                }
            }
        };
    }
```

Now, if the tests fails in @BeforeClass the logs are not copied since the TestRule is no good for @BeforeClass or @AfterClass methods (not sure if I understand the subtitles of this, but it doesn't work).

I tried to make the a similar @ClassRule to test solve it but when the test fails in @BeforeClass, the @AfterClass executes, before running the custom rule code. Obviously, in my case, @AfterClass deletes the containers...

Any idea how to solve this problem?

**Comment by marcphilipp** [comment]
Can you move the container creation/deletion to another `TestRule` and use `RuleChain` to define the order like in the following pseudo-code example?

```java
RuleChain. outerRule(new ProvideDockerContainer()).around(new CopyLogsOnTestFailure())
```
