### ISSUE TITLE
@RunWith(Enclosed.class) and its @BeforeClass

### ISSUE THREAD

**Issue by childnode** [junit-team/junit4#1354]
:information_source:  preliminary note: this issue might not be an Junit issue at all but a question about how it is designed and probably an error in gradle / IntelliJ

:information_desk_person:  we actually ran into some problems with Enclosed tests, a BeforeClass method in the enclosing class:

```
package test;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.experimental.runners.Enclosed;
import org.junit.runner.RunWith;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;

@RunWith(Enclosed.class)
public class TestSomething {
  private static Object someSetupNeeded;

  @BeforeClass
  public static void runBeforeEnclosedSuite() {
    someSetupNeeded = new SomeObject();
  }

  @Category(testcategory.Fast.class) // yes, not slow
  public static class InnerTestClass {
    @Before
    public void setUp() {
      boltStreams.toString(); // NPE on gradle console but not in intelliJ nor when running enclosed test class soley
    }

    @Test
    public void testSomeObject() {
      assertThat(someSetupNeeded, notNullValue());
    }
  } 
}
```

<strike>
with

```
package testcategory;
public interface Fast {
}
```

</strike>
<strike>

```
package testcategory;
public interface Slow {
}
```

</strike>
<strike>
with build.gradle settings

```
test {
    useJUnit {
            excludeCategories 'testcategory.Slow'
    }
}
```

</strike>

when running `./gradlew clean test` some of us gets NPE in the inner before class while others don't.
it is ok if you run the test with `./gradlew clean test --test test.TestSomething`
None of us have any problems running the outer TestSomething class in IntelliJ.

Just to complete: All of us have the same problem, that a single inner test class (TestSomething.InnerTestClass) run in IntelliJ will fail -> for me, an Intelli problem not running a correct suite or building it's own but not using JUnit test filter. So the result is the same as for those who get the error on console `gradlew test` : beforeClass of the encapsulating class is not executed when running an inner test class

:question: no1: what is the designed behaviour of this <strike>combination</strike> of Enclosed test suits <strike>and Category('s /  filters)</strike>? 
:question: no2: why is this not reproducable for all environment using the same build tool version and junit?

used:
- gradle 2.13 (but also tested with gradle 2.14.1) (both, using same wrapper checked in in project)
- IntelliJ CE 2016 (both)
- developer1: Sun Java 8u91 (error as described above) :question:  
- developer2: Sun Java 8u102 (no error on console)  :question: :exclamation:  :question:

P.S: topic someway related: #656 

P.S: this is not a category related issue, it is reproducable this the same code above without categories

**Comment by kcooney** [comment]
If you tell JUnit to run `InnerTestClass` in isolation then `runBeforeEnclosedSuite()` will not be run. This is because when you tell JUnit to run a class, it uses the runner for the class, and in this case `InnerTestClass` isn't annotated with `@RunWith` so runner for is  `BlockJUnit4ClassRunner`.

Is for the other behavior, it would be easier if you could run the test without Gradle our InjtelliJ. You can use the `JUnitCore` (http://junit.org/junit4/javadoc/latest/org/junit/runner/JUnitCore.html). In JUnit 4.12 we added support for filter tests on the command line (see https://github.com/junit-team/junit4/blob/master/doc/ReleaseNotes4.12.md#pull-request-647-support-command-line---filter-param).

Another option would be to run the test in Grade and attach a debugger to see what's going on. I don't know Gradle enough to know how to do this.

**Comment by childnode** [comment]
hi @kcooney 

thx for clarifying these questions.
what is still open to me: what is the designed behaviour? for me: @BeforeClass should work even on Enclosed Suit classes?!

**Comment by kcooney** [comment]
@childnode `@BeforeClass` (and `@ClassRule`) should work with `@RunWith(Enclosed.class)` if you run the outer class.

**Comment by childnode** [comment]
ok, thx for your answers @kcooney - to resume:
1. any execution of sub-/InnerTestClass doesn't trigger any before/after on the enclosed suite - by design.
2. running enclosed suite, will indeed include it, except
2.1. any tool, like gradle, doesn't build a correct suite but adds / executes the inner classes directly

still mysterious: why does it work for some but not for others if gradle version (and even binary - since wrapper is committed in project and no local changes are made, all of us are working on linux) is exactly the same but the only difference is the java patchlevel version?!

**Comment by kcooney** [comment]
@childnode I have no idea what Gradle does when you run your tests. If it runs `TestSomething` the the `@BeforeClass` method should be called.

I also don't know why the Java version matters.

You could a debugger to see what is going on by following the instructions at http://stackoverflow.com/a/25619391/95725

I suggest setting breakpoints in your test and in the methods in `Request`.

**Comment by stefanbirkner** [comment]
This is a Gradle issue. I had a look at the Enclosed runners code and tested with IntelliJ, Gradle and Maven. Only Gradle has the problem. I think its a problem of Gradle's test discovery. Please use [Gradle's issue 2319](https://github.com/gradle/gradle/issues/2319) for further information about this problem.

**Comment by kcooney** [comment]
This is a Gradle issue.
