### ISSUE TITLE
Using TestWatcher at Suite level ?

### ISSUE THREAD

**Issue by pranavparikh** [junit-team/junit4#1358]
I wrote a TestWatcher for my tests which sends the results to our reporting system. 
Instead of extending my custom testwatcher in every test or adding it as a rule in each JUnit test class 
	@Rule
	public MyWatcher watcher = new MyWatcher();
,
can I do this at a suite level ?

**Comment by kcooney** [comment]
A rule is a decorator that wraps the `Statement` that runs the test method, class or suite. If you had a `TestWatcher` at the suite level, it wouldn't be notified about individual tests run inside the suite.

Have you looked at `RunListener`?

**Comment by PeterWippermann** [comment]
In general: If you don't want to repeat yourself and copy your `@Rule` in every test class, I would suggest to introduce a super class for your test classes and place your TestWatcher there.
For your specific use case of test reporting, `RunListener` might be a better fit than `@Rule`.

**Comment by kcooney** [comment]
Agreed with Peter here. Good luck!
