### ISSUE TITLE
How to show details when expect error

### ISSUE THREAD

**Issue by zwz987654** [junit-team/junit4#1362]
My junit tests run on jenkins server with other people's.So,I always get dirty data like this:
`java.lang.Exception: junit.framework.ComparisonFailure: row count (table=t_beststore_ylx_task_record) expected:<[1]> but was:<[2]>`
How can I know what dirty data id?
The dirty data from other's test case,so I hardly find out where the data inserted.I also use @DatabaseTearDown to clean database,so i cant get data via checking database.
Is junit offer methods to show error details?I hava so many junit cases,its too hard to amend all.

**Comment by kcooney** [comment]
Assertion libraries like Truth or Fest often provide better assertion messages.

If that doesn't help, I suggest asking on http://stackoverflow.com (though you will likely need to provide more details including what your test looks like. Much more people read that than the JUnit issue database
