### ISSUE TITLE
ErrorCollector reports AssumptionViolatedException as failure when assumption is not meet multiple times.

### ISSUE THREAD

**Issue by rpost** [junit-team/junit4#1363]
Sample test:

``` java
import org.junit.Assume;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ErrorCollector;

public class SampleTest {

    @Rule
    public ErrorCollector errorCollector = new ErrorCollector();

    @Test
    public void test() throws Exception {
        errorCollector.checkSucceeds(() -> {
            doSth();
            return null;
        });
        errorCollector.checkSucceeds(() -> {
            doSth();
            return null;
        });
    }

    private void doSth() {
        Assume.assumeTrue(false);
    }

}
```

Expected result: test ignored.
Actual: test failed.

Working as expected (ie. test results as ignored) when:

``` java
    @Test
    public void test() throws Exception {
        errorCollector.checkSucceeds(() -> {
            doSth();
            return null;
        });
    }
```

**Comment by kcooney** [comment]
I am tempted to argue that error collector shouldn't be used for assumption failures. ErrorCollector is intended to allow you to make an assertion but have the test continue. Assumption failures are meant to stop processing and move on to the next test.

Perhaps if the delegate passed to `checkSucceeds()` throws an assumption failure  `checkSucceeds()` should immediately rethrow the exception

**Comment by rpost** [comment]
> Perhaps if the delegate passed to checkSucceeds() throws an assumption failure checkSucceeds() should immediately rethrow the exception

That's what I'd expect

**Comment by kcooney** [comment]
@rpost Could you send us a pull with that change and a test? The JavaDoc should document this of course

**Comment by rpost** [comment]
I took a look into code and now I think we should make all `ErrorCollector` AssumptionViolationException-proof, which implies changes in `org.junit.Assert#expectThrows` so that assumption violation is rethrown if expected exception is not `AssumptionViolationException`. Do you agree?

**Comment by kcooney** [comment]
I don't think `expectThrows()` should special case `AssumptionViolationException`. The contract of `expectThrows()` is very explicit; if the expected exception isn't thrown by the lambda you get an assertion error.

Taking a step back, what problem are you trying to solve? The expressions passed into these methods should be production code, not test code, and `AssumptionViolationException` should generally be thrown by test code.

**Comment by rpost** [comment]
> Taking a step back, what problem are you trying to solve?

I worked around my initial problem with my code. I just wanted to ensure correct behavior for `AssumptionViolationException` wherever it is thrown but now I started to doubt :).

**Comment by kcooney** [comment]
I am actually now leaning to having `ErrorCollector` wrap `AssumptionViolationException` in another exception if it is the only collected exception. That way, if you have any collected errors you'll get a failure (not a skipped test)

**Comment by kcooney** [comment]
After working on #1363 here's what I think we should do

- If the `Callable` passed to `ErrorCollector.checkSucceeds()` throws an `AssumptionViolatedException` then `checkSucceeds()` should wrap it with an `AssertionError` (with a useful message) before calling `addError()`
- If an `AssumptionViolatedException` is passed to `addError()` then `addError()` should wrap it with an `AssertionError` (with a different message) before adding it to `errors`

I don't like the idea of changing `checkSucceeds()` and/or `addError()` to throw exceptions if passed `AssumptionViolatedException`. Current users of these methods can reasonably expect that they will never throw an exception. In addition, if these methods did throw when encountering `AssumptionViolatedException` that would put a high burden on the callers. `ErrorCollector` rethrows any collected errors, so deferring the failure to `verify()` should be safe.

That being said, *maybe* `addError()` should throw a `NullPointerException` if you pass in a `null` (currently if you do this, `MultipleFailureException.getMessage()` will throw a `NullPointerException`). The caller shouldn't have a problem avoiding passing in a `null`.
