### ISSUE TITLE
No documentation for running filtered tests from the command line

### ISSUE THREAD

**Issue by accesio** [junit-team/junit4#1364]
Hi

There's no documentation that explains how to use the new features such as --filter, from the command line  to select different categories of tests. You provide documentation for scala and gradle
( https://github.com/junit-team/junit4/wiki/Categories ) but not from the command line itself.

**Comment by kcooney** [comment]
https://github.com/junit-team/junit4/wiki/Test-runners would be he best place to do this (unless you think we should create a specific page foe this)

@accesio would you like to make a first pass at this?

**Comment by cttillman** [comment]
I am interested in writing documentation for this. What is the policy for editing the wiki? Is there a review process? Do I submit drafts somewhere in particular?

**Comment by marcphilipp** [comment]
There's no real policy/process. Feel free to edit the wiki and post a comment here so we can review. Thanks!

**Comment by cttillman** [comment]
Okay. I edited the section under Categories on the page https://github.com/junit-team/junit4/wiki/Test-runners.

**Comment by marcphilipp** [comment]
LGTM, thanks!
