### ISSUE TITLE
net.sf.proguard:proguard:jar must specify an absolute path

### ISSUE THREAD

**Issue by henrik242** [junit-team/junit4#1366]
I get a strange error in my Gradle build.  Is this a junit4-ant problem?

    Processing of /home/travis/.gradle/caches/modules-2/files-2.1/com.carrotsearch.randomizedtesting
      /junit4-ant/2.3.4/f671cb9471d984103ccaaf09fcbc7fc6d8be07a0/junit4-ant-2.3.4.pom failed:

    'build.plugins.plugin[com.pyx4me:proguard-maven-plugin].dependencies.dependency.systemPath' 
      for net.sf.proguard:proguard:jar must specify an absolute path but is 
      ${project.basedir}/lib/proguard.jar in com.carrotsearch.randomizedtesting:junit4-ant:2.3.4

**Comment by kcooney** [comment]
This isn't maintained by us. I.searched for "com.carrotsearch.randomizedtesting" and it looks like you want https://github.com/randomizedtesting/randomizedtesting
