### ISSUE TITLE
Why does RuleChain use a List internally instead of a stack?

### ISSUE THREAD

**Issue by jaredculp** [junit-team/junit4#1368]
Curious why a list was chosen for a problem that has LIFO semantics?

In other words, why

```
public RuleChain around(TestRule enclosedRule) {
    List<TestRule> rulesOfNewChain = new ArrayList<TestRule>();
    rulesOfNewChain.add(enclosedRule);
    rulesOfNewChain.addAll(rulesStartingWithInnerMost);
    return new RuleChain(rulesOfNewChain);
}
```

vs

```    
public RuleChain around(TestRule enclosedRule) {
    chain.push(another);
    return this;
}
```
where `this.chain` is a `Deque<TestRule>`.

Is this simply due to `Deque<T>` not being introduced until JDK 1.6?

**Comment by kcooney** [comment]
Stack extends Vector, and Vector predates the new collection classes, so that wouldn't be a good choice. 

JUnit 4 still only requires JDK 1.5. That might change in the future, but using `Deque` isn't a good enough reason to change JUnit's required JDK.

**Comment by jaredculp** [comment]
Makes sense. Thanks!
