### ISSUE TITLE
how to test a single test in cli

### ISSUE THREAD

**Issue by ddwolf** [junit-team/junit4#1369]
I have a test class:
TestClassA
   |---methodA
   |---methodB

how can I test just methodA using comman line?

**Comment by Tapan2064** [comment]
//test class`
package test1;

public class TestClassA {

	static int a=9;
	int b=8;
	public static int methodA(){
		a++;
		return a;
	}
	public int methodB(){
		b++;
		return b;
	}
	

}
`

//Implementing junit 
package test1;

import static org.junit.Assert.*;

import org.junit.Test;

public class TestJunit {

	   @Test
	   public void testPrintMessage() {
	      assertEquals(10,TestClassA.methodA());
	   }
}

//Required class for solution
package test1;

import org.junit.runner.JUnitCore;
import org.junit.runner.Request;
import org.junit.runner.Result;

public class TestCheckingviacommandline {
    public static void main(String... args) throws ClassNotFoundException {
        String[] classAndMethod = args[0].split("#");
        Request request = Request.method(Class.forName(classAndMethod[0]),classAndMethod[1]);

        Result result = new JUnitCore().run(request);
        System.out.println(result.wasSuccessful());

    }
}

//command line argument for TestCheckingviacommandline.class  {**test1.TestJunit#testPrintMessage**}

**Comment by ddwolf** [comment]
# {test1.TestJunit#testPrintMessage}# this is for maven's command line?

**Comment by kcooney** [comment]
@ddwolf if you are using Maven see
http://maven.apache.org/surefire/maven-surefire-plugin/examples/single-test.html

**Comment by ddwolf** [comment]
@kcooney I dont' use maven...and I know how maven achieve this.
I just use `java -cp $CLASSPATH org.junit.runner.JUnitCore --some other  options`

**Comment by kcooney** [comment]
@ddwolf I suggest looking into Maven or Gradle. They both should support what you want (so we havenw spent time to duplicate that work in JUnitCore). I also suggest installing an IDE and running tests from the IDE (I use Eclipse, but IntelliJ IDEA is quite popular)

**Comment by Tapan2064** [comment]
**@ddwolf**  I have implemented in Eclipse its work.
create a project,inside that project create a package test1 and create all the three classes and pass {**test1.TestJunit#testPrintMessage**} as a command argument of **TestCheckingviacommandline.java** it will work.I think its not a part of MAVEN.

test1->package
TestJunit->class
#->for separation
testPrintMessage->method (here you can pass your own create method)

**Comment by kcooney** [comment]
In Eclipse, you just right-click on the test method and select "Run As -> JUnit Test"

**Comment by ddwolf** [comment]
@kcooney @Tapan2064 
this solution solved my problem
http://stackoverflow.com/a/9288513
