### ISSUE TITLE
Lack of the official XML schema definition for a JUnit report.

### ISSUE THREAD

**Issue by gdemecki** [junit-team/junit4#1387]
Please correct me if I'm wrong, but it seems to me that there doesn't exist a good description of the XML file format for reports produced by the JUnit.

On the internet we can find a few such XSD files provided by 3rd parties (via a reverse engineering), but there are usually outdated. 

Wouldn't be good to have an official format available for everyone? Placed in the JUnit source code or on the Wiki?
I guess it would be very valuable for every tool which parses JUnit test output, since JUnit's report format is de facto a standard in the Java world.

Kind regards,
Greg

**Comment by kcooney** [comment]
JUnit doesn't produce this XML.

**Comment by baev** [comment]
@gdemecki I guess you mean `surefire.xml`. So you can find the schema here https://github.com/apache/maven-surefire/blob/master/maven-surefire-plugin/src/site/resources/xsd/surefire-test-report.xsd

And xml parser https://github.com/apache/maven-surefire/tree/master/surefire-report-parser

**Comment by gdemecki** [comment]
Thanks @baev and @kcooney. This answers my question clearly.
