### ISSUE TITLE
Assert.assertThrows gives unhelpful message if the code throws an exception with the same name from a different package

### ISSUE THREAD

**Issue by PeteGillinGoogle** [junit-team/junit4#1388]
This test:

  @Test
  public void foo() {
    Assert.assertThrows(com.google.foo.NotFoundException.class, this::bar);
  }

  private void bar() {
    throw new com.google.bar.NotFoundException();
  }

fails with the message "unexpected exception type thrown; expected: java.lang.String<NotFoundException> but was: java.lang.String<NotFoundException>" which is not very helpful.

Given how easy it is to accidentally import exceptions with common names like this from the wrong package, it seems like it would be good if it explained better what I'd done wrong (i.e. include the package names).

**Comment by marcphilipp** [comment]
Good catch, thanks!

**Comment by PeteGillinGoogle** [comment]
Thanks for the super-quick fix!
