### ISSUE TITLE
JUnit 4 output is wrong when same test run twice via a suite

### ISSUE THREAD

**Issue by gmkayaker** [junit-team/junit4#139]
Create a suite that runs the same test class twice. Run the suite. The output shows the class run twice but only the last (i.e. 2nd) class has a result annotation and only the tests in the last class have failure traces. If a test fails in both runs, both failure traces are included under the last class. If the test only fails in one of the runs, its hard to tell which run failed.

I'm using the JUnit built into Eclipse 3.6.

**Comment by FrankHJCuypers** [comment]
This bug is still haunting me. Any updates?

**Comment by dsaff** [comment]
Unfortunately, no, sorry, nothing for a while.

**Comment by suttermichael** [comment]
we have the same issue. In our case we execute the tests with feature toggle variation to ensure that the implementation is running with feature switched on/off.
Is there something happening on this issue?

**Comment by kcooney** [comment]
A run of a test is associated with a `Description` (which as the name implies, represents a description of a test, not a run of a test). I don't see how JUnit could support multiple results from running the same test without breaking users that extend our API.

If you are wanting to run a test with a feature on or off you can use `Parameterized` and have a parameter for each feature you need to toggle.

Given we have no path to resolve this issue, I recommend closing it. If any users need this functionality, I suggest seeing if JUnit 5 supports this use case, and if not file a feature request there.

**Comment by rosariop** [comment]
Is this bug still open? I encoutered the problem today!

**Comment by kcooney** [comment]
We haven't done anything to support running the same test multiple times, and are not likely to do so (see #issuecomment-282068210).

The workaround is to use `Parameterized` and have different parameter values for the different runs
