### ISSUE TITLE
Name conflict on @Before(d) method with its homonym in its base class

### ISSUE THREAD

**Issue by stephaneeybert** [junit-team/junit4#1407]
Having a @Before(d) method in a class, and another @Before(d) method bearing the same name in its base class, makes the base class method not being called.

Renaming one of the two methods solves the issue.

Version: 4.12.

**Comment by marcphilipp** [comment]
Well, if you override a method in the subclass you effectively replace the base class method so there is only one left for JUnit to execute. 🤔

**Comment by stephaneeybert** [comment]
Makes sense.

**Comment by kcooney** [comment]
I personally recommend making `@Before` and `@After` methods final.

**Comment by marcphilipp** [comment]
I also prefer not to overwrite `@Before` and `@After` methods.

But if you really have to, you should add a call to the `super` implementation to execute both:

```java
public class Base {
    @Before public void setUp() {/* do something */}
}
public class Subclass {
    @Before @Override public void setUp() { super.setUp(); /* do something else */ }
}
```

**Comment by stephaneeybert** [comment]
I had done the explicit super call before (and indeed it worked) but was simply puzzled why I had to. My eyes must have been glued too much that day :-)

**Comment by marcphilipp** [comment]
Sure, no problem at all. 🙂
