### ISSUE TITLE
Trimmed stack traces do not include suppressed throwables

### ISSUE THREAD

**Issue by dmlloyd** [junit-team/junit4#1426]
Sometimes suppressed exceptions contain critical context.  Trimmed stack traces should include suppressed exceptions if any are present.

The workaround is to disable trimmed stack traces.

Ref: getTrimmedStackTrace in org.junit.internal.Throwables

**Comment by kcooney** [comment]
Could you provide a sample stacktrace that is problematic? It would be easier to fix this problem if you give the original trace and the trimmed version. Thanks.

**Comment by panchenko** [comment]
This is about [Throwable.addSuppressed(Throwable)](https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html#addSuppressed(java.lang.Throwable)) and [Throwable.getSuppressed()](https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html#getSuppressed()) methods introduced in java 1.7.

Currently in `Throwables` when building the trimmed version only `getCause()` is appended, it should also process the suppressed ones if present and running on 1.7, possible via reflection.
