### ISSUE TITLE
ExternalResource after() not called if before() throws

### ISSUE THREAD

**Issue by CorinnaL** [junit-team/junit4#1427]
If an Exception is thrown during the execution of the before() method in a class inherited from the ExternalResource rule, the after() method is not called. This differs from the behavior of the @Before / @After annotations which is why I assume this is not intended. 

```
public class MyExternalResource extends ExternalResource {
	@Override
	public void before() throws RuntimeException	{
		System.out.println("Rule before() called");
		throw new RuntimeException();
	}
	@Override
	public void after() {
		System.out.println("Rule after() called");
	}
}
```
```
public class MyTest {
	@Rule
	public MyExternalResource ext = new MyExternalResource(); 
	@Test
	public void myTest() {
		System.out.println("Test called");
	}
}
```

From the above code I would expect

>  Rule before() called
>  Rule after() called

but get only

>  Rule before() called

**Comment by kcooney** [comment]
Thw behavior of this rule has been this way for so long that I suspect changing it would break people.

**Comment by CorinnaL** [comment]
I certainly would not want anyone to break. I also just realized that this behavior is documented and thus probably no news to you. Thank you for the response!
