### ISSUE TITLE
Theories Runner runs @Theory methods before Mockito's JUnitRule initializes mocks

### ISSUE THREAD

**Issue by magneticflux-** [junit-team/junit4#1433]
Mockito's `JUnitRule` rule runs the `MockitoAnnotations.initMocks(testClass)` method after all `@DataPoint` annotated fields have been acquired. This causes all `@DataPoint` annotated fields to appear to be `null` when the tests are run. This is due to the nature of `PotentialAssignment`, which maintains a reference to the field's _value_, but not the field itself.

Is there any way to allow Mockito's automatic mocking rule assign the values to the fields so that the Theories runner can see them? My naïve solution would be to instead reference each field (or index of List/Array) in an `Assignment` or `PotentialAssignment`, but I'm sure that would introduce all sorts of other bugs.

**Comment by kcooney** [comment]
@magneticflux Could you clarify your use case? Do you have `@DataPoint` fields that you want to initialize to a mock object? Data point fields must be static, so I don't see how `MockitoAnnotations.initMocks(testClass)` could be used to initialize them.

**Comment by magneticflux-** [comment]
@kcooney The `MockitoAnnotations.initMocks(testClass)` gets an instance of the test class through the `apply` method in the `MethodRule` class. It then uses the `Class.getDeclaredFields()` method to access each field, before setting the field using the provided test class instance. If the field is null, as per Oracle Javadocs for `Field.setField`, the instance is ignored.

As for my use case, I have fields declared `public static` that are annotated with `@Mock` and `@DataPoint`. Even if I add a rule as described here:
```
@Rule
public final MockitoRule mockitoRule = MockitoJUnit.rule().strictness(Strictness.STRICT_STUBS);
```
The fields annotated with `@Mock` are null when the Theories runner looks for them. They _are_ non-null as the test method runs, but since I only access the parameters passed to the test method, I only receive null objects.

**Comment by magneticflux-** [comment]
@kcooney [Here](https://github.com/magneticflux-/MinesweeperJ/blob/example-mockito-junit-theories-null-issue/src/test/java/org/skaggsm/minesweeperj/entities/PlayerInfoTest.java#L54) is a test class that causes the issue. The line with the failed assertion is the one highlighted. Repo has a Gradle wrapper, so you should be able to clone and build it for yourself if you want to experiment.

**Comment by kcooney** [comment]
This is working as intended. When you have a field or method that is annotated with `@Rule`, the rule is applied "around" each test method. The `@DataPoints` methods and fields, however, are evaluated before any of the test methods are executed (so JUnit can enumerate the test cases). So the rule can't be "in scope" when the data points are evaluated.

We could possibly special case `@DataPoint` fields so they would be dereferenced just-in-time, but that would make their behavior inconsistent with how other data point members are evaluated, so could lead to confusion.

You could probably use `MockitoRule` with `@ClassRule` and that might cause the field annotated with `@DataPoint` and `@Mock` to be initialized with a mock instance before the field is evaluated by JUnit.

I think it would be simpler to initialize the field to a mock instance at declaration time.

**Comment by magneticflux-** [comment]
Okay, thank you for the explanation. I'll experiment with your `@ClassRule` idea and see if it's viable for initializing fields before the Theories runner can get to them.

That's what I'm doing as a workaround. I initialize the mock in a static method annotated with `@BeforeClass` and immediately do any stubbing. Since that's working, and `@ClassRule` fields run before any `@BeforeClass` methods, I expect updating Mockito's JUnitRule to be a TestRule would work.
