### ISSUE TITLE
Hibernate integration test with junit

### ISSUE THREAD

**Issue by Diantha** [junit-team/junit4#1437]
Hello, can you please insert an example to how use integration test for hibernate with junit ? I don't have found any integration test in your project, I think it will be very helpfull for the user like me. Thank you

**Comment by kcooney** [comment]
There are countless books online resources for using hibernate and writing JUnit tests for hibernate code. I don't think the JUnit team is well suited to add to that.

If you find a particularly useful online resource, please let us know and we can link to it from the wiki.

**Comment by Diantha** [comment]
the problem is that... i haven't found anything usefull or real working...

**Comment by Tibor17** [comment]
@Diantha 
Are you looking for testing Hibernate API or rather JPA?
I created a project which has JPA Runner and able to substitute an expensive CDI container.

**Comment by Diantha** [comment]
@Tibor17  both, but I am interesting in you project
