### ISSUE TITLE
Including tests multiple times in a suite of tests.

### ISSUE THREAD

**Issue by JonathonShields** [junit-team/junit4#1444]
Hi all,

I have a requirement to run the same set of tests concurrently(in separate threads), after doing some digging about I came across ActiveTestSuite. I've seen some posts re an equivalent mechanism in JUnit 4, as of yet I've not seen a suggested out of the box supported mechanism for JUnit 4. So I've continued down the path of ActiveTestSuite, I'm happy to be told there is a different mechanism now.

So to the issues I'm having, I eventually got my test suite running, our custom base test classes need so updates to be thread safe. So I have two identical test suites added to the ActiveTestSuite and its running in 3500 tests successfully in Eclipse. The issue arrises when I try to execute the test suite on the command line. Unfortunately(for me) the test execution must be done via Gradle, I'm relatively new to Gradle, so I'm not sure if the issue I'm having is solely a Gradle JUnit integration issue or if there is a general issue with running the test suite from the command line. I haven't came across any real examples of it being used from the command line.

So the types of errors I'm getting seem to be unexpected JUnit lifecycle errors:

```
    java.lang.AssertionError: Unexpected start event for test_insert_positiveFlow_allFields(my.test.MemberTest)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestEventAdapter.testStarted(JUnitTestEventAdapter.java:56)
    	at org.junit.runner.notification.RunNotifier$3.notifyListener(RunNotifier.java:87)
```

and 

```
    java.lang.AssertionError
    	at org.gradle.api.internal.tasks.testing.processors.TestOutputRedirector.setOutputOwner(TestOutputRedirector.java:49)
    	at org.gradle.api.internal.tasks.testing.processors.CaptureTestOutputTestResultProcessor.completed(CaptureTestOutputTestResultProcessor.java:80)
    	at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.completed(AttachParentTestResultProcessor.java:56)
    	at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.completed(AttachParentTestResultProcessor.java:56)
    	at org.gradle.api.internal.tasks.testing.junit.TestClassExecutionEventGenerator.completed(TestClassExecutionEventGenerator.java:83)

```
There are other similar unexpected event assertions thrown during the test execution. I've dug about a bit and can't see any examples of the ActiveTestSuite and Gradle(or Ant etc....) with respect to this type of issue. 

The task I've declared is:

```
    task parallelTestSuite(type: Test){

        //gradle.startParameter.continueOnFailure = true
        scanForTestClasses = false
        includes = ['**/*MyActiveTestSuite.class']
      	
    	environment "SERVER_DIR", "."
    	maxHeapSize = "1024m"

    	workingDir "../../"
    	afterTest { desc, result ->
    		println "Executing test ${desc.name} [${desc.className}] with result: ${result.resultType}"
    	}

    }
```

I've tried setting the fork behaviour but to be honest the default configuration is what I want, i.e. parallel threads in the same JVM. Again I'm not sure if the Gradle test runner just can't handle the same tests being executed(at the same time), i.e. it has a singleton map of test descriptions.

Any help much appreciated. 

Thanks.

**Comment by JonathonShields** [comment]
It appears the gradle test runner is using the JUnit Description as a unique key for the test execution and validates against it, the way its implemented it seems it doesn't support current running of the same test suites. 

I know this is probably 'hacky' but is there a way to override the auto generated description, for example append the thread ID to it so that all tests will be seen as unique? I know this could cause other  issues as it seems the framework itself uses the Description class a lot.

**Comment by kcooney** [comment]
The JUnit `RunListener` API uses `Description` as well so many things break if you run the same test class multiple times. We have no plans to fix this in JUnit 4. No idea if JUnit 5 supports that use case.

If you use a custom `Runner` you may be able to provide different `Description` instances for different instances of the same class in a suite of tests, but I would caution against doing so in a way that isn't deterministic. Also, timeouts in JUnit use threads, so if you use a thread ID in the description, you might see weird behavior.

**Comment by JonathonShields** [comment]
The JUnit 4 test runner in Eclipse has no issues running the test suite and doesn't fall fowl of running the same test multiple times. It does seem specific to the Gradle integration, specifically in JUnitTestEventAdapter.java.

Is there a way to override this class and provide a custom implementation? I'm not sure what else I can do :(

**Comment by kcooney** [comment]
Our API doesn't provide a way to know which of the n copies of the test had a test failure, so I would be surprised if Gradle was the only tool that didn't work well for what you are trying to do.

I suggest reaching out to the JUnit 5 team.

**Comment by JonathonShields** [comment]
Thanks I appreciate your time. I'm not sure what contacting the JUnit 5 team could offer, the issue isn't in JUnit as I see it, now I could be wrong here.

The ActiveTestSuite class has been around since JUnit 3, the suite passes fine in Eclipse using the default runner. Automating their execution is my issue now, and it seems the Gradle integration and perhaps others as you have highlighted aren't designed to support the same test running twice in separate threads.

**Comment by kcooney** [comment]
You are running against a fundamental design assumption of JUnit 4. It isn't related to threads. Test methods are assumed to be uniquely identifiable by `Description` values.

I suggested contacting the JUnit 5 team because they designed a new API that build tools and IDEs can use to run tests. When if that API didn't have that same deep assumption, the test engineer used by JUnit 5 running JUnit 3 and 4 tests still has that assumption, so you would need to migrate your tests to JUnit 5 style.

JUnit 3 is over a decade old. We support it because the emulation layer is stable, but users should move to the newer APIs.

**Comment by JonathonShields** [comment]
Thanks again. So I think its safe to say the JUnit itself doesn't explicitly support the execution of the same test(s) concurrently at least not by design?

**Comment by kcooney** [comment]
Again, concurrency isn't the issue. We hopefully resolved those.

If I understand correctly, you are running the tests in a class multiple times in a single test run. The problems are 1) JUnit will send multiple starting events to the listener with the same `Description` values (so the listener can't tell which one is reporting failures) and 2) my guess is if you went to the top if the `Runner` hierarchy and walked the `Description` tree you would see no duplicate descriptions (the duplication happens at test execution time, but your model includes the test once). If so, that would likely confuse most tools (possibly even JUnit's command-line runner).
