### ISSUE TITLE
assertEquals passes when it should fail when strings begin with escaped character

### ISSUE THREAD

**Issue by ezrasavard** [junit-team/junit4#1446]
When using assertEquals(String a, String b), the following assertion will pass, when it should obviously fail:

`assertEquals("\bbar", "\bfoo");`

After tracing the process, it seems likely that this is related to how junit processes the strings in order to produce the expected/actual log statement.

**Comment by kcooney** [comment]
I could not reproduce this with either `org.junit.Assert.assertEquals(String, String)` or `junit.framework.Assert.assertEquals(String, String)`:

Here's the test of `org.junit.Assert`:

    @Test
    public void stringsStartingWithSameEscapedCharacterDiffer() {
        try {
            assertEquals("\bbar", "\bfoo");
        } catch (ComparisonFailure exception) {
            assertEquals("expected:<\b[bar]> but was:<\b[foo]>", exception.getMessage());
            return;
        }
        fail("ComparisonFailure expected");
    }

Here's the test of `junit.framework.Assert`:

    public void testStringsStartingWithSameEscapedCharacterDiffer() {
        try {
            assertEquals("\bbar", "\bfoo");
        } catch (ComparisonFailure exception) {
            assertEquals("expected:<\b[bar]> but was:<\b[foo]>", exception.getMessage());
            return;
        }
        fail("ComparisonFailure expected");
    }

Do these fail for you? What version of JUnit are you using? What platform?

**Comment by ezrasavard** [comment]
Thanks for your reply -- I'm using JUnit 4.12, packaged with IntelliJ IDEA 2016.3.6. I'm using org.junit.Assert, so I'm focusing on that one here.

This is the code I am running, and the results are interesting. The first test passes, and so does the second. I'm not sure why this would happen.

```
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.junit.ComparisonFailure;
import org.junit.Test;

public class TestMain {

    @Test
    public void testFoobars() {
        assertEquals("\bfoo", "\bbar");
    }

    @Test
    public void stringsStartingWithSameEscapedCharacterDiffer() {
        try {
            assertEquals("\bbar", "\bfoo");
        } catch (ComparisonFailure exception) {
            assertEquals("expected:<\b[bar]> but was:<\b[foo]>", exception.getMessage());
            return;
        }
        fail("ComparisonFailure expected");
    }
}
```
I've run this test using IntelliJ and also with Maven from the commandline. Can you reproduce my first test passing?

**Comment by panchenko** [comment]
I can reproduce this in IntelliJ, in Eclipse and Maven works as expected.
I would suggest reporting a [bug](https://youtrack.jetbrains.com/issues/IDEA), most likely this failure is lost while sending it to IDE.

**Comment by ezrasavard** [comment]
I'm surprised about it working in Maven, but I suppose my Maven config is pointing to the junit package that came with IntelliJ - I'll be back at work on Monday and will check back in then. Thanks for your support.

**Comment by kcooney** [comment]
@ezrasavard if you can reproduce in IntelliJ you can launch in a debugger and see if an exception is thrown from. `testFoobars()` and,  if so, if it gets reported to the registered `RunListener` instances.

Alternatively add a call to `fail()` after the assertion in `testFoobars()`.

**Comment by ezrasavard** [comment]
Thanks again for the input -- since I can reproduce it with both IntelliJ and Maven (using the JUnit package from IntelliJ), the issue probably is with that package.

Can anyone else reproduce the issue using JUnit from IntelliJ, but running a test with Maven?

**Comment by panchenko** [comment]
Seems like with "Maven" you mean something different than the `mvn test` command executed in the terminal window :smile: 
From the command line it works, but IntelliJ has issues.

**Comment by ezrasavard** [comment]
I'll try it again tomorrow @panchenko, but `mvn test` is what I used.

**Comment by panchenko** [comment]
Just in case I've created an [example project](https://github.com/panchenko/junit-examples/tree/master/issue1446)

**Comment by kcooney** [comment]
@ezrasavard since you are (so far) the only one to see this, you are probably the best one to track down the issue. You can launch your test under the debugger in IntelliJ and set breakpoints in your test methods and the following methods:

-  `org.junit.runner.notification.RunNotifier.fireTestFailure()`
- `org.junit.runners.ParentRunner.run()` ([here](https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/runners/ParentRunner.java#L374) and [here](https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/runners/ParentRunner.java#L380))

**Comment by panchenko** [comment]
I've tried before - an exceptions happens and it's lost by the Inteelij runner.

**Comment by ezrasavard** [comment]
Thanks all - with the help of @panchenko 's test project, I've reproduced the correct behaviour with `mvn test`. I'll open this with IntelliJ.

**Comment by kcooney** [comment]
@ezrasavard Please add a link to the IntelliJ bug/thread. I am extremely curious about what is going on.

My guess: they have a custom serialization format for sending data from JUnit to the IDE and that format can't handle the message.

**Comment by ezrasavard** [comment]
https://youtrack.jetbrains.com/issue/BND-1442
I added some notes from a bit more digging when reporting there. I wasn't able to dig in fully since I couldn't find source code for the caller at the point of failure.
