### ISSUE TITLE
@Test alongside Lombok's @Delegate annotation?!

### ISSUE THREAD

**Issue by wheredevel** [junit-team/junit4#1457]
Guys, I repost my issue with [Lombok](https://github.com/rzwitserloot/lombok) and [JUnit](https://github.com/junit-team/junit4).  
Issue: https://github.com/rzwitserloot/lombok/issues/1356

I believe It's a cool feature actually (saves me alot of time, but need to workaround the `@Test` annotation limitation):

Original
----
Hi, guys!  

I'm mixing-in a "template" test into an "origin" test.
Something like:
```
public interface TestSomething {
  void testSomething() throws Exception;

  @Builder
  public static final class Mixin {
    public void testSomething() throws Exception {
      // some actual test here
    }
  }
}

public class MyTest {
  @Delegate
  private TestSomething testSomething = TestSomething.Mixin.builder().build();
}
```
(Note: I omitted a way I pass MyTest context to the Mixin - it's an important part, but irrelevant to the issue subject.)

So, the question is:  
**How do I make JUnit discover the `testSomething()` of the origin, generated by `@Delegate`, as a test - like it was annotated with `@Test`** ?

Followup
----
So, guys, how hard is it to allow `@Test` annotation near the `@Delegate` one?: 
```
public class MyTest {
  @Delegate
  @Test 
  private TestSomething testSomething = TestSomething.Mixin.builder().build();
}
```

I guess, adding an `onMethod` to `@Delegate` is a dream come true:
```
public class MyTest {
  @Delegate(onMethod=@__({@Test}))
  private TestSomething testSomething = TestSomething.Mixin.builder().build();
}
```

**Comment by panchenko** [comment]
JUnit runs the methods annotated with `@Test`, if your tool generates those automatically - it should also generate this annotation, then it would work out of the box. There is nothing JUnit should do in this case.

Also, on JUnit4 side additional ways to discover tests can be implemented in an runner.

Another approach would be posting a question on StackOverflow and describing the problem your trying to solve instead of a particular approach. You might get some new ideas then.

**Comment by wheredevel** [comment]
My idea of posting this here, is about to show how `JUnit` tests can be **templated** and **mixed-in** easily using `Lombok` - and, hopefully, to push the community to closing this small gap.

**Comment by kcooney** [comment]
We would be unlikely to add support for.Lombok in JUnit 4.x (we currently still depend on JDK 5!)

If you cannot generate methods annotated with `@Test` you could create a runner that extends `BlockJUnit4ClassRunner` to find the methods.

It is possible that JUnit 4 would have better extension points for allowing you identify these methods as test methods.
