### ISSUE TITLE
Add assertThrowsOnNullArguments

### ISSUE THREAD

**Issue by NWuensche** [junit-team/junit4#1461]
Hello everybody,
is it possible to create a new assert? It should pass iff every argument of the constructor of a class throws an NPE, otherwise not. I think this could reduce code smell a lot.

**Comment by kcooney** [comment]
Does this meet your needs?

https://github.com/google/guava/blob/master/guava-testlib/src/com/google/common/testing/NullPointerTester.java

**Comment by NWuensche** [comment]
Jup, thanks.
