### ISSUE TITLE
How to remove the default number associate to File.createTempFile

### ISSUE THREAD

**Issue by jabrena** [junit-team/junit4#1469]
Hi,

I am doing Mock tests to emulate a Interface based on a Linux filesystem but I have some problems with the usage of the Class: `TemporaryFolder`.

The real system provide a interface like:

* sys/class/battery/voltage

Using some techniques, I can replace the real path for a Mock path, but the problem that I have is when the mock create a simulated batteryMock object:

* sys/mocks/battery/voltage4428435515544614645_MOCK

The method `File.createTempFile` add some numbers:

```java
batterySensor = File.createTempFile(BATTERY_FIELD_VOLTAGE, "_MOCK", tempEV3BatteryFolder);
```

and that suffix doesn´t match with the expected location by the real Class. 

Any idea to remove completely the last part of the temporal file: `4428435515544614645_MOCK` the part about _MOCK is a parameter that maybe it is possible to be empty, ¨¨ but what happen with the number. Any alternative.

Many thanks in advance.

Juan Antonio

**Comment by panchenko** [comment]
@jabrena I afraid it's not fully clear what are you trying to do. One can assume that your project deals with files, and that's all.

The `File.createTempFile()` method intentionally adds a random number to the file name, to make sure that concurrently executed classes/programs don't conflict with each other. If for your project this randomness is not needed, then you should not use this method.

**Comment by marcphilipp** [comment]
Closing this issue as it is not JUnit-specific.

@jabrena You'll have a much better chance to find a solution to your problem if you'd post it on StackOverflow.
