### ISSUE TITLE
NPE using StaticMetamodel in more than one test

### ISSUE THREAD

**Issue by FiruzzZ** [junit-team/junit4#1472]
I created a new test class for an Entity and making queries with JPA (Eclipselink 2.6.1) but using String and concatenations of SMM (StaticMetamodel) generated, instead of Criteria API.
The thing is that after ONE test is executed (succeeded/failed) in which I use at least one SMM reference to any Attribute, all other tests throws NPE (NullPointerException) 
Examples:

`@Test public void test1() {
        getEntityManager().createQuery(("SELECT e.id FROM Entity e WHERE " + Entity_.attribute,getName() +" =value ").getResultList();
}`

`@Test public void test2() {
        getEntityManager().createQuery(("SELECT e.id FROM Entity e WHERE " + Entity_.otherAttribute,getName() + "='some string' ").getResultList();
}`

[OrdenTest.zip](https://github.com/junit-team/junit4/files/1109485/OrdenTest.zip)

**Comment by kcooney** [comment]
This sounds like an issue with your tests or the code under test, not an issue with JUnit

I suggest asking on https://stackoverflow.com/

See https://stackoverflow.com/help/mcve for suggestions on asking good questions.

**Comment by kcooney** [comment]
See also https://stackoverflow.com/questions/218384/what-is-a-nullpointerexception-and-how-do-i-fix-it

**Comment by FiruzzZ** [comment]
I never heard that someone could debug or test by sounds, you must be some kind special of..
if u want links of records/backgrounds
[https://stackoverflow.com/questions/3854687/jpa-hibernate-static-metamodel-attributes-not-populated-nullpointerexception](https://stackoverflow.com/questions/3854687/jpa-hibernate-static-metamodel-attributes-not-populated-nullpointerexception)
[https://stackoverflow.com/questions/36225377/static-metamodel-attributes-null-when-unit-testing](https://stackoverflow.com/questions/36225377/static-metamodel-attributes-null-when-unit-testing)

And maybe this will "sounds" weird but the Attributes are null at the beginning of the test. JPA, the query, the source, the IDEs (tested on Netbeans and Eclipse) can't be blamed 

musical notes example:  (this doesn't happens in all tracks)
`System.out.println("checking for null: " + Orden_.class);  //this one is not null

System.out.println("checking for null: " + Orden_.id); //this is null after the 1st succeed test

System.out.println("checking for null: " + Orden_.numero);//this is null after the 1st succeed test
`

**Comment by kcooney** [comment]
@FiruzzZ sorry but this isn't a general forum for debugging problems with tests. It's a place to report bugs or feature requests for JUnit itself.  If you isolated your problem and it is a bug in the Junit code, please create an issue here. Otherwise, unfortunately, we likely don't have the expertise or time to help you.

Good luck!
