### ISSUE TITLE
Eclosed Runner - Support multiple levels of nesting.

### ISSUE THREAD

**Issue by bzitzow** [junit-team/junit4#1473]
Does Enclosed runner support this? I can't figure out how to get the third level of nesting to work.

-> Class (test fixture that represents the class/object level)
-> -> Method 1 (context)
-> -> -> Context 1 (context)
-> -> -> Context 2 (context)
-> -> Method 2 (context)

**Comment by kcooney** [comment]
The `Enclosed` runner only runs tests in static nested class. Any of those classes could be annotated with `@RunWith(Enclosed.class)`.

You can also try https://github.com/bechte/junit-hierarchicalcontextrunner/wiki
