### ISSUE TITLE
Add getter for @Rule in a RuleChain

### ISSUE THREAD

**Issue by Ehbraheem** [junit-team/junit4#1474]
I have this 

  ```
@Rule
   public ActivityTestRule<MainActivity> mActivityTestRule
            = new ActivityTestRule<>(MainActivity.class);
    @Rule
    public ActivityTestRule<QuizActivity> mQuizActivityRule
            = new ActivityTestRule<>(QuizActivity.class, false, false);

    public ActivityTestRule<InsectDetailsActivity> mDetailActivityRule
            = new ActivityTestRule<>(InsectDetailsActivity.class, false, false);

    @Rule
    public RuleChain rules = RuleChain.outerRule(mActivityTestRule)
            .around(mQuizActivityRule)
            .around(mDetailActivityRule);
```

I want to do something like 

`rules.getrule().around(0).launchActivity();`

**Comment by panchenko** [comment]
I think `.launchActivity()` can be called directly via `mQuizActivityRule`/`mQuizActivityRule` what would be the benefit of doing that via RuleChain?
Also, RuleChain should not be needed when #1445 is merged.

**Comment by Ehbraheem** [comment]
I want to use RuleChain so I don't have to specify `mQuizActivityRule` explicitly, Since I want to manually start it for some test

**Comment by panchenko** [comment]
RuleChain is used only for ordering and the plan is switching to ordering via annotations like this:

```java
@Rule(order=1)
public ActivityTestRule<QuizActivity> mQuizActivityRule = ...

@Rule(order=2)
public ActivityTestRule<InsectDetailsActivity> mDetailActivityRule = ...
```
so RuleChain is not needed at all.

**Comment by Ehbraheem** [comment]
@panchenko Thanks for that. But I still think that feature is worth implementing.

**Comment by kcooney** [comment]
I don't see how we could write a signature for your proposed method that would not require a cast.
