### ISSUE TITLE
How to @Inject other classes when there is a @Rule

### ISSUE THREAD

**Issue by xchangcheng** [junit-team/junit4#1479]
I have defined a TestRule like this:

```
public final class ATestRule implements TestRule {
    @Override
    public Statement apply(Statement statement, Description description) {}
}
```

I have a test class like:

```
public class MyTest {
    @Inject private A a; // will be null
    @Rule public ATestRule testRule = new ATestRule();

    @Test
     public void someTest() {
     }
}
```

'A' in MyTest is null which means it's failed to be injected. But I don't want to move 'A' to ATestRule and 
access it by 'testRule'.

Any idea how to inject A (with Guice) in MyTest?

**Comment by kcooney** [comment]
I generally do this:

        @Before
        public void injectMembers() {
            Guice.createInjector(new TestModule()).injectMembers(this);
        }

create the `Injector` in a `@Before` method and then call `Injector.injectMembers(tgis

**Comment by kcooney** [comment]
See https://github.com/google/guice/wiki/BoundFields for more discussion. My team is a fan of `BoundFieldModule` which is mentioned there.

Some people like to use frameworks like GuiceBerry.

**Comment by xchangcheng** [comment]
Thanks.
I have solved it in a similar way.

```
public class MyTest {
    @Inject private A a;
    @Rule public ATestRule testRule = new ATestRule();

   @Before
    public void setUp() throws Exception {
      testRule.getInjector().injectMembers(this); // Create an injector in ATestRule and get it here.
    }
    @Test
     public void someTest() {
     }
}
```

**Comment by kcooney** [comment]
@xchangcheng that works too if your rule needs to create the injector or have access to it. For my tests, the collection of modules tends to be different for every test case.
