### ISSUE TITLE
Using Junit with Ant

### ISSUE THREAD

**Issue by lrae24** [junit-team/junit4#1481]
Hi guys ,

So im trying something and just cant seem to get the ant task to run  and print out the result .

We use the standard webapp structure and i have the  Junit and Hamcrest JAR files in my build/lib folder .My test suite is a package with my .java test cases . The issue is i see everyone referring to a class file to compile then a test class file to compile and in my case i don't have both i have just created the test cases in a standard package so i need som advice on how i would insert this in ant as i want to include this as part of a build process . So currently i have test class which import other classes from the webapp and i have some code attached but am not sure where to point the classname as i have issue pointing it directly to JUnit or JUnitCore  please could you assist me ?
![screen shot 2017-09-11 at 11 06 12 am](https://user-images.githubusercontent.com/25219824/30267013-70e9a90e-96e1-11e7-95a7-dfcd286c2f75.png)

**Comment by stefanbirkner** [comment]
Hi @lrae24,

this is the JUnit issue tracker and not a Q&A page. Please post your question on [Stackoverflow](https://stackoverflow.com/) and tag it with JUnit.

Thanks,
stefan

**Comment by kcooney** [comment]
See https://stackoverflow.com/help/how-to-ask about asking good questions on  stackoverflow.com. Also I suggest not using screenshots for the ant.xml snippet

**Comment by panchenko** [comment]
There is the [Getting started – Ant](https://github.com/junit-team/junit4/wiki/Getting-started-%E2%80%93-Ant) page already, which contains an example of the build script.
