### ISSUE TITLE
Run all tests in an IntelliJ module does not work when having class names with unicode characters

### ISSUE THREAD

**Issue by TedL** [junit-team/junit4#1482]
Trying to run all testcases by right click on the module-> Run 'All Test' results in the followng error message:
"Process finished with exit code 1
Class not found: "se.xx.yy.TjÃ¤nsteplattformenTestHelperTest"Empty test suite."

The class name is: se.xx.yy.TjänsteplattformenTestHelperTest

However running only that class works.

I'm running IntelliJ Community edition version 2017.2.4
And jUnit plugin version 1.0

I have both the global and projekt enocoding of IntelliJ set to windows-1252.

**Comment by stefanbirkner** [comment]
This seems to be an IntelliJ issue. Can you please create an issue in Jetbrains' issue tracker: https://youtrack.jetbrains.com/issues/IDEA

**Comment by TedL** [comment]
Ok, no problem.
Thank you.

**Comment by stefanbirkner** [comment]
You're welcome.

**Comment by kcooney** [comment]
FYI: the IntelliJ bug is https://youtrack.jetbrains.com/issueMobile/IDEA-179384
