### ISSUE TITLE
Help with feature implementation

### ISSUE THREAD

**Issue by helenocampos** [junit-team/junit4#1483]
Hi guys, first of all, I'm sorry for creating a topic in the issues section. I did so because I didn't find the right place.

I'm trying to implement a feature using JUnit as part of my master thesis research. 
What I'm trying to do is to allow the execution of ordered test methods from different test classes. 
Example:
Class A has methods mA1, mA2 and mA3.
Class B has methods mB1, mB2, mB3.
Class C has methods mC1, mC2.
So I want to execute: mC1, mB2, mC2, mA3 ....
The ordering feature is not the problem. My problem is the method execution.

I've spent the last month trying to figure out how JUnit works internally but I haven't made much progress.

I want to ask how would you guys approach this problem/implementation. 
Thanks!

**Comment by kcooney** [comment]
This would be really hard to do in our current code base. Is there a compelling reason to support this  behavior?

There is a pull that provides support for specifying test method order within a single class. See #1130

**Comment by helenocampos** [comment]
The reason I would like to implement this is because I'm researching about Test Case Prioritization.
In short, I've found some evidence that prioritizing test cases at the test method granularity may provide a speed-up in the fault revealing speed. This might be interesting in the regression testing scenario, where in some cases, the suite execution takes long time, delaying feedback about faults.

I've seen the specific ordering implemetation, but it solves the problem only partially.
I appreciate any ideas on how I could achieve the arbitrary method execution. Thanks!

**Comment by kcooney** [comment]
@helenocampos you can look at the code at https://github.com/junit-team/junit4/tree/master/src/main/java/org/junit/experimental/max
