### ISSUE TITLE
Three test class with the same resources

### ISSUE THREAD

**Issue by zgq1987** [junit-team/junit4#1494]
I want to load the resources only once. How can I do? Many Thanks!

**Comment by marcphilipp** [comment]
Please provide more information. What kind of resources? How do you load them?

**Comment by zgq1987** [comment]
@RunWith(PowerMockRunner.class)
public abstract class BaseTest {
	
	protected static Obj obj;
	public static Obj getObj(){
		if(null!=obj){
			return obj;	
		}
		//String to Object,I want to do it only once,because it use too many time.
		String objStr="...some str...";
		JSONObject jo = JSONObject.fromObject(json);
		obj=(Obj)JSONObject.toBean(jo, ObjClass);
		return obj;
	}
}

public class TestA extends BaseTest {
	@Test
	public void test(){
		System.out.println(getObj().toString);
	}
}

public class TestB extends BaseTest {
	@Test
	public void test(){
		System.out.println(getObj().toString);
	}
}

public class TestC extends BaseTest {
	@Test
	public void test(){
		System.out.println(getObj().toString);
	}
}

**Comment by marcphilipp** [comment]
You're already caching it so it should only be loaded once, right?

**Comment by zgq1987** [comment]
I hope that, but it load three times. Maybe every testClass will load itself?

**Comment by marcphilipp** [comment]
Might be a side-effect of the `PowerMockRunner`. Can you please ask them?

**Comment by zgq1987** [comment]
OK, many thanks!
