### ISSUE TITLE
can not find lessThan() method

### ISSUE THREAD

**Issue by VictorZhx** [junit-team/junit4#1495]
build.gradle add dependency    testCompile 'junit:junit:4.12'

Test  class can find   assertThat() method,but  cant find greaterThan() 、greaterThanOrEqualTo()、 lessThan() and so on，  why？？

**Comment by panchenko** [comment]
These methods are provided by `org.hamcrest:hamcrest-library:1.3` (or `org.hamcrest:hamcrest-all:1.3`).
