### ISSUE TITLE
[JUnit 4.13 regression] @BeforeClass shadowing in superclass doesn't work

### ISSUE THREAD

**Issue by medb** [junit-team/junit4#1509]
In JUnit 4.13 version the `@BeforeClass` method of superclass is run even if it is shadowed by current class, which is not as expected according to current JUnit 4.12 behaviour and `@BeforeClass` javadoc:
```
The "@BeforeClass" methods of superclasses will be run before those of the current class,
unless they are shadowed in the current class.
```

Repro code:
```
class Junit413RegressionSuperclass {
  @BeforeClass
  public static void beforeAll() {
    System.out.println("beforeAll - superclass");
  }
}

public class Junit413Regression extends Junit413RegressionSuperclass {
  @BeforeClass
  public static void beforeAll() {
    System.out.println("beforeAll - class");
  }

  @Test
  public void test() {
    System.out.println("test - class");
  }
}
```

Expected output (JUnit 4.12):
```
beforeAll - class
test - class
```

Actual output (JUnit 14.13-SNAPSHOT):
```
beforeAll - superclass
beforeAll - class
test - class
```

**Comment by panchenko** [comment]
This was changed in #1414
I can understand a need to override such a static method (not possible in java terms, that's why the javadoc says "shadowed").

**Comment by kcooney** [comment]
Thanks for raising this issue!

Related discussion in #1411

The 4.13 behavior seems more rational to me (you can't override static methods in Java), but if existing tests depend on the 4.12 behavior then we might need to reevaluate the changes.

**Comment by medb** [comment]
I agree that JUnit 4.12 behavior is illogical, but because `@BeforeClass` methods should be static there are no other way (as far as I know) to override behavior of superclass' `@BeforeClass` methods in subclass, and this functionality is needed on practice - my project has tests that are breaking after switching to JUnit 4.13 because of this change in behavior.

**Comment by kcooney** [comment]
@medb good point. Assuming we went with the 4.12 behavior for annotated static methods, what do you propose we do about fields? On the one hand, it would be odd to treat `ClassRule` on a shadowed field differently than on a shadowed method. On the other hand, fields are not polymorphic.

**Comment by medb** [comment]
@kcooney looks like `@ClassRule` suffers from the same issue - there is no way to override its behavior in a subclass.

If we agree that we want to provide functionality of overriding `@BeforeClass` and `@ClassRule` behavior in a subclass in JUnit 4.13 then, from my point of view, we have 2 choices:
1. resort to shadowing logic as in JUnit 4.12.
2. execute `@BeforeClass` and `@ClassRule` code only in actual test class, and ignore it in all superclasses.

While 1st approach has benefits of backward compatibility and provides all necessary functionality, it looks illogical and it's brittle - it's hard to re-factor deep enough hierarchy of test classes that shadow each others `@BeforeClass` methods.

That's why I think that 2nd approach could provide more clean solution from readability and maintainability point of view. But it will require more code if you want to execute superclass' `@BeforeClass` methods in all subclasses without any modification, but I'm not sure how this is important.

**Comment by kcooney** [comment]
Option 2 violates the principal of least surprise. A subclass should inherit the behavior of the superclass. I have countless tests that expect rules on the base class to affect subclasses.

**Comment by medb** [comment]
Agree, option 2, would be quite surprising behavior and not backward compatible.
But this is the only thing I can think as an alternative to JUnit 4.12 behavior that preserves all functionality.

We need to go back to JUnit 4.12 behavior then?

**Comment by kcooney** [comment]
I'm included to return to the JUnit 4.12 behavior for static methods/fields (i.e shadowed methods/fields "override" methods/fields from the base class with the same name) because 4.13 changes behavior that existing tests depend on, and that behavior was documented. I'd like to hear from the other maintainers, though. @junit-team/junit-committers ?

If a derived class has a field/method with the same name as a field/method in a base class, when it that method called/applied? Is it called along with the base class fields/methods or the derived fields/methods?

Note that for Rules there are other ways you could have the subclass override the behavior from the superclass. The `apply()` method is passed a `Description` for the class, and the Rule could use that to inspect the test class. Although this is more work to do, it would lead to less fragile code (it sounds like with your current solution, if someone renames the `@BeforeClass` method in the base class, the behavior of the subclasses change.

**Comment by marcphilipp** [comment]
As you said, I think the new behavior is by far more rational. The number of tests that will be broken by this change should not be very high. Thus, I'd say let's keep it and change the Javadoc (which was changed in #394 / #504).

**Comment by kcooney** [comment]
The Javadoc clarification was released in 4.11, so rational or not the current behavior for static fields/methods breaks behavior that was documented in two releases.

Then again, the Javadoc updates for `@Before` and `@After` in #504 contradict our decisions in #1411

**Comment by kcooney** [comment]
To make things concrete, here's one possible fix:

https://github.com/junit-team/junit4/commit/5ef2b8de3d751b7e06cf81dcbf64a155fe490e0a

**Comment by marcphilipp** [comment]
@stefanbirkner @dsaff What do you think?

**Comment by stefanbirkner** [comment]
I had a look at the issue but didn't think it through completely. Currently I think that we should restore the behavior of JUnit 4.12.

**Comment by marcphilipp** [comment]
In that case, let's restore the 4.12 behavior.

@kcooney Can you please take care of that?

**Comment by kcooney** [comment]
Sent out #1514

This change only affects static methods. The behavior of non-static methods is subtlety different in 4.13 due to the fixes for bridge methods.
