### ISSUE TITLE
Exclude the time in set-up/tear-down for Timeout @Rule

### ISSUE THREAD

**Issue by rlvillacarlos** [junit-team/junit4#1510]
The time for set-up/tear-down is not included when computing the time-out when using the Test annotation. 

However the time needed for set-up or tear-down is included when using the Timeout Rule. 

Is there a way to exclude the time for set-up/tear-down in the Timeout Rule? 

If none, can this be feature on the next release?

**Comment by kcooney** [comment]
There isn't a way to do this. Given the way Rules are implemented, I don't see how we could do what you are proposing. Rules execute around the test fixture (the test fixture includes the`@Before` methods, the`@After` method and the test method).

**Comment by rlvillacarlos** [comment]
Is it not possible that the timeout begins after the @Before methods then maybe stop before the @After methods?

**Comment by kcooney** [comment]
I don't think it is possible to.do what you are asking without breaking other rules. See:

- https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/rules/Timeout.java
- https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/runners/BlockJUnit4ClassRunner.java#L303

**Comment by rlvillacarlos** [comment]
I will check the links. So does it mean that the only option is to add individual timeout args in a @Test annotation?

**Comment by stefanbirkner** [comment]
Another option would be to replace before and after blocks with a rule and use rule ordering for letting the Timeout rule be the innermost rule.

**Comment by rlvillacarlos** [comment]
Will try this. Thanks!
