### ISSUE TITLE
TemporaryFolder should not follow symlinks when deleting

### ISSUE THREAD

**Issue by afwang** [junit-team/junit4#1511]
As the title states, the TemporaryFolder test rule should not follow symlinks within its temporary directory structure. Symlinks can point to anywhere else on the filesystem. If a TemporaryFolder follows those symlinks, the TemporaryFolder may end up deleting files outside of the temporary directory structure that the user does not suspect the test rule to delete.

The default behavior for TemporaryFolder should be to remove symlinks without following them. This ensures that the targets of symlinks are not accidentally deleted.

If the target of a symlink sits within the temporary directory structure, the target will eventually be deleted by TemporaryFolder without having to follow a symlink. If a target of a symlink sits outside of a directory structure, then TemporaryFolder shouldn't be deleting the target file anyway.

**Comment by kcooney** [comment]
Thanks for the big report. This was fixed in #1303
