### ISSUE TITLE
Rule and RunListener Ordering

### ISSUE THREAD

**Issue by szaluk** [junit-team/junit4#1521]
I am seeing an issue where I have a RunListener set on a runner that is always being set to ignored when we have some of our method-level rules set.  We have a very complex RuleChain with many rules defined in it.  

Is there an order of what gets executed first between Rules and Listeners?  is there anyway to force a particular RunListener to always run last after all Rules and other RunListeners are done processing?

Thanks,
Steve

**Comment by kcooney** [comment]
This kind of question can best be answered on stackoverflow.com

But yes, in the built-in runners, listeners are called at the beginning and end of each test method, so the rules are executed between them.
