### ISSUE TITLE
Any chance of starting JUnit 3 exceptions on a new line like JUnit 4?

### ISSUE THREAD

**Issue by cpovirk** [junit-team/junit4#1526]
As in, changing...

```
1) testFoo(com.google.some.Class)some.Exception: message goes here
```

...to...

```
1) testFoo(com.google.some.Class)
some.Exception: message goes here
```

The code change would be straightforward, just changing [this line](https://github.com/junit-team/junit4/blob/0038617a0a6c70c712cf30b90c849db518f3715f/src/main/java/junit/textui/ResultPrinter.java#L71) as suggested in the comment.

However, I'm sure that some people are used to grepping through test logs, and the change in format would mess with their workflow. (Perhaps this is exactly why you left the JUnit 3 behavior alone when implementing the new behavior in JUnit 4.) I also assume that you're not too interested in making changes to JUnit 3 at all. But I figured I'd ask before I start thinking about whether it's worth locally patching our JUnit 3 for the people who are stuck on it. Thanks.

**Comment by kcooney** [comment]
Any reason why you are still using the JUnit 3 APIs to run your tests? The JUnit 4 APIs can run JUnit3-style tests.

You could also just make your own listener and print things any way you want.

You should also consider migrating to the JUnit 5 APIs for running tests.

**Comment by kcooney** [comment]
`JUnit4TestAdapter` allows you run JUnit4-style tests from JUnit3. If you want to run those tests using the JUnit4 runner, you need to do the opposite. You could pass your `TestSuite` to `JUnit38ClassRunner` and pass that to `JUnitCore.run()` after installing `org.junit.internal.TextListener`.

I think just using a custom `junit.framework.TestListener` that prints the results the way you want would be simpler.

I don't think we would change the current JUnit3 behavior here.

**Comment by cpovirk** [comment]
Oh, whoops, thanks, that makes more sense. Anyway, feel free to close. I will figure out how much digging I want to do internally.
