### ISSUE TITLE
Test class execution stops after 10 minutes

### ISSUE THREAD

**Issue by bergeronjulien** [junit-team/junit4#1531]
Test class execution stops after 10 minutes and does not give any exceptions.

-Maven build
-Paremeterized class

Code that reproduce the issue:
`
public class TestClass
{
    @Parameterized.Parameters
    public static Collection<Object[]> environments() {
        return buildEnvironments(testId);
    }

    @Test
    public void test() throws InterruptedException {
        for(int i = 0; i < 100000; i++){
            System.out.println("LOOP " + i);
            Thread.sleep(10000);
        }

    }
}
`

After 10 minutes, test stops without giving any exceptions and gives current sucess status.
Can't override it with a timeout

**Comment by kcooney** [comment]
We need more details

https://stackoverflow.com/help/mcve

**Comment by bergeronjulien** [comment]
Issue updated

**Comment by kcooney** [comment]
I suspect a maven issue or some problem with your configuration. would expect it to run for 2.8 hours and finish with no errors.

Do you get the same behavior when running outside of Maven? I

**Comment by kcooney** [comment]
Please raise this issue with the Surefire team
