### ISSUE TITLE
Not able to get @Category to work, need help!

### ISSUE THREAD

**Issue by ghuangups** [junit-team/junit4#1532]
Hi,

We was trying to use this @Category feature from junit. However, we were getting unable to load Category error when executing the test.

This was what we did:
- created this file under hadoop-common:
hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/test/TestJUnitCategory.java like this:

package org.apache.hadoop.test;
public class TestJUnitCategory {
  public interface AllTests {}

  // for tests that never failed
  public interface StablesTest extends AllTests {}

  // for tests that use mini cluster
  public interface IntegrationsTest extends AllTests {}

  // for tests that failed at some time
  public interface FlakiesTest extends AllTests {}
}

Added following to root pom.xml file under hadoop:
+      <dependency>
+        <groupId>junit</groupId>
+        <artifactId>junit</artifactId>
+        <version>${junit.version}</version>
+        <scope>test</scope>
+      </dependency>

+    <test.groups>org.apache.hadoop.test.TestJUnitCategory</test.groups>
+    <junit.version>4.11</junit.version>

+        <plugin>
+          <groupId>org.apache.maven.plugins</groupId>
+          <artifactId>maven-surefire-plugin</artifactId>
+          <version>2.21.0</version>
+          <configuration>
+            <groups>${testcase.groups}</groups>
+          </configuration>
+        </plugin>

+    <profile>
+      <id>flakies</id>
+      <properties>
+        <testcase.groups>org.apache.hadoop.test.TestJUnitCategory.FlakiesTest</testcase.groups>
+      </properties>
+    </profile>
+    <profile>
+      <id>stables</id>
+      <properties>
+        <testcase.groups>org.apache.hadoop.test.TestJUnitCategory.StablesTest</testcase.groups>
+      </properties>
+    </profile>
+    <profile>
+      <id>integrations</id>
+      <properties>
+        <testcase.groups>org.apache.hadoop.test.TestJUnitCategory.IntegrationsTest</testcase.groups>
+      </properties>
+    </profile>
+    <profile>
+      <id>none</id>
+      <properties>
+        <testcase.groups>!org.apache.hadoop.test.TestJUnitCategory.AllTest</testcase.groups>
+      </properties>
+    </profile>

Also tried following to root pom.xml file but seems no help:

           <configuration>
             <groups>${testcase.groups}</groups>
+            <useSystemClassLoader>true</useSystemClassLoader>
+            <useManifestOnlyJar>false</useManifestOnlyJar>
           </configuration>
+          <dependencies>
+            <dependency>
+              <groupId>org.apache.maven.surefire</groupId>
+              <artifactId>surefire-junit47</artifactId>
+              <version>2.21.0</version>
+            </dependency>
+          </dependencies>
.
.
.

Test code for example TestSnapshot.java was annotated like this:
import org.junit.experimental.categories.Category;
import org.apache.hadoop.test.TestJUnitCategory;
.
.
@Category(TestJunitCategory.IntegrationsTest.Class)
public class TestSnapshot {
.
.

pom.xml for sub-modules was added following dependency:
+<dependencies>
+  <dependency>
+    <groupId>org.apache.hadoop</groupId>
+    <artifactId>hadoop-annotations</artifactId>
+    <scope>test</scope>
+    <type>test-jar</type>
+    <version>3.0.0-cdh6.x-SNAPSHOT</version>
+  </dependency>
+</dependencies>

Used following command to invoke tests by category:
mvn test -P integrations -X

JVM dump gave following error:

# Created on 2018-06-06T09:24:42.018
java.lang.RuntimeException: Unable to load category: org.apache.hadoop.classification.TestJUnitCategory.IntegrationsTest
   at org.apache.maven.surefire.group.match.SingleGroupMatcher.loadGroupClasses(SingleGroupMatcher.java:139)
   at org.apache.maven.surefire.common.junit48.FilterFactory.createGroupFilter(FilterFactory.java:100)
   at org.apache.maven.surefire.junitcore.JUnitCoreProvider.createJUnit48Filter(JUnitCoreProvider.java:275)
   at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:124)
   at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
   at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
   at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.classification.TestJUnitCategory.IntegrationsTest
   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
   at org.apache.maven.surefire.group.match.SingleGroupMatcher.loadGroupClasses(SingleGroupMatcher.java:135)
   ... 6 more

Any idea what was missing or wrong?

Many thanks,
George

**Comment by marcphilipp** [comment]
Maybe Surefire needs nested classes to be specified as `org.apache.hadoop.classification.TestJUnitCategory$IntegrationsTest`? In any case, this is a question for the Maven Surefire project.

**Comment by kcooney** [comment]
Alternatively ask on https://stackoverflow.com
