### ISSUE TITLE
org.junit.rules.TestName: make toString() return same value as getMethodName().

### ISSUE THREAD

**Issue by wheredevel** [junit-team/junit4#1539]
The title says it all... 
Thanks!

**Comment by marcphilipp** [comment]
Why?

**Comment by akshaypalshikar** [comment]
hi @marcphilipp 
I am trying to do my small contribution. Please see if you can merge this pull request : 
https://github.com/junit-team/junit4/pull/1550

**Comment by marcphilipp** [comment]
@aslakhellesoy @wheredevel Could you please explain why adding a `toString()` method would be useful?

**Comment by aslakhellesoy** [comment]
Why are you asking me @marcphilipp?

**Comment by marcphilipp** [comment]
@aslakhellesoy Oops, sorry about that! I meant to ask @akshaypalshikar.

**Comment by akshaypalshikar** [comment]
Hi @marcphilipp
I don't find any need of it but looked logical and easy to get started.
Let me know if you want me to cancel my pull request

**Comment by marcphilipp** [comment]
For future reference: Before putting in the effort and working on a pull request, it's always a good idea to first open an issue, explain your use case and get feedback from a maintainer.

I think in this case adding a `toString()` implementation is ok, but I would still like to know when this would be useful.

@akshaypalshikar Could you please add a sentence explaining the rationale?

**Comment by wheredevel** [comment]
@marcphilipp, I believe @akshaypalshikar followed the issue I opened on Jul 5.  
If it's not clear - I'm the one to blame.

**Comment by akshaypalshikar** [comment]
@marcphilipp
Let me know if you want me to cancel the pull request.

**Comment by kcooney** [comment]
One possible use case would be so you could pass a `TestName` instance to `String.format()`. Not sure if that justifies overriding `toString()`

**Comment by kcooney** [comment]
No one has been strongly advocating for this change, so closing this issue and the associated pull.
