### ISSUE TITLE
Link to "JUnit Toolbox" is brocken

### ISSUE THREAD

**Issue by dinoopp** [junit-team/junit4#1540]
On https://junit.org/junit4/ link to "JUnit Toolbox" ie https://junit-toolbox.googlecode.com/ is broken.

I think the code is moved from Google to GitHub.

**Comment by kcooney** [comment]
New link appears to be https://github.com/MichaelTamm/junit-toolbox

**Comment by stefanbirkner** [comment]
Fixed in source code but the fix still needs to be deployed.
