### ISSUE TITLE
BlockJUnit4ClassRunner no runnable methods

### ISSUE THREAD

**Issue by BogdanAlexandru11** [junit-team/junit4#1542]
Hi. 

I have made my own suite "MySuite.class", and I'm trying to run all the tests from the project using that suite. I have declared AllTests.class as 
"@RunWith(ClasspathSuite.class)
public class AllTests {}"

And my tests are being triggered as follows 
"@RunWith(MySuite.class)
@Suite.SuiteClasses( { AllTests.class })
public class RunAllMyTests {}"

I'm getting the following errors
"java.lang.Exception: No runnable methods
org.junit.runners.BlockJUnit4ClassRunner.validateInstanceMethods(BlockJUnit4ClassRunner.java:191)
 org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:128)
	at org.junit.runners.ParentRunner.validate(ParentRunner.java:416)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:84)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)"

If I replace AllTests.Class in Suite.SuiteClasses annotation with one test: "@Suite.SuiteClasses( { Test1.class })" or even multiple tests : "@Suite.SuiteClasses( { Test1.class, Test2class, Test3.class})" it runs fine, but if I'm trying to run all the tests as described above it crashes.

Any suggestions? 
Thanks !

**Comment by kcooney** [comment]
I am guessing one of the tests on your classpath doesn't have any public methods annotated with `@Test` (either that or some weird bug with `ClasspathSuite` or with `MySuite`). It's unfortunate that JUnit isn't telling you with class is the problem.

If you can provide a simple reproducible test case, I can look into why the exception message isn't useful, which should help future users track problems like this.

**Comment by BogdanAlexandru11** [comment]
Hi.
I will elaborate in this post what i'm trying to achieve, how it works and where it goes wrong.

I have about 600 tests in a project, and some of them fail randomly, I know it's not the best solution, but I would like when one of those tests fails, I would like to retry it 3 times. I have researched the feature and firstly I have implemented a rule, but I do not want to add the rule in each individual test, as there are too many files which constantly grow and this would not be a solution for me.

I have researched the feature and I was able to find a custom Suite and Runner which would achieve that .

MySuite looks like this 
"public class MySuite extends Suite {
    private static Class<?>[] getAnnotatedClasses(Class<?> klass) throws InitializationError {
        Suite.SuiteClasses annotation = klass.getAnnotation(Suite.SuiteClasses.class);
        if (annotation == null) {
            throw new InitializationError(String.format("class '%s' must have a SuiteClasses annotation", klass.getName()));
        }
        return annotation.value();
    }
    public MySuite(Class<?> klass, RunnerBuilder builder) throws InitializationError {
        super(null, getRunners(getAnnotatedClasses(klass)));
    }
    public static List<Runner> getRunners(Class<?>[] classes) throws InitializationError {
        List<Runner> runners = new LinkedList<Runner>();
        for (Class<?> klazz : classes) {
            runners.add(new MyRunner(klazz));
        }
        return runners;
    }
}"

And MyRunner looks like this
"public class MyRunner extends BlockJUnit4ClassRunner {

    public MyRunner(Class<?> klass) throws InitializationError {
        super(klass);
    }
    @Override
    protected void runChild(final FrameworkMethod method, RunNotifier notifier) {

        Description description= describeChild(method);
        if (method.getAnnotation(Ignore.class) != null) {
            notifier.fireTestIgnored(description);
        } else {
            RunRules runRules = new RunRules(methodBlock(method), Arrays.asList(new TestRule[]{new RetryRule(3)}), description);
            runLeaf(runRules, description, notifier);
        }
    }
}"
And my RetryRule looks like this 
"public class RetryRule implements TestRule {
    private int retryCount;

    public RetryRule (int retryCount) {
        this.retryCount = retryCount;
    }

    public Statement apply(Statement base, Description description) {
        return statement(base, description);
    }

    private Statement statement(final Statement base, final Description description) {
        return new Statement() {
            @Override
            public void evaluate() throws Throwable {
                Throwable caughtThrowable = null;
                for (int i = 0; i < retryCount; i++) {
                    try {
                        base.evaluate();
                        return;
                    }
                    catch (Throwable t) {
                        caughtThrowable = t;
                        System.err.println(description.getDisplayName() + ": run " + (i + 1) + " failed.");
                    }
                    Thread.sleep(1000);
                }

                System.err.println(description.getDisplayName() + ": giving up after " + retryCount + " failures.");
                throw caughtThrowable;
            }
        };
    }
}"


At the moment, If I'm using the following class
"@RunWith(MySuite.class)
@Suite.SuiteClasses( { Test1.class })
public class RunAllMyTests {}"
All my unit tests from the class Test1.class are being ran, and if any of the tests are failing, they're being re-run 3 times.
This also works with multiple tests that are manually entered such as
""@RunWith(MySuite.class)
@Suite.SuiteClasses( { Test1.class, Test2.class, Test3.class })
public class RunAllMyTests {}"

But this only runs 3 test classes, and I have many test classes (I haven't counted them but there are 50+) and I would like to be able to run them automatically without me manually entering each class name in the Suite.SuiteClasses.

Therefore I have created the class
"@RunWith(ClasspathSuite.class)
public class AllTests {}"
Which runs all the tests from my suite(all 600).

But when I'm trying to use the Class AllTests as a Suite.SuiteClasses with a custom runner I'm getting the error " no runnable methods"
The error is happening when the following class is being ran
""@RunWith(MySuite.class)
@Suite.SuiteClasses( { AllTests.class })
public class RunAllMyTests {}"

Thanks for reading, and let me know if you need more details on reproducing the issue.

**Comment by kcooney** [comment]
Have you tried using a debugger? The stack trace should tell you where to set the breakpoints. If you can't reproduce in an IDE, most build tools have ways of running and waiting for a debugger to attach.

(Yes, the error message should be good enough that you shouldn't need a debugger).

I do wonder if 'ClasspathSuite` is going to include `RunAllMyTests`

**Comment by kcooney** [comment]
You couldn't set a breakpoint in `org.junit.runners.BlockJUnit4ClassRunner.validateInstanceMethods()`? From there you should be able to see which test class is triggering this.

Also, does your IDE or build tool tell you which test class(es) failed?

I do think the `ClasspathSuite` forums or StackOverflow.com would be better places to ask this.

**Comment by arushabt** [comment]
Hi @BogdanAlexandru11 ,

Did you find any solution for above

**Comment by cristitech** [comment]
Make sure you **import org.junit.Test**, and not something else.

**Comment by code-newbie** [comment]
> Make sure you **import org.junit.Test**, and not something else.

work for me.
