### ISSUE TITLE
Junit Parameterization without private properties

### ISSUE THREAD

**Issue by dileepguntamadugu** [junit-team/junit4#1543]
**This is more of a query than an issue and I'm very Naive to Junit

I'm working on a Test Automation project which is based on Junit + Selenium. I would be needing a lot of test data for each of the scenario.

I've maintained a csv file to store the data, where in I'm reading the csv data and then mapping the header columns to the records values as a list of object. 

Is it possible for Junit Parameterized tests running without the private properties?
because,
1. There would be so many fields in the csv file and it would be a tedious job to create private properties for each of the test data.
2. The getRecords() method will return the data only as a object row mappings and it is not appropriate to define some private property for this row data.

`package core.utilities;

import org.junit.Before;
import org.junit.jupiter.api.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVRecord;

import java.io.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.LinkedHashMap;
import java.util.List;

@RunWith(Parameterized.class)
public class JunitParameterizedRunner {

	@Parameters
	public static Collection getRecords(final String filename) throws IOException {
        Reader in = new InputStreamReader(new FileInputStream(new File(filename)));
        CSVParser csvParser = CSVParser.parse(in,CSVFormat.RFC4180.withFirstRecordAsHeader());
        Map<String, Integer> csvHeaderMapRaw = csvParser.getHeaderMap();
        HashMap<Integer, String> csvHeaderMapRawTailored = new HashMap<>();
        int counter = 0;
        for (String key : csvHeaderMapRaw.keySet()) {
        	System.out.println(key);
        	csvHeaderMapRawTailored.put(counter++,key);
        }
        Iterable<CSVRecord> records = csvParser.getRecords();
        LinkedHashMap<String, String> recordDataMap = new LinkedHashMap<>();
        LinkedHashMap<Long, Object> finalRecordDataMap = new LinkedHashMap<>();
        for (CSVRecord record : records) {
        	for(int valueIndex=0;valueIndex<csvHeaderMapRaw.size();valueIndex++){
        		recordDataMap.put(csvHeaderMapRawTailored.get(valueIndex), record.get(valueIndex));
        	}
        	finalRecordDataMap.put(record.getRecordNumber(), recordDataMap.clone());
        }
        List<Object> list = new ArrayList<Object>(finalRecordDataMap.values());
        System.out.println("The Records DataMap is: "+Arrays.asList(list));
        return Arrays.asList(list);
    }
	
	@Test
	public void dataStream() {
		try {
			String fileName = "C:\\testData.csv";
			getRecords(fileName).toString();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
}`

**Comment by kcooney** [comment]
> The getRecords() method will return the data only as a object row mappings and it is not appropriate to define some private property for this row data.

Why would that not be appropriate?

**Comment by Tibor17** [comment]
@kcooney 
I think I understand @dileepguntamadugu . We have exactly the same problem in our company.
We have parameterized test with a lots of data variations and they are so many that one row would not be readable because it would be too long. Complex logic must be then extracted to private methods but still it leads to overhead because you are creating extra method for each next run of the test and this method is composition, so it calls another methods which provide some data. The purpose of Parameterized was to get rid of writing more and more test methods but on the other side this construct with this annotation leads to Object[] array and again many methods defining the data itself.

**Comment by panchenko** [comment]
@dileepguntamadugu To be honest, it's not clear if your question is about using JUnit (which does not care about "private properties") or designing classes for the test data.

**Comment by dileepguntamadugu** [comment]
@kcooney - Say in one test I have 25 data fields and other test I have 80 fields which is true actually in my case, there are going to be several tests sometimes in hundreds.

It is gonna be like defining private properties for each such fields for each of the test. it will end up in so many, leaving it to imagination.

**Comment by Tibor17** [comment]
@dileepguntamadugu 
The only way how to solve this problem is to create several DataProvider classes, instantiate them within `@Parameters` method, inject the single instance in only one `@Parameter` and execute it within `@Before`.

**Comment by dileepguntamadugu** [comment]
@panchenko you mean it is possible for junit parameterized tests to be run without private properties?
Say, i have 100 rows of data with login name and password and i still don't need to define private properties as below?
private String loginName
private String password
