### ISSUE TITLE
Setting up a dynamic bootstrap classpath for test runners

### ISSUE THREAD

**Issue by realark** [junit-team/junit4#1564]
We have an unusual use case for Junit test runners.

The Datadog Java agent tests use `@RunWith` to allow us to test our bytecode instrumentation without spinning up a full Java Agent.

(Technically we're using spock, but we hook in at the Junit level to set everything up)

https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/testing/src/main/java/datadog/trace/agent/test/SpockRunner.java#L102

The process looks like this:

1. Test runner is initialized.
2. We append our core classes to the bootstrap loader (so we can test our bootstrap instrumentation).
  a. due to Java's classloading delegation, appended classes now load on the bootstrap loader
3. We set up bytebuddy to transform classes for the test.

This normally works well, but the problem happens when we try to run a single test method, it seems like some filtering happens before our test runner initializes. This filtering does some introspection+reflection on the test class. This can cause bootstrap classes to load too early (before we've set up the bootstrap classpath).

To work around this, we simply avoid referencing bootstrap classes in fields or method signatures. This works, but it would be nice if we didn't have to do this.

Is there any "lower-level" hook we can use to set up our bootstrap classes before our test class is potentially introspected? Any recommendations about how we can solve this kind of problem? I realize this is a pretty abnormal use-case.

**Comment by marcphilipp** [comment]
Does your `Runner` extend `ParentRunner` or implement `Filterable`? If so, that's were the filtering happens so you might need to override it and make sure you can initialize your runner first. The test class is loaded before calling `filter()`, though.

**Comment by realark** [comment]
I gave it a shot but no luck.

Upon taking a closer look, I think the hooks we need would actually have to come from the test launcher (idea junit launcher in our case). I think I'll follow up with them.

https://github.com/JetBrains/intellij-community/blob/master/plugins/junit_rt/src/com/intellij/junit4/JUnit4TestRunnerUtil.java#L316

Thanks for the answer!
