### ISSUE TITLE
I think someone Hacked the Documentation Page

### ISSUE THREAD

**Issue by dwkrueger2** [junit-team/junit4#1570]
It looks like someone inserted non-native links to the following github... The Download links don't appear direct and I don't know if they can be trusted.  

See Highlighted Areas
https://imgur.com/a/iVkxj3L

For Link
https://github.com/junit-team/junit4/wiki/Download-and-Install

**Comment by sormuras** [comment]
Have a look at the document's history, it didn't happen for the first time: https://github.com/junit-team/junit4/wiki/Download-and-Install/_history

It's a wiki - hacking is called "editing" there. Just restored the links to `seach.maven.org`.

**Comment by dwkrueger2** [comment]
I figured that it was edited... But that seems like a significant gratuitous edit.  And I don't know if the new link could be trusted. But what do I know?...
Thanks.

**Comment by marcphilipp** [comment]
Thanks for letting us know. I've restricted editing of wiki pages to users with push access for now.
