### ISSUE TITLE
Tests are marked as ignored when assertion in @AfterClass fails

### ISSUE THREAD

**Issue by CarlSalaets** [junit-team/junit4#1574]
I have a test class in which I have an assertion in the `@AfterClass` teardown method. (because I want to make sure I have at least one test case for every value of an enum)

I noticed that (at least in IntelliJ IDEA) if that teardown assertion fails, all other test are both marked as successful and marked as ignored. This is weird behaviour because the tests are not actually ignored, they were indeed run and were successful.

Correct behaviour would be: not mark those tests as ignored.

I'm using junit 4.12

**Comment by kcooney** [comment]
Possibly an IDEA bug.

If you run your tests in build tool like maven, does it report the test run as passing?

**Comment by CarlSalaets** [comment]
It seems you are correct.
Maven indicates only a single test failure and no skipped tests. This is the expected behaviour.
I was too quick to open a bug report here.

**Comment by CarlSalaets** [comment]
I created a bug at https://youtrack.jetbrains.com/issue/IDEA-203356
