### ISSUE TITLE
Failing openjdk-6 build

### ISSUE THREAD

**Issue by npathai** [junit-team/junit4#1577]
Travis Logs

`$ ~/bin/install-jdk.sh --target "/home/travis/openjdk6" --workspace "/home/travis/.cache/install-jdk" --feature "6" --license "GPL" --cacerts
install-jdk.sh 2018-10-17
Expected feature release number in range of 9 to 12, but got: 6
The command "~/bin/install-jdk.sh --target "/home/travis/openjdk6" --workspace "/home/travis/.cache/install-jdk" --feature "6" --license "GPL" --cacerts" failed and exited with 3 during .
`

**Comment by sormuras** [comment]
From where did you copy the logs?

**Comment by sormuras** [comment]
Perhaps related to https://travis-ci.community/t/the-travis-ci-build-could-not-be-completed-due-to-an-error/1345

**Comment by npathai** [comment]
@sormuras I faced the issue while working on Issue #1365 

https://travis-ci.org/junit-team/junit4/builds/466439917

**Comment by sormuras** [comment]
Thanks for the heads-up. It seems like "dist: trusty" is also affected...

Will notify @travis-ci / @banzaiman

**Comment by stefanbirkner** [comment]
FYI I have the same problem with System Rules since 6th Dec: https://travis-ci.org/stefanbirkner/system-rules/branches

**Comment by marcphilipp** [comment]
@sormuras Any news? Did Travis get back to you?

**Comment by sormuras** [comment]
Seems like it is _not_ working as intendend: https://travis-ci.community/t/the-travis-ci-build-could-not-be-completed-due-to-an-error/1345 -- as if legacy JDKs are no longer supported "out of the box".

**Comment by kcooney** [comment]
@sormuras Our `.travis.yml` doesn't specify trusty. Maybe it should? Or is trusty the default?

**Comment by sormuras** [comment]
**Trusty** is the default, afaik. But it now lacks JDK 6 support.
**Xenial** only comes with JDK 10 and 11 installed.

**Comment by marcphilipp** [comment]
It does use trusty but for some reason no longer installs the `open-jdk-6` package via apt. Previously it did install the package but did not change the used Java version. Thus, I've removed it in 9b34c4b6 for now.

**Comment by kcooney** [comment]
Could we configure Travis to use the older images for now? See https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch

**Comment by marcphilipp** [comment]
Maybe. I've sent a support request to Travis. Let's hope they'll get back with a solution.

**Comment by sormuras** [comment]
Also started a thread **_Java/JDK on Travis CI_** over here: https://travis-ci.community/t/java-jdk-on-travis-ci/1380

**Comment by kcooney** [comment]
Sorry, still recovering from the flu when I sent my last comment. That link in my comment was from 2017. 🙄
