### ISSUE TITLE
Color class can not be tested

### ISSUE THREAD

**Issue by salihaksit7** [junit-team/junit4#1588]
I can not test 'android.graphics.Color' class.
I have a function called 'getMyColor()'  which returns 

      Color.rgb(12,15,19)

When I am trying to test this function, the return of this 'getMyColor()' is always 0(Zero).

I tried this on Activity, and it works(returns other than 0).

My Gradle:

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

**Comment by marcphilipp** [comment]
@salihaksit7 This has very likely nothing to do with JUnit. You have a better chance to get a meaningful answer if you ask on StackOverflow.
