### ISSUE TITLE
Using Mockito Test case failed

### ISSUE THREAD

**Issue by Raj1071** [junit-team/junit4#1589]
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.835 sec <<< FAILURE! - in com.npst.mb.MbankingApplicationTest
testMpin(com.npst.mb.MbankingApplicationTest)  Time elapsed: 0.823 sec  <<< FAILURE!
java.lang.AssertionError: expected: com.npst.mb.pojo.ResponseData<ResponseData [tid=, statusCode=0,data={Msg=verified, statusCode=0}]> but was: com.npst.mb.pojo.ResponseData<ResponseData [tid=, statusCode=0,data={Msg=verified, statusCode=0}]>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.npst.mb.MbankingApplicationTest.testMpin(MbankingApplicationTest.java:93)

Results :

Failed tests: 
  MbankingApplicationTest.testMpin:93 expected: com.npst.mb.pojo.ResponseData<ResponseData [tid=, statusCode=0,data={Msg=verified, statusCode=0}]> but was: com.npst.mb.pojo.ResponseData<ResponseData [tid=, statusCode=0,data={Msg=verified, statusCode=0}]>

Tests run: 2, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.493 s
[INFO] Finished at: 2019-01-17T14:57:43+05:30
[INFO] Final Memory: 36M/346M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project CapexMbankingPhase2: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/npstx/raj/Canara Projects/MBS_APP_OMNI/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by Raj1071** [comment]
in above execution expected and but was response is same but still Test get failure..
Help me

**Comment by marcphilipp** [comment]
I'm afraid without the test source code, we can't help you. Moreover, this is not the place for seeking help with one's testing problems in general. You'll be much better of asking on StackOverflow. If you suspect an issue in JUnit, please open an issue and include a minimal reproducible sample project.

**Comment by Raj1071** [comment]
@marcphilipp thanx .. will post there also 

package com.npst.mb;

import static org.junit.Assert.*;
import static org.mockito.Mockito.when;

import java.util.HashMap;
import java.util.Map;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.runners.MockitoJUnitRunner;
import org.springframework.beans.factory.annotation.Autowired;

import com.npst.mb.canmb.dao.CanmbBaseDao;
import com.npst.mb.canmb.dao.CanmbTransactionDao;
import com.npst.mb.canmb.entity.Customer;
import com.npst.mb.canmb.entity.OMNIIntegration;
import com.npst.mb.canmb.entity.UserProfileMaster;
import com.npst.mb.canmb.service.CanmbTransactionServiceImpl;
import com.npst.mb.controller.OminiController;
import com.npst.mb.pojo.MBSOMNIIntegration;
import com.npst.mb.pojo.ResponseData;

@RunWith(MockitoJUnitRunner.class)
//Class<MockitoJUnitRunner> cannot be resolved to a type
//@SpringBootTest
public class MbankingApplicationTest {

	 @Mock
	 CanmbTransactionDao dataServiceMock;
	 
	 @Mock
	 CanmbBaseDao baseDao;
	 
	 @InjectMocks
	 CanmbTransactionServiceImpl businessImpl;
	    
	 @Autowired
	 OminiController controller;
	 
	 Customer customer;
	@Test
	public void test() {
		
		Customer cust= new Customer();
		cust.setMbnumber("+919990176197");
		cust.setDeviceid("abcdef");
		UserProfileMaster profile= new UserProfileMaster();
		profile.setChkflag(22);
		profile.setStatus("ACTIVE");
		cust.setUserProfile(profile);
		cust.setMpin("123456");
		cust.setMpinsalt("12345");
		when(dataServiceMock.getUserMbAndDevice("+919990176197", "abcdef")).thenReturn(cust);
		this.customer=cust;
	        assertEquals(cust, businessImpl.getUserMbAndDevice("+919990176197", "abcdef"));
	}

	@Test
	public void testMpin() {
		
		Customer cust= new Customer();
		cust.setMbnumber("+919990176197");
		cust.setDeviceid("abcdef");
		UserProfileMaster profile= new UserProfileMaster();
		profile.setChkflag(22);
		profile.setStatus("ACTIVE");
		cust.setUserProfile(profile);
		cust.setMpin("d150cb2c64171a95eb3fa1bbf2ea786aef16b04d389a1ac67a52c75e95f61e66");
		cust.setMpinsalt("12345");
		when(dataServiceMock.getUserMbAndDevice("+919990176197", "abcdef")).thenReturn(cust);
		
	        //assertEquals(cust, businessImpl.getUserMbAndDevice("+919990176197", "abcdef"));
	        
	        MBSOMNIIntegration reqData = new MBSOMNIIntegration();
	        reqData.setMbnumber("+919990176197");
	        reqData.setDeviceid("abcdef");
	        reqData.setMpin("123456");
	        
	        OMNIIntegration omni=new OMNIIntegration();
	        
	       // businessImpl.validateOmniMpin(reqData, omni, "123");
	        ResponseData data= new ResponseData();
	        Map<String,String> ominiMap= new HashMap<>();
	        ominiMap.put("Msg", "verified");
			ominiMap.put("statusCode", "0");
	        data.setStatusCode(0);
	        data.setTid("");
	        data.setData(ominiMap);
	       when(businessImpl.validateOmniMpin(reqData, omni, "123")).thenReturn(data);
	       assertEquals(data,businessImpl.validateOmniMpin(reqData, omni, "123"));
	        
	        
	}
	
}
