### ISSUE TITLE
Cucumber runtime exception with Junit plugin test

### ISSUE THREAD

**Issue by samkariash** [junit-team/junit4#1591]
Dear team

May be you can help. I am trying to run a cucumber test with Junit. It runs fine but when I want to run it as a junit plugin test ,then I get below exception.

cucumber.runtime.CucumberException: Expected a file URL:bundleresource://174.fwk1558712965:3/cucumber/runtime/
	at cucumber.runtime.io.Helpers.filePath(Helpers.java:19)
	at cucumber.runtime.io.FileResourceIteratorFactory.createIterator(FileResourceIteratorFactory.java:28)
	at cucumber.runtime.io.ZipThenFileResourceIteratorFactory.createIterator(ZipThenFileResourceIteratorFactory.java:23)

====================================================

import org.junit.runner.RunWith;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;

@RunWith(Cucumber.class)
@CucumberOptions( features={"resources"},
			glue= {"Steps"})
public class RunCucumberTest {

}
=======================================================
import org.junit.Test;

import cucumber.api.java.en.Given;

public class StepDefinitions {
	
	

	@Given("I want to write a step with precondition")
	public void myTest() throws Exception {
		
	System.out.println("Sample output");
	
	System.out.println("Sample output 2");
	}
	

}
Can you see if something is wrong
Thanks 
Shiva

**Comment by panchenko** [comment]
@samkariash Your question rather belongs to https://github.com/cucumber/cucumber-jvm, please try version 4.2.3
