### ISSUE TITLE
4.13 docs: Rule refers to deprecated RuleChain for order despite having order() property

### ISSUE THREAD

**Issue by TWiStErRob** [junit-team/junit4#1593]
Version: 4.13-beta2

`Rule` JavaDoc
> You can use a `{@link org.junit.rules.RuleChain}` if you want to have control over the order in which the Rules are applied.

`ClassRule` JavaDoc doesn't mention `order()`

It would be nice to have the same example as on `RuleChain` written on `Rule` and `ClassRule` using the `order()` property to ease migration of the deprecation.

**Comment by kcooney** [comment]
Could you send us a pull request fixing the Javadocs?

**Comment by marcphilipp** [comment]
@TWiStErRob @kcooney I've submitted a PR at #1594.

**Comment by TWiStErRob** [comment]
Nice, @marcphilipp, sorry I didn't get around to it.

**Comment by marcphilipp** [comment]
No worries, thanks for the quick review! 🙂
