### ISSUE TITLE
Getting error Could not initialize class sun.awt.X11.XToolkit while building in jenkins

### ISSUE THREAD

**Issue by Bkbest** [junit-team/junit4#1595]
Hi,
I need help here 
JUnit version 4.11
I have few test cases where on building the project in jenkins I am getting the following error:

[INFO] java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11.XToolkit
[INFO] 	at java.lang.Class.forName0(Native Method)
[INFO] 	at java.lang.Class.forName(Class.java:264)
[INFO] 	at java.awt.Toolkit$2.run(Toolkit.java:860)
[INFO] 	at java.awt.Toolkit$2.run(Toolkit.java:855)
[INFO] 	at java.security.AccessController.doPrivileged(Native Method)
[INFO] 	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
[INFO] 	at java.awt.Toolkit.getEventQueue(Toolkit.java:1734)
[INFO] 	at java.awt.EventQueue.isDispatchThread(EventQueue.java:1043)
[INFO] 	at javax.swing.SwingUtilities.isEventDispatchThread(SwingUtilities.java:1361)
.
.
.
org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
[INFO] 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
[INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
[INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Actually the same test cases executed with out any issues till now, however they started popping up recently. 
please help me in this issue.

Thanks,
Aravind

**Comment by sormuras** [comment]
Which version of Maven and which version of Surefire do you use? Did you change any of these recently?

**Comment by Bkbest** [comment]
Hi sormuras,
Thanks for very quick reply,
Maven version is 3.0.5
surefire version:  2.12.4
we did not make any changes to the test cases or to the maven or surefire version.

**Comment by sormuras** [comment]
Any change made to the Java version or flavor? Running in a container now? Headless mode?

**Comment by Bkbest** [comment]
No changes in java version, what do you mean by Headless mode?

**Comment by sormuras** [comment]
https://www.oracle.com/technetwork/articles/javase/headless-136834.html ... might not apply here.

> [INFO] java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11.XToolkit

Looks like class `sun.awt.X11.XToolkit` is present but its `static {...}` didn't complete. Is there any more detailed logging statement what went wrong there?

**Comment by panchenko** [comment]
As specified in the article, `-Djava.awt.headless=true` should be passed to java when running tests.
Most likely, jenkins runs in background without access to the computer display, but code under test is trying to use the related classes and that fails.

And the question is not related to JUnit :-)

**Comment by Bkbest** [comment]
@sormuras 
for some test cases I get 
Can't connect to X11 window server using 'localhost:11.0' as the value of the DISPLAY variable.

and for some test cases I get
Could not initialize class sun.awt.X11.XToolkit

this is one such exception for a test case

testDeleteIOI(com.mypackage.deletion.TestDelete)  Time elapsed: 0.004 sec  <<< ERROR!
[INFO] java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11.XToolkit
[INFO] 	at java.lang.Class.forName0(Native Method)
[INFO] 	at java.lang.Class.forName(Class.java:264)
[INFO] 	at java.awt.Toolkit$2.run(Toolkit.java:860)
[INFO] 	at java.awt.Toolkit$2.run(Toolkit.java:855)
[INFO] 	at java.security.AccessController.doPrivileged(Native Method)
[INFO] 	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
[INFO] 	at java.awt.Toolkit.getEventQueue(Toolkit.java:1734)
[INFO] 	at java.awt.EventQueue.isDispatchThread(EventQueue.java:1043)
[INFO] 	at javax.swing.SwingUtilities.isEventDispatchThread(SwingUtilities.java:1361)
[INFO] 	at com.mypackage.Collection.delete(Collection.java:478)
[INFO] 	at com.mypackage.deletion.DeleteHandler.delete(DeleteHandler.java:142)
[INFO] 	at com.mypackage.Delete.processDelete(Handler.java:132)
[INFO] 	at com.mypackage.Handler.delete(Handler.java:52)
[INFO] 	at com.mypackage.deletion.TestDelete.test(TestIOI.java:110)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
[INFO] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[INFO] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
[INFO] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[INFO] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[INFO] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[INFO] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
[INFO] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
[INFO] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
[INFO] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
[INFO] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
[INFO] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
[INFO] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
[INFO] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
[INFO] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[INFO] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
[INFO] 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
[INFO] 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
[INFO] 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
[INFO] 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
[INFO] 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
[INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
[INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by marcphilipp** [comment]
As @panchenko said, this question is not strictly related to JUnit. I think you'd be better of asking on StackOverflow. 🙂
