### ISSUE TITLE
Option to read retrieve parameters per test in Junit4

### ISSUE THREAD

**Issue by pavanbachu06** [junit-team/junit4#1598]
able to read the test data from the JSON file for each test case using @paramter tag and run the test cases per parameter parallelly. Able to run the test case per parameter parallel using Parallel-Computer. Need help to figure out a way to read the parameter from JSON

**Comment by kcooney** [comment]
JUnit has support for running tests in parallel, as do some of the plugins for the various build tools. It's hard to make recommendations without knowing more about your environment (how you build and run tests, etc).

Reading JSON data is outside of the scope of JUnit

I suggest asking on stackoverflow.com. See https://stackoverflow.com/help/how-to-ask for how to ask a good question there. Feel free to add a link to the question you ask on this bug.

Good luck!
