### ISSUE TITLE
Make Statement an interface instead of an abstract class

### ISSUE THREAD

**Issue by CarlSalaets** [junit-team/junit4#1606]
`org.junit.runners.model.Statement` is currently an abstract class with a single method.
Why is this not an interface so we could take advantage of the Java 8 lambda syntactic sugar?

Implementing a TestRule would become simpler:
```java
public class ExampleTestRule implements TestRule {
	@Override
	public Statement apply(Statement base, Description description) {
		return () -> {
			// ...
			base.evaluate();
			// ...
		}
	}
}
```

**Comment by kcooney** [comment]
The class predates Java 7.

Unfortunately, we can't change it to an interface without breaking users.
