### ISSUE TITLE
Provide a `CompositeTestRule`

### ISSUE THREAD

**Issue by vRallev** [junit-team/junit4#1614]
`RuleChain` has been deprecated in version 4.13 and the replacement is to use the order attribute in the `@Rule` annotation. But `RuleChain` also served as a composite test rule and there is no replacement for that. Let's say I have a method like this:
```java
public TestRule myRules() { .. }
```
Previously I was returning a `RuleChain`, that combined multiple rules. There is no replacement for this purpose.

Yes, it would be easy to create my own test rule. But I feel like there should be something available in the framework. I don't know how much it would differ from `RuleChain`, though.

**Comment by panchenko** [comment]
@vRallev Could you please elaborate more on the use case?

**Comment by vRallev** [comment]
Many of our tests require a specific set of test rules. Instead of having a base class, we provide the functionality through test rules. To avoid repeating the `RuleChain` in every class, we've extracted the setup into a factory method. In this specific case the test would look like this:
```java
public class MyTest {

  @Rule public TestRule rules = myRules();

  // other rules

  // tests
}
```
The factory method looked similar to this:
```java
public TestRule myRules() {
  return RuleChain.outerRule(..).around(..)...;
}
```
The order of the rule chain matters to us. 

I was looking for a replacement for `RuleChain` that allows me to combine multiple rules. I still believe `RuleChain` has a valid purpose.

**Comment by marcphilipp** [comment]
@junit-team/junit-committers WDYT?

**Comment by stefanbirkner** [comment]
I'm in favour for removing the deprecation from RuleChain. I also use it for combining rules into a single one. I was just not sure whether this is a more common use case or it was only me because I built RuleChain.

**Comment by marcphilipp** [comment]
I have also used it like that in the past. +1 on undeprecating it.

@vRallev Would you be interested in submitting a PR?

**Comment by vRallev** [comment]
Yes, starting in a minute.

**Comment by vRallev** [comment]
Done #1615
