### ISSUE TITLE
AssumeFalse description : "got" and "expected" are inverted

### ISSUE THREAD

**Issue by LeGritche** [junit-team/junit4#1616]
The description of Assume.assumeFalse is wrong.

Running the test :
`assumeFalse(true);`

give the description :
`org.junit.AssumptionViolatedException: got: <false>, expected: is <true>`

instead of 
`org.junit.AssumptionViolatedException: got: <true>, expected: is <false>`

I think the implementation of assumeFalse should be :
`Assume.assumeThat(b, CoreMatchers.is(false));`

**Comment by marcphilipp** [comment]
Indeed! 😳

@LeGritche Would you be interested in submitting a PR?

**Comment by Oxilod** [comment]
Here is the change requested if I understood the issue correctly: https://github.com/junit-team/junit4/pull/1620
