### ISSUE TITLE
Unrooted tests with custom test runner

### ISSUE THREAD

**Issue by magwas** [junit-team/junit4#1618]
I am writing a framework which generates both test cases and stubs from contract information.
To make life easier, I would like to use the already existing framework of Junit for running the tests.

So I have introduced the @Contract annotation instead of @Test and trying to write a runner.
The runner is running fine, but Eclipse reports all the contracts as unrooted tests.

What conditions should I satisfy to make those contracts appear as if they were normal junit testcases?

Here is an example contract as context:

```
@RunWith(ContractRunner.class)
public class ContractTest {

  @InjectMocks
  BeatTableServiceImpl beatTableService;

  @Contract("a contract with return definition")
  public void contract_one(
      final TestData testData,
      final ContractInfo<BeatTableServiceImpl> contract
  ) {

    contract.returns(
        testData.beatTableData.beatTableComplex
    )
        .initializeBeatTable(testData.castVoteData.castVoteList);
  }

  @Contract("a contract with exception definition")
  public void contract2(
      final TestData testData,
      final ContractInfo<BeatTableServiceImpl> contract
  ) {

    contract.throwing(
        ReportedException.class,
        "Invalid castVotes"
    )
        .initializeBeatTable(null);

  }

}

```

**Comment by marcphilipp** [comment]
@magwas Can you share the implementation of your runner? Which class does it extend?

**Comment by magwasada** [comment]
The contract runner is here : https://github.com/magwas/PDEngine/blob/feature/refactor_to_services/src/test/java/org/rulez/demokracia/pdengine/contract/ContractRunner.java
It extends Runner.
All the parts of the solution are in the same folder.

**Comment by marcphilipp** [comment]
You should really extend `ParentRunner`. It would force you to implement `getChildren()` (to return your contracts) and `describeChild()` to generate a `Description` for each child. The missing condition that you need to satisfy is to add the test `Descriptions` as children of the `Description` returned by `getDescription()`.
