### ISSUE TITLE
Exclude all categories in failsafe

### ISSUE THREAD

**Issue by noviceamateur** [junit-team/junit4#1623]
I want to exclude those test classes which have ALL the categories mentioned in the section of the failsafe configuration.

Presently, I believe it excludes all test classes which have any one of the categories mentioned in the configuration.

    <excludeGroups> Group1, Group2 </excludeGroups>

@Categories(Group1.class)
public class SampleTest {
}

I want SampleTest to run with the mentioned configuration, but it is NOT running.

Junit version - 4.12

**Comment by Tibor17** [comment]
You mean the POM?
You have used
`excludedGroups` or
`excludeGroups` including the package (fully qualified class name)?

**Comment by noviceamateur** [comment]
I used `<excludeGroups>` and fully qualified class names. 
My assumption is that it should do a AND of the groups mentioned.

**Comment by Tibor17** [comment]
@noviceamateur 
Did you see the documentation?
http://maven.apache.org/surefire/maven-failsafe-plugin/integration-test-mojo.html#excludedGroups
http://maven.apache.org/surefire/maven-failsafe-plugin/examples/inclusion-exclusion.html

**Comment by Tibor17** [comment]
The Surefire and Failsafe do not perform any logic like AND. This logic can be in provider. In this case JUnit but again the feature has to be described in JUnit documentaion.

**Comment by noviceamateur** [comment]
So  the failsafe plugin is excluding the tests  if it has any one of the groups mentioned in the `<excludedGroups>` . 

But I want to exclude test cases only if they have ALL the groups mentioned in the tag.

Would this be a ask for failsafe plugin or junit ?

**Comment by Tibor17** [comment]
Surefire and Failsafe only `deliver your setting` to junit instance. What the junit does is up to the junit.
I think this works with OR.
If you want to have AND, you may want to introduce a new group `C` which inherits `A` and `B`.
Just a guess.

**Comment by noviceamateur** [comment]
So junit performs the logic of deciding whether to run a test or not depending on the settings supplied to it by failsafe right ?

Can this be taken up as a feature request ?

**Comment by Tibor17** [comment]
@noviceamateur I am responsible only for the Failsafe/Surefire where i made a correctnees due to you have made a typo with `excludGroups`.
You can ask junit committers with junit related questions.
ok, hoping this helps.

**Comment by noviceamateur** [comment]
`<excludedGroups>` is the correct tag right ? `<excludeGroups>` is incorrect ?

**Comment by Tibor17** [comment]
@noviceamateur 
Several years ago I developed `matchAny` in inclusion/exclusion annotation, see the Javadoc:
https://junit.org/junit4/javadoc/4.12/org/junit/experimental/categories/Categories.IncludeCategory.html
This is related to `Suite` runner. Slightly different from your usecase. Can you use the Suite instead?

**Comment by Tibor17** [comment]
`excludedGroups` is correct one.

**Comment by noviceamateur** [comment]
I will take a look at it. Thank @Tibor17 . Much appreciated

**Comment by marcphilipp** [comment]
Closing because JUnit already provides that feature and Surefire uses its own Filter to include/exclude tests based on categories.
