### ISSUE TITLE
Assert should have fail(Throwable) and fail(String, Throwable) API.

### ISSUE THREAD

**Issue by HamletDRC** [junit-team/junit4#164]
It would be nice if Assert had a fail(Throwable) and fail(String, Throwable) API.

There are often times where a fail() method call is appropriate. If you call JUnit's fail() or fail(String) there is no way to also include a stack trace. fail(Throwable) and fail(String, Throwable) would provide an API to fail a test without swallowing a stack trace.

I personally have need of this feature. I find many codebases that call fail() explicitly for readability but then swallow the stack trace. Having this API would be nice. 

I am happy to write a patch for this, but I need some answers first. 
1. AssertionFailedError extends AssertionError, which does not have a (String, Exception) constructor. It only has a constructor for each primitive and (Object). The Object constructor correctly sets the cause if the Object is a throwable, so we can delegate to this constuctor to make sure that the stack trace is reported. Is this an acceptable implementation detail? 
2. How to implement the (String, Throwable) overloading... we can construct an AssertionFailedError with the String message, and then call error.setStackTrace explicitly with the stack trace from the user exception. Is this acceptable? 

Thanks, Hamlet

**Comment by RahulNagekar** [comment]
My case is like following, I want to fail if any exception occurs.
```
    @Test
    public void myTest() {
        try {
            someMethod();
        } catch (ExceptionType ex) {
           fail("No exception should be thrown",ex);   //proposed api
        }
    }  
```
As, failure is an assert failure I cant throw a excpetion after it.
But, I will need the tracktrace incase of failure to trace the root cause.

My current workaround to this is :
```
catch (ExceptionType ex) {
            ex.printStackTrace(System.err);
            fail("No exception should be thrown");
        }

```

**Comment by kcooney** [comment]
@RahulNagekar have you tried `assertThrows()`?
