### ISSUE TITLE
Warn on mixed JUnit 3/4 tests

### ISSUE THREAD

**Issue by kriegfrj** [junit-team/junit4#1642]
I reported this issue in junit-team/junit5#1964, but perhaps should have reported it here. I didn't realise that there was still active development on JUnit 4.

If the JUnit 4 runner encounters a class that extends `TestCase` *and* has `@Test` annotations in it, then it will silently ignore all of the JUnit 4 tests. It would be good if it were not so silent about it, as it could lull people into a false sense of security that all their tests are passing, when actually some are simply not running at all.

Ideal solution: runner should run both sets of tests.
Acceptable solution: runner should check for this situation and generate an error or warning if it is found.

**Comment by marcphilipp** [comment]
Just to set expectations, "active development" is a bit of an overstatement. 😉

**Comment by kriegfrj** [comment]
Well, I wasn't expecting there to be a 4.13 release, so the current level of activity is infinitely greater than I had supposed. :smile:

**Comment by marcphilipp** [comment]
Fair enough. 😅

**Comment by kcooney** [comment]
There's an ErrorProne check for this. See https://errorprone.info/bugpattern/JUnit3TestNotRun
