### ISSUE TITLE
SpringBoot Custom.properties file unable to resolve placeholder property error in junit

### ISSUE THREAD

**Issue by BilgehanYildiz** [junit-team/junit4#1644]
Hi I want to use junit to test my spring boot application.In my application It is working without problem but when I want to use unit test ,that time I got compilation error.My junit version is 4.12.

Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'my.property' in value "${my.property}my.properties" at org.springframework.util.PropertyPlaceholderHelper.parseStringValue

I tried different combination but no luck?
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest(classes = MyApplication.class)
@WebAppConfiguration
@ContextConfiguration(classes = {MyTestConfig.class})
@EnableAutoConfiguration
public class MyTest {

**Comment by marcphilipp** [comment]
That's not an issue in JUnit core but most likely in your setup. I think StackOverflow would be your best bet in getting help.
