### ISSUE TITLE
Deprecation of Assert#assertThat missing in 4.13 release notes

### ISSUE THREAD

**Issue by sratz** [junit-team/junit4#1645]
The deprecation of Assert#assertThat in 4.13 is missing in the release notes and came as a surprise, seeing thousands and thousands of warnings in our code base.

This should be added to the release notes.

Maybe it should even be re-considered. The import pattern usually looks like
```
...
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertThat;
import static org.junit.Assert.assertTrue;
...
```

and org.junit.Assert.* is usually a place IDEs's code completions look for methods to be imported statically. This symmetry and convenience is now kind of broken.

**Comment by marcphilipp** [comment]
@sratz You're right, it should be mentioned in the release notes.

@stefanbirkner Do you have time to add it?

The rationale for deprecating it was that there are other assertion libraries, e.g. AssertJ, so users should make a conscious decision which to use. Moreover, using the method in Hamcrest provides an upgrade path to future versions of Hamcrest that might contain bug fixes or improvements.

**Comment by marcphilipp** [comment]
@stefanbirkner Thanks!
