### ISSUE TITLE
Update the wiki with "assertThrows"

### ISSUE THREAD

**Issue by LorenzoBettini** [junit-team/junit4#1647]
I think this wiki page https://github.com/junit-team/junit4/wiki/Exception-testing should be updated to mention also the new `assertThrows` method.

**Comment by sormuras** [comment]
It's a wiki page. Hit the **Edit** button. 😉 

![image](https://user-images.githubusercontent.com/2319838/73765371-bc59c680-4774-11ea-8687-2ff651c73cc1.png)

**Comment by LorenzoBettini** [comment]
@sormuras I would do that with pleasure, but I see no such buttons :)

**Comment by sormuras** [comment]
🤔

Mh, so ... maybe there's a restriction in place that I'm not aware of.

What text would you add on the page? I'll copy it over for you then.

**Comment by marcphilipp** [comment]
Yes, we had spam issues a while ago and had to restrict editing to users with push access.

**Comment by LorenzoBettini** [comment]
I'll put the text I'd like to propose in this issue ASAP

**Comment by LorenzoBettini** [comment]
### Using `assertThrows` Method

The method `assertThrows` has been added to the `Assert` class in version 4.13. With this method you can assert that a given function call (specified, for instance, as a lambda expression or method reference) results in a particular type of exception being thrown. In addition it returns the exception that was thrown, so that further assertions can be made (e.g. to verify that the message and cause are correct). Furthermore, you can make assertions on the state of a domain object after the exception has been thrown:

```java
@Test
public void testExceptionAndState() {
	List<Object> list = new ArrayList<>();

	IndexOutOfBoundsException thrown = Assert.assertThrows(IndexOutOfBoundsException.class,
			() -> list.add(1, new Object()));
	// assertions on the thrown exception
	Assert.assertEquals("Index: 1, Size: 0", thrown.getMessage());
	// assertions on the state of a domain object after the exception has been thrown
	Assert.assertTrue(list.isEmpty());
}
```

**Comment by LorenzoBettini** [comment]
@sormuras I added the Markdown content I'd like to add.
By the way, https://github.com/junit-team/junit4/pull/1633 also deprecated `ExpectedException.none()`, do you think it's worthwhile to add a note in the wiki page about that as well?

**Comment by marcphilipp** [comment]
@LorenzoBettini Thanks! I added a new section and a short note about `ExpectedException` now being deprecated.

**Comment by kcooney** [comment]
I moved the section about assertThrows() higher up on that wiki page, since that is our current recommended way for testing exceptions. I also added a note that explains why ExpectedExcetpion is deprecated.
