### ISSUE TITLE
JUnit 4 support status

### ISSUE THREAD

**Issue by medb** [junit-team/junit4#1650]
What the status of JUnit 4? Is it effectively deprecated/not supported any more, because of JUnit 5 release?

**Comment by kcooney** [comment]
We released JUnit 4.13 on January 1st (see https://twitter.com/junitteam/status/1212403812192964608).

Newer projects should use JUnit 5 and write tests using JUnit Jupiter (see https://junit.org/junit5/docs/current/user-guide/#overview-what-is-junit-5). JUnit5 can run JUnit4-style tests using the JUnit Vintage test engine (see https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4).

**Comment by marcphilipp** [comment]
That being said, if there's a critical bug in JUnit 4 we would certainly fix it and ship a patch release.
