### ISSUE TITLE
Temporary Folder not being deleted 

### ISSUE THREAD

**Issue by NedK123** [junit-team/junit4#1658]
Hello
I'm not sure if this is a bug in JUnit or no, so feel to correct me if I'm wrong

I'm using a temporary folder in my unit test using the @Rule of JUnit.
The folder is not being deleted after the tests finish

Java version : 1.8

JUnit version: 4.12

Os windows 10

I'm creating a file.csv under a temp folder in order to edit it using CSVPrinter from org.apache.commons

```
public class MyService {

public void createCSVFile(String basePath) {
        try (FileWriter out = new FileWriter(format("%s/file.csv", basePath));
             CSVPrinter printer = new CSVPrinter(out, CSVFormat.DEFAULT.withHeader(HEADERS))) {
            //printer.PrintRecord(args);
        } catch (IOException e) {
            log.error("Failed to create file.csv under " + basePath, e);
        }
    }
}
```

The test:

```
    @Rule
    public TemporaryFolder folder = new TemporaryFolder();
    private String folderPath;
    private MyService myService;

    @Before
    public void setup() throws IOException {
        folder.newFile("file.csv");
        folderPath = folder.getRoot().getPath();
    }
 
    @Test
    public void testing_myService() {
        myService.createCSVFile(folderPath);
        //Assert 
    }
```

When i open the folder ex: *C:\Users\me\AppData\Local\Temp\junit2290989758736528709*
I can still see the file.csv as it was not deleted

I tried to migrate the create of the file to become in the tests. It did not fix it
```
    @Test
    public void testing_myService() {
        folder.newFile("file.csv");
        myService.createCSVFile(folder.getRoot().getPath());
        //Assert 
    }

```

I added an @After method to delete the folder 
```
    @After
    public void cleanup() throws IOException {
        //Tried several ways to delete the folder and file as well
        //FileUtils.forceDelete(folder.getRoot().getAbsoluteFile());
        //folder.getRoot().delete();
        //FileUtils.deleteDirectory(folder.getRoot());
        //new File(folderPath +"/file.csv").delete();

        //All methods did not delete neither the direcotry (with exception can't delete file.csv) nor deleted the file.csv
    }
```

I also tried to call the `folder.create();` and `folder.delete();` myself without using the @Rule
But the folder wasn't deleted as well

The file.csv and folder are marked as **read-only** when viewing the properties on windows

I tried to change that in the code 
```
folder.setWritable(true);
folder.setReadable(true);
folder.setExecutable(true);
```
Didn't manage to delete the folder as well

My aim is to find a solution that works for any environment where the code is checked out ex: CI pipeline on a linux server and on windows

any other reason for this behavior?

can you please advise

**Comment by kcooney** [comment]
I wonder if some code is holding a file handle, preventing the temporary directory from being deleted.

I suggest:

```
@Rule
public final TemporaryFolder folder = TemporaryFolder.builder()
    .assureDeletion()
    .build();
```

That should cause `TemporaryFolder` to throw an exception if it could not delete the folder.

**Comment by NedK123** [comment]
Indeed it was
A file reader wasn't being properly closed

can you please this same question on stackoverflow? @kcooney  
[question](https://stackoverflow.com/questions/60857085/temporaryfolder-not-being-deleted-using-junit-rule)
Thank you

**Comment by kcooney** [comment]
> can you please answer this same question on stackoverflow?

@NedK123 Done.
