### ISSUE TITLE
GPG signing key changed, but not documented?

### ISSUE THREAD

**Issue by rgurley** [junit-team/junit4#1659]
The signing key for junit:junit changed from 0xEFE8086F9E93774E to 0x85911F425EC61B51, but this change was not documented in release notes for 4.13.

**Comment by marcphilipp** [comment]
You're right, I used a different signing key for the 4.13 release. I documented it now and added `KEYS` file to the repo in 50a285d3ce69b4556ac46d8633f6beb4527b4679.
