### ISSUE TITLE
java.lang.NoClassDefFoundError: org/junit/runner/manipulation/Filter

### ISSUE THREAD

**Issue by blankman23** [junit-team/junit4#1661]
I am trying to make a new test case for one of my classes using junit. I am not sure which junit to use 4 or 5 because I keep having this issue occur.
here is a picture of my build path. and the one below is the error code along with the code i am currently writing. 
![image](https://user-images.githubusercontent.com/64275535/80236258-e52d8180-8628-11ea-9736-fa505cb92afd.png)

![image](https://user-images.githubusercontent.com/64275535/80236164-c3cc9580-8628-11ea-91d8-0d8b30399920.png)

**Comment by kcooney** [comment]
I see junit-4.10.jar (which is a very old version of JUnit) and a "JUnit 4" folder in your classpath. My guess is you don't need both. You should also use a more recent version of JUnit.

Questions like this should be asked on stackoverflow.com
