### ISSUE TITLE
GitHub Wiki has broken links to Release Notes

### ISSUE THREAD

**Issue by Mike4Online** [junit-team/junit4#1664]
Release notes for JUnit 4.13 are currently at [https://github.com/junit-team/junit4/blob/main/doc/ReleaseNotes4.13.md](https://github.com/junit-team/junit4/blob/main/doc/ReleaseNotes4.13.md)

However, links to these release notes in the JUnit 4 Wiki at [https://github.com/junit-team/junit4/wiki](https://github.com/junit-team/junit4/wiki) currently point to [https://github.com/junit-team/junit/blob/master/doc/ReleaseNotes4.13.md](https://github.com/junit-team/junit/blob/master/doc/ReleaseNotes4.13.md), which gives a 404 error.  This invalid link is referenced in several other pages on the internet, so ideally these ../blob/master/doc... links would be made valid.

Corresponding Release Notes links for other versions of JUnit 4 also have this issue.

**Comment by marcphilipp** [comment]
Thanks for raising the issue. I fixed all the links I could find in the wiki.
