### ISSUE TITLE
All release notes links are broken on junit4.org (they point to "master" branch)

### ISSUE THREAD

**Issue by dimsuz** [junit-team/junit4#1666]
All links under `Release Notes` on the https://junit.org/junit4/ are 404.

![Screenshot_2020-06-29 JUnit – About](https://user-images.githubusercontent.com/42920/86024327-237e5d00-ba2d-11ea-914b-5e2b6a380201.png)

**Comment by vlsi** [comment]
The same happens for GitHub Releases: https://github.com/junit-team/junit4/releases

**Comment by marcphilipp** [comment]
Thanks for reporting! I fixed the releases page and will fix the website now.

**Comment by marcphilipp** [comment]
Fixed.
