### ISSUE TITLE
Maven surefire plugin  generating empty testng report 

### ISSUE THREAD

**Issue by Shantha93** [junit-team/junit4#1667]
I have a simple selenium project built using testng and maven. When i trigger my testng xml suite from eclipse (which uses its own testng plugin) i have the testng report created every time.  
I want to run this project from command line through maven for CI/CD integration and hence i am trying to run as "mvn test", with surefire plugin added to my POM. This works fine for 2-3 classes in my suite, but when ever i try to run a bulk of 6-10 classes in the regression xml suite, through "mvn clean test", the execution is getting completed, with BUILD SUCCESS, but there is only empty testng index.html in the surefire reports.

Please help me handle this issue and have a consistent report generated for all my bulk executions.

**Comment by kcooney** [comment]
@Shantha93 the JUnit team does not maintain the maven surefire plugin. It looks like issues for Surefire can be [reported here](https://maven.apache.org/surefire/maven-surefire-plugin/issue-management.html), but you may want to start with their [user mailing list](https://maven.apache.org/surefire/maven-surefire-plugin/mailing-lists.html).

**Comment by Tibor17** [comment]
I think you must have wrong config in surefire. You cannot run suite and
classes altogether. Post your project on Github and involve the TestNG team
in discussion. Mostly it is a user problem, see the www.stackoverflow.com,
but dont ask these junit guys, they will not help you.

Dňa pi 3. 7. 2020, 15:23 Shantha93 <notifications@github.com> napísal(a):
