### ISSUE TITLE
release 4.13.1 links to release note 4.13

### ISSUE THREAD

**Issue by THausherr** [junit-team/junit4#1675]
Here on github in the "releases" part, JUnit 4.13.1 links to 
https://github.com/junit-team/junit/blob/HEAD/doc/ReleaseNotes4.13.md
but should link to
https://github.com/junit-team/junit/blob/HEAD/doc/ReleaseNotes4.13.1.md

**Comment by marcphilipp** [comment]
Thanks for reporting! Fixed now.
