### ISSUE TITLE
Option to create TemporaryFolder that doesn't limit access to created files

### ISSUE THREAD

**Issue by bradyoo** [junit-team/junit4#1679]
After the fix for https://github.com/junit-team/junit4/security/advisories/GHSA-269g-pwp5-87pp, the test I have had that creates temp files with multiple users need access broke.

I am wondering if there can be an option to create a TemporaryFolder without the limited access if I'm not worried about the information disclosure vulnerability.

**Comment by panchenko** [comment]
I would recommend explicitly setting the desired permissions, as this is quite a special case.
Long term that would simplify migrating to JUnit 5.

**Comment by kcooney** [comment]
I agree with Marc. If you need this functionality you could create your own rule that extends `ExternalResource`
