### ISSUE TITLE
Junit 4 life cycle support 

### ISSUE THREAD

**Issue by soso2704** [junit-team/junit4#1695]
I am not finding any information on Junit 4 end of life since Junit 5 Jupiter is out. 

Is there long term support on the latest version of Junit 4 planned?

**Comment by marcphilipp** [comment]
Even though new features are only added to JUnit Platform and Jupiter (currently known as JUnit 5), given the widespread use of JUnit 4, we will continue to fix critical bugs, in particular security-related ones, for the time being.
