### ISSUE TITLE
Issue in Mocking Java Comparator - For Open JDK 1.8

### ISSUE THREAD

**Issue by PriyankaKeer** [junit-team/junit4#1704]
Hi Team,

We are facing issue while mocking Comparator using Mockito.
While using below VM argument, we were able to mock the comparator - For JDK 1.8 but the same is failing in Open JDK 1.8.
**-Djava.util.Arrays.useLegacyMergeSort=true**
Please Suggest on this.

Thanks in Advance!

**Comment by marcphilipp** [comment]
This is unrelated to JUnit. Please open an issue for Mockito.
