### ISSUE TITLE
Confusing problem... get differernt result between `main method` and `test method`

### ISSUE THREAD

**Issue by Gakiii** [junit-team/junit4#1738]
when I run such code in a `main method` I got the result like this
Main.java
```java
public class Main {
    public static void main(String[] args) {
        String s = String.valueOf(1);
        s.intern();
        String s2 = "1";
        System.out.println(s == s2); // true
    }
}
```
but I run it with junit like this
StringTest.java
```java
public class StringTest {
    @Test
    public void Test1() {
        String s = String.valueOf(1);
        s.intern();
        String s2 = "1";
        System.out.println(s == s2); //false
    }
}
```
chips : Apple M1
OS : Mac Monterey 12.3.1
jdk verison: 
```
❯ java -version
openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment Zulu11.45+27-CA (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.45+27-CA (build 11.0.10+9-LTS, mixed mode)
```
junit verison: 4.13.2

**Comment by panchenko** [comment]
There is a bug in your code, the proper way to write it is  `s = s.intern();`

**Comment by Gakiii** [comment]
> r code, the proper way to write it is `s = s.intern();`

I have a guess, when I run this code with junit, the String constant pool already has a "1"(like jdk8+ the "java" is already created by the jvm).
 so in the code in junit, the code `s.intern()` actually do nothing.
so `s == s2` is flase.
That the only reason I can explain this.
@panchenko

**Comment by panchenko** [comment]
@Gakiii Actually I cannot explain how you get `true`.

"1" is always in the pool., as the constants are interned:

     * All literal strings and string-valued constant expressions are
     * interned. String literals are defined in section {@jls 3.10.5} of the
     * <cite>The Java Language Specification</cite>.

However I am not aware of `String.valueOf(int)` returning interned strings and I don't see that in the sources.

**Comment by Gakiii** [comment]
> @Gakiii Actually I cannot explain how you get `true`.

@panchenko 
emmmmm, I'm really confused
You can try it. 
And I'm sure you will get `true` like me.
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/42515562/166086304-e1da602a-cd65-455d-a230-b0599018fb58.png">

**Comment by Gakiii** [comment]
@panchenko 
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/42515562/166086347-3fcd7cb7-a5c1-4f3b-99af-c670b55fecc1.png">
when I don't use `s.intern()` the result is `false`
😟

**Comment by marcphilipp** [comment]
I think the difference is that the `main` method is `static` so the compiler seems to be generating an interned constant for your string whereas it doesn't do that for the non-static test method. If you're code relies on interning, you should make sure to call `intern()`. I think you'd get the same result if you moved your code to a static method that's called from `main()` and your test method.
