### ISSUE TITLE
Refactoring Confirmation for Replace ‘expected’ Attribute with Try-Catch

### ISSUE THREAD

**Issue by larjean89** [junit-team/junit4#1777]
Greetings,
I have a question regarding a refactoring on this [commit](https://github.com/junit-team/junit4/commit/df016dc056ab15dfa7a6c448ef1905b27eff877f) from line 79 to 88

@marcphilipp @alb-i986 did you conduct the following refactoring?

**Replace ‘expected’ attribute with try-catch** This refactoring involves substituting the use of an ‘expected’ attribute for exception handling with a try-catch block for more explicit error management.

Code snippet
```java
-@Test(expected = AssumptionViolatedException.class)
   + @Test
    public void assumeThatWorks() {
        -assumeThat(1, is(2));
       + try {
            +assumeThat(1, is(2));
            +fail("should throw AssumptionViolatedException");
      +  } catch (AssumptionViolatedException e) {
            // expected
        +}
   + }
```
Thanks and looking forward to hearing from you.

**Comment by marcphilipp** [comment]
@larjean89 What's your reason for asking?

**Comment by snicoll** [comment]
FTR, this is likely to be created by a bot. The "OP" created something similar in https://github.com/spring-projects/spring-framework/issues/33329

**Comment by larjean89** [comment]
@marcphilipp thank you for your prompt response. I am currently conducting research on various refactoring techniques and their impacts on software development. So, i am in the process of manual checking and confirmation of some refactorings.

**Comment by larjean89** [comment]
I am conducting some research on various refactorings. I'm sorry if I posted the question on the wrong platform. Can I be guided on the best route i can take to ask such questions?

Regards
________________________________

**Comment by marcphilipp** [comment]
Yes, the commit authors obviously conducted the refactoring. Was that your full question?
