### ISSUE TITLE
introduce @Fail annotation for test methods that must fail

### ISSUE THREAD

**Issue by SebastianDietrich** [junit-team/junit4#183]
Sometimes it is necessary to check if a given test fails. e.g. when a functionality should only work under given circumstances e.g. running against different backend systems, some of them up, some down and you want your test to run through / fail accordingly.

--> introduce an annotation that marks a test-method as "must fail"

This could even be enhanced with an additional parameter "@Fail (when = myCondition)" to represent conditions (returning true/false) under which the test must fail/succeed

**Comment by simonezampinistud** [comment]
I need it...

**Comment by kcooney** [comment]
@simonezampinistud could you describe how `Assume`, `@Ignore` and `assertThrows()` don't meet your needs?

**Comment by simonezampinistud** [comment]
I have to test a "test framework". I have to test a method which contains itself a call to "fail()".

**Comment by panchenko** [comment]
@simonezampinistud Something like the following. Copied from https://github.com/junit-team/junit4/blob/master/src/test/java/org/junit/tests/assertion/AssertionTest.java
```java
try {
        Assert.fail("woops!");
} catch (AssertionError exception) {
        assertEquals("java.lang.AssertionError: woops!", exception.toString());
        return;
}
throw new AssertionError(ASSERTION_ERROR_EXPECTED);
```

**Comment by kcooney** [comment]
@simonezampinistud if you can use Java 8 or greater, I highly recommend `org.junit.Assert.assertThrows`

```
assertThrows(AssertionError.class, () -> Assert.fail("woops"));
```

The `assertThrows` method returns the exception thrown by the lambda, so you can make assertions on it. For example, if you use [Truth](https://google.github.io/truth/), you can do this:

```
AssertionError expected = assertThrows(
    AssertionError.class, () -> Assert.fail("woops"));

assertThat(expected).hasMessageThat().contains("woops");
```
