### ISSUE TITLE
Junit should be an osgi bundle

### ISSUE THREAD

**Issue by cschneider** [junit-team/junit4#212]
I sometimes use junit assertions even in production code to make sure no invalid data slips through. As some of my applications run under osgi it would be very handy if junit already was a valid osgi bundle. 

As far as I can tell it would only be necessary to switch the to packaging in the pom to bundle and add the maven bundle pllugin. I can provide a patch if that helps.

Christian

**Comment by sarod** [comment]
Any progress on this issue?

**Comment by jtulach** [comment]
My change https://github.com/junit-team/junit/pull/1262/commits/02756b208241a7adcc4ecfce5a2188d81010d1b5 is likely to address the needs stated in this issue.

**Comment by kcooney** [comment]
Closing this. See #905 for rationale
