### ISSUE TITLE
error using JUnit4TestAdapter with class which has no test methods

### ISSUE THREAD

**Issue by orionll** [junit-team/junit4#226]
Suppose we have two classes:

```java
// A.java
public class A
{
}

// Main.java
import junit.framework.JUnit4TestAdapter;
import junit.framework.Test;
import junit.framework.TestResult;

public class Main
{
    public static void main(String[] args)
    {
        Test test = new JUnit4TestAdapter(A.class);

        System.out.println(test.countTestCases());

        TestResult res = new TestResult();
        test.run(res); // Running a test class with no tests??
        System.out.println(res.wasSuccessful());
    }
}
```

If I run this application, Main class produces this output:

```java
1
false
```

So, class A doesn't have any test methods, but JUnit4TestAdapter says that it does!

**Comment by kcooney** [comment]
(doing a pass at closing old issues)

Given 1) JUnit 4-style tests were introduced a long time ago 2) JUnit 5 is around the corner and 3) this only affects an error case (a test case with no tests), I'm not sure it's worth fixing this
