### ISSUE TITLE
Allow programatic generation of Suite classes

### ISSUE THREAD

**Issue by Yishai** [junit-team/junit4#41]
Add an annotation to the Suite class called SuiteMethod that would annotate
a method that returns a Class[] array. The Suite would then be built from
the two annotations, Suite.SuiteClasses plus any methods on the class (and
enforce that they be public, static, take no parameters and return a
Class[] array) that are annotated with Suite.SuiteMethod and build the
Suite as a combination of all of the Arrays returned. Multiple methods
return the same class, my preference would be to only run the class once.

An alternative would be to create a separate runner for a class has the
@SuiteMethod.

**Comment by conneronx** [comment]
Way to kill something that would be super useful.
