### ISSUE TITLE
Allowing stopping of tests externally

### ISSUE THREAD

**Issue by abyx** [junit-team/junit4#47]
[This ticket was copied from the old sourceforge tracker, original issue created Feb 21 2008]
Currently, the only way to stop tests that are being run using JUnitCore,
is to implement a Runner that then has access to RunNotifier.pleaseStop().
This was possible to do in JUnit3 using TestResult.stop().

In my work place we found this feature very useful, as had programs that
simply ran tests and processed the output. These programs weren't too
coupled with JUnit, they simply listened to TestResult and processed the
data. We would like to do the same thing with Result and RunListener.

My suggestion is simply to add pleaseStop() to JUnitCore (which is always
used for simply running tests).

Thanks,
Aviv.

**Comment by sdettmer** [comment]
well, and how to realize this now?

Stackoverflow proposes the following workaround:
```java
JUnitCore jUnitCore = new JUnitCore();
Field field = JUnitCore.class.getDeclaredField("fNotifier");
field.setAccessible(true);
RunNotifier runNotifier = (RunNotifier) field.get(jUnitCore);
runNotifier.pleaseStop();
```
(extended JUnit 4 sometimes seems needlessly complex)

**Comment by marcphilipp** [comment]
@sdettmer Please open a new ticket if this feature request is still relevant to you. Please give us a little insight into your use case. Thanks!
