### ISSUE TITLE
Provide option for FilterRequest to not fail upon leaving no tests remaining

### ISSUE THREAD

**Issue by cmosher01** [junit-team/junit4#486]
Currently, if FilterRequest filters out all tests leaving none remaining, it generates a bogus test "Filter.class" that automatically FAILs with "No tests found matching..." error message. Would like to have a way to disable this; having no matching tests could be perfectly acceptable in some situations. If this were disabled, FilterRunner.getRunner could instead return a new IgnoredClassRunner.

**Comment by xsimo** [comment]
I would like this issue to be reopened. I have tested with the explicit `failIfNoTests=true` and it still throws the `No tests found matching com.example.ExampleCategory from org.junit.runner.Request$1@2345678`
and this was with junit version 4.13.2.
So the setup is any multi-module project, when trying to configure surefire ( or failsafe ) maven plugin by specifying the `<groups>com.example.ExampleCategory</groups>` if one of the submodule contains tests from which none of them matches that test Category, the execution fails.

**Comment by kcooney** [comment]
@xsimo have you reached out to the maven maintainers?
