### ISSUE TITLE
Toward multi-module JUnit: separate assertion mechanisms from core

### ISSUE THREAD

**Issue by pholser** [junit-team/junit4#537]
Assertions and assumptions form implicit contracts between JUnit tests and test runners. There are several ways to satisfy the assertion contract that don't need to get Hamcrest involved at all. To satisfy the assumption contract, you have to use org.junit.Assume, or construct instances of the internal AssumptionViolatedException and bring in Hamcrest as a dependency. I think it'd be a good idea to tease out Assert/Assume, and anything else that helps test writers express test outcomes (matchers, maybe?) into another library that depends on Hamcrest, and get Hamcrest out of JUnit's core.

I'm imagining JUnit becoming a multi-module project (much like Hamcrest is!) with a "core" (annotations for methods, the internal machinery for running tests and stuff for writers of test runners), "assertions", "runners" (specific runners like Suite, Categories, Parameterized, etc. that leverage machinery from the core but needn't  be in the core itself)...maybe more.

I wouldn't anticipate doing this for 4.x, but might necessitate a new major version.

**Comment by kcooney** [comment]
JUnit 5 is much more modular. We couldn't do this in JUnit 4 without breaking many people, and we ready have a next major release in JUnit 5, so I am closing
