### ISSUE TITLE
using @Rule TemporaryFolder inside @Before

### ISSUE THREAD

**Issue by francisdb** [junit-team/junit4#58]
I'm explaining the issue with a unit test:

public class TemporaryFolderTest {

```
@Rule
public TemporaryFolder temporaryFolder = new TemporaryFolder();

@Before
public void before(){
    System.out.println(temporaryFolder.getRoot());
    // fails
    // assertNotNull(temporaryFolder.getRoot());
}

@Test
public void testTempFolder(){
    System.out.println(temporaryFolder.getRoot());
    assertNotNull(temporaryFolder.getRoot());
}
```

}

**Comment by lucasvc** [comment]
Why is this issue closed?
This code is too uneasy:

```
@Rule
public TemporaryFolder fileRule = new TemporaryFolder();
private File folder;

@Before
public void setUp() throws Exception {
    folder = fileRule.newFolder();
}
```

**Comment by panchenko** [comment]
@lucasvc What's the problem exactly?

**Comment by lucasvc** [comment]
```
@Rule
public TemporaryFolder folderRule = new TemporaryFolder();

@Before
public void setUp() throws Exception {
    when(provider.getFolder()).thenReturn(folderRule.getRoot());
}
```
`IllegalStateException` is thrown because folder is not yet created.
So I could call folderRule.create(), which says _Do not use_.

How can I use the rule at `@Before`?

**Comment by panchenko** [comment]
I've just checked it works in junit 4.12.

**Comment by lucasvc** [comment]
d'0h >.<
I'm at 4.11, sorry for not telling before.

**Comment by kcooney** [comment]
@lucasvc it should work in 4.11. Could you provide a full example including the test class definition? How are you running the test?

**Comment by lucasvc** [comment]
Ok, found the problem. Seems caused by the [`powerkmock`](https://github.com/powermock/powermock) runner:
```
@RunWith(PowerMockRunner.class)
```

Using other runner (like the `MockitoJUnitRunner` one) works as expected.

**Comment by kcooney** [comment]
@lucasvc your problem appears to be https://github.com/powermock/powermock/issues/427 which is apparently fixed by https://github.com/powermock/powermock/pull/606

Alternatively usehttps://github.com/powermock/powermock/wiki/PowerMockRule

**Comment by lucasvc** [comment]
@kcooney really thanks for the links!
