### ISSUE TITLE
@Theory does not support 'expected' for expected exceptions, unlike @Test

### ISSUE THREAD

**Issue by pimterry** [junit-team/junit4#602]
I have also just run into the issue discussed at http://stackoverflow.com/questions/13050412/expect-exception-when-using-junit-theory

It would be useful if you could define theories like the below:

``` java
@Theory(expected = SomeException.class)
public void shouldThrowAnExceptionForAllBadThings(Object thing) {
    assumeThat(thing, isBadThing())
    tryToPerformOperationWith(thing);
}
```

**Comment by kcooney** [comment]
assertThrows() resolves this.
