### ISSUE TITLE
Remove junit.framework from 4.x releases

### ISSUE THREAD

**Issue by gaffa** [junit-team/junit4#618]
I am sure it was discussed before but I cannot find anything. Why do we still provide 3.x package junit.framework in the 4.x releases?

**Comment by martinanderssondotcom** [comment]
Why? Because people are inherently not rational, and afraid of others. Apparently, the JUnit authors are no exception.

We all "know" that the cost for 5 million programmers worldwide to constantly decipher a list of possible conflicting imports and the googling this entails is so much greater than the cost of breaking "backward compatibility", only provided for the few of us who initially refuse to actually write code and maintain our software, but eventually has to regardless. The small minority oppress the majority.

Many projects before has proven that with added complexity and confusion, eventually, the entire product dies in favor of a new kid. Wake up people.

**Comment by kcooney** [comment]
@martinanderssondotcom the methods in `junit.framework.Assert` are deprecated, so for new JUnit4-style tests people will hopefully see the problem without looking at imports.

In any case, we avoid making major breaking changes in a minor release, and there will be no more major releases of this project, so I don't see a path forward. Forcing everyone who wants the fixes in 4.13 to migrate all their JUnit tests away from `TestCase` will prevent many projects from upgrading. Splitting into two jars would be a large amount of work (and again, questionable for a point release).

Long term, JUnit 5 is the path forward, and it doesn't include the 4.x jars.

**Comment by kcooney** [comment]
BTW, I do appreciate the different point of view, but I don't think it's helpful to refer to people you haven't met as not rational. I realize that you are probably very passionate about you projects (and we are, too) and that passion can affect our language,  but I hope we can be more mindful of our word choices and tone.

Thanks.

**Comment by martinanderssondotcom** [comment]
lol you are absolutely right. My impatience and frustration with completely different products got the best of me. I am genuinely sorry.

To be honest, I think JUnit actually set an example with the addition of another package. And.. JUnit added JavaDocs on the old package as belonging to JUnit 3.x.

I happened to stumble across this thread and felt so much with the original poster. But this is out of frustration with completely different products. I fight this fight every day trying to decipher what is old what is new. Too often it's not even documented, at least not on a JavaDoc level.

Change is a necessity for innovation and improvement. I think simplicity and "out with old" has never been more important in our modern day and age with "fatigue" hitting just about every language and tech stack in the market. If every product maintaining their backward compatibility could perform the same trick 
as JUnit and branch off in a new package/module then that would be awesome. But unfortunately they often mix old with new. Fast forward ten years and it's just a complete nightmare trying to make sense out of it all and the websites and reference guides trying to describe ten different ways of accomplishing the same thing has to spend most of its text describing "historical reasons" and making up lame excuses.

I definetely do not call any of this rational. That's just an opinion of course. And it was wrong of me to call other ppl irrational. My most sincere apologies for this. Again, my rant had actually very little to do with JUnit who has served me well and been a pleasure to work with throughout the years :)
