### ISSUE TITLE
Make @FixMethodOrder inherited annotation

### ISSUE THREAD

**Issue by lgoldstein** [junit-team/junit4#642]
I think that _@FixMethodOrder_ should be made _@Inherited_. The reason for this is that in many of my projects I use a base class as the "root" of all test classes and find it very useful to be able to decide something that can affect all my tests - _@FixMethodOrder_ being one of them.

**Comment by hartmut27** [comment]
I can confirm,  e.g.
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
is getting inherited to subclasses now
(tested with junit-4.12)

**Comment by marcphilipp** [comment]
That's good to hear! :-)

**Comment by lgoldstein** [comment]
@hartmut27 I don't see how this happens - the code for _@FixMethodOrder_ does not contain the _@Inherited_ annotation.

**Comment by hartmut27** [comment]
@lgoldstein Sorry, my mistake! - You're correct, it is not related to @FixMethodOrder. 
In my test case even I omit @FixMethodOrder in the parent class, all tests are processed in a method-name-sorted way. Don't not yet know why, since in the past the execution was not ordered by method name.
