### ISSUE TITLE
RunListener testRunStarted method not will not be run.

### ISSUE THREAD

**Issue by wutingbupt** [junit-team/junit4#644]
Hi there,

I try to create our own run listener and I also create our own runner: DemoJunit4Runner

In this runner, I try to override the run method and add this listener at run method.

Later I call super.run(xx)

But I founded testRunStarted will not be called, but related finish method will be called.

BTW, the listener works well if I start it through the JcatCore directly add it.

I create a simple class and add a RunWith(my demo runner)

the result is like I said before, the testRunStarted will not be called.

Did I missed something?

Br,
Tim

**Comment by shark-horse** [comment]
The only simple solution I have found is to use a static constructor in some kind of shared class. Just use the class somehow when you want it to initialize something, and its static constructor will run once and never again.

You can still use a test listener for e.g. routines to run on failure and at the end of the test run even if you like to run arbitrary sets of tests in eclipse or with Maven.
