### ISSUE TITLE
Parameterized Suites

### ISSUE THREAD

**Issue by yterradas** [junit-team/junit4#655]
hi, 

i was wondering if there are any plans to parameterized suite classes. i refer to a way to annotate suites with @RunWith(Parameterized.class), add the parameters inside the suite, therefore having all of the classes in the @Suite.Classes() run with those parameters. after looking at the code i think it's possible by making one of the constructors in SuiteClass protected instead of private, thus maintaining encapsulation. i can go more in details of my possible solution, unless your, junit team's, intention was never to have or allow such feature. also if there is, currently, a way to accomplish that could you be kind to briefly explain it, please. thank you in advance for your time.

**Comment by yterradas** [comment]
if there is still interest in this feature I can take a look again to formulate a description of the work.

**Comment by PeterWippermann** [comment]
I had the same use case and implemented such a `ParameterizedSuite`. Have a look at it, if you like: https://github.com/PeterWippermann/parameterized-suite

**Comment by kcooney** [comment]
I agree with David on this. If making Suite easier to extend would help, please file a bug or create a pull.

**Comment by PeterWippermann** [comment]
Well, that was my intention when I opened #1338 .
