### ISSUE TITLE
New Method Proposal: ExpectedException#expect(Throwable, Callable)

### ISSUE THREAD

**Issue by Tibor17** [junit-team/junit4#706]
Many times I needed to assert a block of code in test-method to throw an exception, and check how the throwing block has changed values.
I had to use try-catch.

So I would like to implement new method with such of signature `ExpectedException#expect(Throwable, Callable)`.

Usage:

`Object obj = expect( Exception.class ,  new Callable() { ..do and return something.. });`

Usage of Lambda in Java 8:

`expect( Exception.class ,  () -> { ..do and return something.. }  )`

**Comment by kcooney** [comment]
Fixed in #1154
