### ISSUE TITLE
Exception assertions improvement.

### ISSUE THREAD

**Issue by ghost** [junit-team/junit4#722]
Hi guys.

There are at least 3 well known ways to check that some exception is thrown and has specific properties (verifiable by `matcher`):

`try-catch`:

``` java
@Test
public void assertSomeExceptionIsThrown() {
   try {
       ... // block of code under test
       fail("Expected test to throw SomeException");
   } catch (SomeException e) {
       assertThat(e, matcher);
   } catch (Throwable t) {
       fail("Expected test to throw SomeException, but caught: " + t);
   }
}
```

`@Test(expected = ...)`:

``` java
@Test(expected = SomeException.class)
public void assertSomeExceptionIsThrown() {
   ... // block of code under test
}
```

`@Rule`:

``` java
@Rule
public ExpectedException thrown = ExpectedException.none();

@Test
public void assertSomeExceptionIsThrown() {
   thrown.expect(matcher);
   ... // block of code under test
}
```

All the caveats of these methods are also well known. `try-catch` is very wordy and overcomplicated for the most cases. `@Test(expected = ...)` is too simple -- the only thing you can check is the class of exception. `@Rule` is a bit better but it has almost the same disadvantage. While with `@Test(expected = ...)` you cannot say where
exactly the exception was thrown from, with `@Rule` you have to be cautious. You'll have to state your expectations just before the intended block of code. Otherwise JUnit will be pretty happy while you will get a false-positive test:

``` java
@Rule
public ExpectedException thrown = ExpectedException.none();

@Test
public void assertSomeExceptionIsThrown() {
   thrown.expect(matcher);
   ... // another block of code that can throw SomeException
   ... // block of code under test
}
```

Both of them (`@Test(expected = ...)` and `@Rule`) have the same side effect that as soon as exception is thrown the test is over. So throwing an exception would be the last thing you can check in your test. That's not very handy for more sophisticated tests.

What I suggest is to provide new methods in `org.junit.Assert` and `org.junit.Assume` to address the limitations of `@Test(expected = ...)` and `@Rule` and to take the best of `try-catch` while cutting the amount of boilerplate code needed for it.
`org.junit.Assert`:

``` java
public static <T extends Throwable> void assertThrows(ThrowingBlock block, Class<T> clazz);
public static void assertNotThrows(ThrowingBlock block);
public static <T extends Throwable> void assertThrows(ThrowingBlock block, Class<T> clazz, Matcher<? super T> matcher);
public static <T extends Throwable> T assertThrowsAndReturn(ThrowingBlock block, Class<T> clazz);
```

Where `ThrowingBlock` is simply a:

``` java
/**
 * Piece of code which execution could result in throwing an exception.
 */
public interface ThrowingBlock {

    void execute() throws Throwable;
}
```

Similar methods could be included in `org.junit.Assume`.

OK, here is how it's supposed to work:

``` java
@Test
public void assertWithClass() {
    Assert.assertThrows(new ThrowingBlock() {
        @Override
        public void execute() throws Throwable {
            account.withdraw(10);
        }
    }, InsufficientFundsException.class);
}

@Test
public void assertWithClassAndMatcher() {
    Assert.assertThrows(new ThrowingBlock() {
    @Override
        public void execute() throws Throwable {
            account.withdraw(10);
        }
    }, InsufficientFundsException.class, hasMessage(startsWith("Not enough")));
}

@Test
public void assertAndReturn() {
    InsufficientFundsException e = Assert.assertThrowsAndReturn(new ThrowingBlock() {
        @Override
        public void execute() throws Throwable {
            account.withdraw(10);
        }
    }, InsufficientFundsException.class);
    // assertions go after the exception block
    // which is more natural than with @Rule
    assertThat(e.getMessage(), hasMessage(startsWith("Not enough")));
    assertTrue(e.getBalance() < e.getRequestedAmount());
}
```

It may seem wordy, but the only thing that is big here is the the anonymous class. Boilerplate code is completely gone.
The extra bonus here is that being 100% usable right now, after release of jdk8, these methods will become even more usable:

``` java
@Test
public void assertWithClass() {
    Assert.assertThrows(() -> account.withdraw(10), InsufficientFundsException.class);
}

@Test
public void assertWithClassAndMatcher() {
    Assert.assertThrows(() -> account.withdraw(10), InsufficientFundsException.class, hasMessage(startsWith("Not enough")));
}

@Test
public void assertAndReturn() {
    InsufficientFundsException e = Assert.assertThrowsAndReturn(() -> account.withdraw(10), InsufficientFundsException.class);
    assertThat(e.getMessage(), hasMessage(startsWith("Not enough")));
    assertTrue(e.getBalance() < e.getRequestedAmount());
}

@Test
public void atmHasNoMercy() {
    for (int i = 0; i < MAX_RETRIES; i++)
        Assert.assertThrows(() -> account.withdraw(10), InsufficientFundsException.class);
}
```

All this is possible with zero effort from JUnit because `ThrowingBlock` is a Functional Interface.

I have working prototype of it. If you're interested I can submit it for review.

Thanks.

**Comment by adrianosimoes** [comment]
Haven't this been fixed in Junit 5 with assertThrows?
Since as far as I know JUnit 4 will always be Java 7 compatible, should this be closed?

**Comment by kcooney** [comment]
@adrianosimoes JUnit 4.x also has `assertThrows` so yes, this can be closed.
