### ISSUE TITLE
Make Enclosed runner not try to run the tests in static nested classes without test methods

### ISSUE THREAD

**Issue by vinaybansal** [junit-team/junit4#728]
The Enclosed runner treats all static nested classes as test classes. If any static nested classes have no methods annotated with `@Test` you will get a failure. This prevents you from having a nested class that is a helper class. It would be great if Enclosed would ignore those classes.

Suggestion: Make Enclosed runner ignore all the inner classes annotated with @Ignore just like it works for ignoring the tests with @Ignore.

```
@RunWith(Enclosed.class)
public class RootTest {

  @Ignore
  public static class B {
    ......
  }

  public static class FooTest {
    @Test
    public void testFoo() {
      B b = new B();
      ....
    }
  }
}
```

**Comment by adrianosimoes** [comment]
I tried this with JUnit 4.11 and I didn't got any error if I put the @Ignore on the B class.
Probably fixed already.

 ```
@RunWith(Enclosed.class)
public class Test{
	  @Ignore
	  public static class B   {
	        public static void test(){}
	  }
	  public static class FooTest {
	    @Test
	    public void testFoo() {
	     B.test();
	    }
	  }
	}
```

**Comment by ajburley** [comment]
Thanks @adrianosimoes I just confirmed the same with JUnit 4.13.1. Probably this GitHub issue could be closed.

**Comment by marcphilipp** [comment]
Thanks for the feedback!
