### ISSUE TITLE
Add support for test pre-processors

### ISSUE THREAD

**Issue by vasiliygagin** [junit-team/junit4#766]
Currently in order to apply any pre-processing, common approach is to override Runner (or subclass of it).
For example to add Spring Framework injection I'd use:

```
@RunWith(SpringJUnit4ClassRunner.class)
```

And for Unitils support I'd use:

```
@RunWith(UnitilsJUnit4TestClassRunner.class).
```

But what happens when you need support for both?
Unitils actually is trying to solve this problem by supporting some (but not all) of Spring annotations.

It would benefit Java world if JUnit would support something like this:

```
@ProcessWith({SpringJUnitTestProcessor.class, UnitilsJunitTestProcessor.class})
```

In this case default BlockJUnit4ClassRunner will be used but listed processors will take care of their own responsibilities and would not have to know about each other.
Each of the processors would have to implement so common interface with a method like this:

```
public void prepareTest(Object testInstance, Method testMethod).
```

If there is an interest in this features, I'd like to contribute.

**Comment by bangnab** [comment]
As far as I understand, this has been solved in JUnit 5 with the Extention API (see http://junit.org/junit5/docs/current/user-guide/#extensions). So I propose that the issue be closed.

**Comment by marcphilipp** [comment]
Spring does now provide Rules:
http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/test/context/junit4/rules/SpringClassRule.html

Moreover, the JUnit Jupiter API was designed with composability of such pre-processors as one of its main design goals.

So, indeed, I think this issue can be closed! Thanks, @bangnab for bringing it to my attention! 👍
