### ISSUE TITLE
Hamcrest-all 1.3 with JUnit 4.11 throws exception

### ISSUE THREAD

**Issue by apreg** [junit-team/junit4#872]
Hi,

In the ExpectedException class there is this import:
`import static org.hamcrest.CoreMatchers.containsString;`
which cannot be resolved if you use hamcrest-all simply because the containsString method is in `org.hamcrest.Matchers.`

**Comment by vlio20** [comment]
@apreg , how did you solve this issue?

**Comment by apreg** [comment]
sorry, I cannot remember

**Comment by stefanbirkner** [comment]
You should always avoid to use hamcrest-all together with JUnit because hamcrest-all contains classes of hamcrest-core. Please use [hamcrest-library](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22hamcrest-library%22) if you need more than the core matchers.
