### ISSUE TITLE
TestWatcher.failed should be called before @After methods

### ISSUE THREAD

**Issue by axelfontaine** [junit-team/junit4#906]
Currently it is not possible to introspect the state of object created in @Before and destroyed in @After methods in a TestWatcher.

Calling TestWatcher.failed before @After methods would enable this. This is a great help for gathering context information for diagnosing the problem, before this information is lost.

**Comment by HTrustProject** [comment]
The following article describes how to use a TestWatcher for taking screenshots: http://www.thinkcode.se/blog/2012/07/08/performing-an-action-when-a-test-fails

**Comment by heese** [comment]
The following article describes how to use a TestWatcher for taking screenshots: http://www.thinkcode.se/blog/2012/07/08/performing-an-action-when-a-test-fails
