### ISSUE TITLE
Duplicate file error while using jUnit in Android apps

### ISSUE THREAD

**Issue by mustafa01ali** [junit-team/junit4#929]
While using jUnit in Android applications, if any other referenced library has a file named "LICENSE.txt", the APK generation fails with the following error - 

```
Error generating final archive: Found duplicate file for APK: LICENSE.txt
```

A simple renaming of LICENSE.txt to LICENSE-junit.txt would make the lives of a ton of Android developers easier :)

**Comment by vlsi** [comment]
It is really sad JUnit uses non-standard LICENSE name.

I think LICENSE should be included in `META-INF/` folder, so standard resource transformers can understand how to deal with licenses.

See https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ApacheLicenseResourceTransformer
