### ISSUE TITLE
Enhancement: BigDecimal support for assertEquals()

### ISSUE THREAD

**Issue by pbenedict** [junit-team/junit4#95]
Using JUnit to test BigDecimal values is always a sore point. It is because BigDecimal considers precision using equals() but ignores it in compareTo(). The best way to handle this would be a new assertEquals method that allows precision to be optionally evaluated. You can also add an alternative method that accepts a message:

public static void assertEquals(BigDecimal expected, BigDecimal actual, boolean precisionMatters) {
    if (precisionMatters) {
        Assert.assertEquals(expected, actual);
    } else {
        Assert.assertEquals(0, expected.compareTo(actual));
    }
}

**Comment by ptahchiev** [comment]
I don't think using the hamcrest matcher's fixes this issue. For example this code:

````
   assertThat(product.getRating(), is(equalTo(new BigDecimal("2.3"))));
````

will produce this result:

````
Expected: is <2.3>
     but: was <2.30000>
````

I think junit or hamcrest still needs `isNumericEquivalent` method.

**Comment by marcphilipp** [comment]
Have you tried using [`comparesEqualTo`](http://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/Matchers.html#comparesEqualTo(T))?

**Comment by ptahchiev** [comment]
Yes, `comparesEqualTo` actually works. Thanks.

**Comment by marcphilipp** [comment]
Here's a cheat sheet I created some time ago:
http://www.marcphilipp.de/blog/2013/01/02/hamcrest-quick-reference/
