### ISSUE TITLE
ComparisonFailure reports all failures as "expected: null<null> but was: null<null>"

### ISSUE THREAD

**Issue by dsaff** [junit-team/junit4#976]
Still debugging locally, but since my local gradle build picked up 4.12-beta-1, all string comparison failures are reporting

org.junit.ComparisonFailure: expected: null<null> but was: null<null>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)

This is on comparison of two obviously non-null strings, for example assertEquals("a", "b").

This appears to be affecting our whole local team, but still may be something odd about our setup.  Continuing to investigate.

**Comment by navels** [comment]
FYI, you missed ArrayComparisonFailure.fCause, which disappeared in 4.12.  This caused much hair-pulling for us as it caused a gradle test task to fail with no apparent cause.  We had upgraded to gradle 2.4 which bundles junit 4.12 whereas our application classpath pointed to 4.11.
