### ISSUE TITLE
ErrorCollector is not working for me - can it run using Cucumber Runner class?

### ISSUE THREAD

**Issue by JasonSmiley** [junit-team/junit4#983]
ErrorCollector doesn't seem to work, even when I do the most basic test.

See code:

```
@Rule
public ErrorCollector test = new ErrorCollector();

@When("I test my code")
public void I_test_my_code(){
    //Sandbox step - put code here you want to test
    //new TestCase("Testing Error Handler 1", false, equalTo(true), false).runTest();
    //new TestCase("Testing Error Handler 2", false, equalTo(true), false).runTest();
    //new TestCase("Testing Error Handler 3", true, equalTo(true), false).runTest();

    test.checkThat("Testing Error Handler 1", false, equalTo(true));
    test.checkThat("Testing Error Handler 2", false, equalTo(true));
    test.checkThat("Testing Error Handler 3", true, equalTo(true));
}
```

Note, I am using Cucumber JVM to run my tests.

**Comment by sarpk** [comment]
Please make verify public. I am having the same issue despite just using plain JUnit with mvn integration.

**Comment by kcooney** [comment]
@sarpk are you using cucumber? If so, I suggest commenting on the cucumber bug. If not, can you provide a simple reproducible test case?

**Comment by sarpk** [comment]
@kcooney no I am using testng not cucumber.

**Comment by kcooney** [comment]
@sarpk sorry, you said that in your post, and I misread it.

Users that use JUnit shouldn't need to call `verify()`. It is ultimately Marc's CL, but personally I would rather not make a method public that shouldn't be called by end users. I suggest asking on the TestNG forums if they have something like `ErrorCollector`. Alternatively, migrate your tests to JUnit :-)
